### ISSUE TITLE
Support Spark 3.4 for BigQuery Pushdown

### ISSUE THREAD

**Issue by idc101** [GoogleCloudDataproc/spark-bigquery-connector#1000]
Is it planned to support pushdown to BQ with Spark 3.4?

Thanks

**Comment by davidrabinowitz** [comment]
Can you please elaborate which pushdown is missing? Notice that Filtering and RequiredColumns are already implemented, as well as RuntimeFiltering for spark 3.2 and above

**Comment by idc101** [comment]
Calling `enablePushdownSession(spark)` for spark 3.4 throws this exception: https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/fbd106c057ce795a36bed71fec2eadc857f60d65/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/BigQueryConnectorUtils.java#L52

**Comment by davidrabinowitz** [comment]
Thanks for interest in query pushdown! This feature has not been officially released, and due to its nature it needs deep integration with each Spark version due to internal changes Spark are making. We plan work on it in the upcoming months.

**Comment by ihrimech** [comment]
Thanks for this feature ! Are there more information about its release for Spark 3.4 ?

**Comment by sid-habu** [comment]
@davidrabinowitz Do we need to enable `enablePushdownSession(spark)` on Spark 3.4.2 for basic filtering pushdown? Enabling pushdown explicitly throws 

```
Could not find an implementation of com.google.cloud.spark.bigquery.pushdowns.SparkBigQueryPushdown that supports Spark version 3.4.2
```
