### ISSUE TITLE
Excessive logging on executors when using Arrow data format with DateTime columns

### ISSUE THREAD

**Issue by dchristle** [GoogleCloudDataproc/spark-bigquery-connector#1011]
We have a job performing reads of large tables in BigQuery that generates about 250 million log messages over each 5 minute period. It appears to be related to DateTime column handling. There isn't an analogous type supported between BigQuery's DateTime and Spark, so it's not surprising that some warning is generated (e.g. some typecasting must occur), but the magnitude of logs is excessive.

The log messages show up in the executors (not the driver), and are all repeats of the following:
```
23/07/06 22:49:59 INFO Field: Unrecognized extension type: google:sqlType:datetime
```

I couldn't track down this exact log message, but a GitHub code search revealed `Unrecognized extension type` log messages in an Apache Arrow project. Arrow is used by the connector as an intermediate format for transferring data between BigQuery and Spark, and when I pass the option `.option("readDataFormat", "AVRO")` when reading the BigQuery table, the log messages are gone. I suspect the log message is being emitted for every row processed. Ideally, it should be emitted no more than once per `DataFrame`. 

For reference, this is happening when using Spark 3.4.1 on Kubernetes with version 0.31.1 of the shaded Spark-BigQuery connector.

**Comment by davidrabinowitz** [comment]
This line comes from the Arrow library, @idc101 's solution is a good way to cope with it
