### ISSUE TITLE
BigQueryClientFactory is not cached correctly, resulting in thread leak

### ISSUE THREAD

**Issue by nikolay-voskresenskiy-db** [GoogleCloudDataproc/spark-bigquery-connector#1018]
I have a persistent spark application that does a job on schedule (and it also queries multiple tables in BQ), and after a couple of runs I see thousands of Gax-* threads sitting in the thread dump. Eventually it leads to performance and stability issues.

As far as I can tell, the root cause is the interaction of BigQueryRelationProvider and Guice injector inside, it creates a new BigQueryClientFactory for each new read which makes it create a new BigQueryReadClient in turn, which then creates InstantiatingExecutorProvider which in turn creates a ScheduledThreadPoolExecutor with a fixed thread pool size.

If the data frame uses a union of multiple tables and/or does unions to achieve explicit partitioning, the thread count balloons very fast.

A simple workaround is to kill the driver vm after each unit of work, but I still think this is an issue and could affect more complex spark jobs.

**Comment by davidrabinowitz** [comment]
Which version of the connector are you using?

**Comment by nikolay-voskresenskiy-db** [comment]
0.30.0

**Comment by suryasoma** [comment]
Can you please use the latest version of the connector? 
This issue has been addressed in https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/965
