### ISSUE TITLE
Numeric -> decimal(38,9) -> BigNumeric issue with v0.31.0

### ISSUE THREAD

**Issue by idc101** [GoogleCloudDataproc/spark-bigquery-connector#1031]
Hi,

With the change to the numerics handling in v0.31.0 it is no longer possible to read/write numerics, they all get converted to BigNumerics.

For example, I read a Numeric column from a BigQuery table and in Spark this is `decimal(38, 9)` but when writing back to BigQuery that is written as a BigNumeric.

I believe this is to do with the decimal type being paramertised. According to https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#decimal_types an unparameterised Numeric is 38,9 but if it is parametrised the max precision is 29, but every Spark decimal is parametrised.

So if the decimal we are writing can fit into the unparameterised BigQuery Numeric can we use that? Something like:
- decimal(p<29,s) => numeric(p, s)
- decimal(29<=p<=38, s<=9) => numeric
- decimal(p>38,s>9) => bignumeric

**Comment by bbarodia** [comment]
I had the same issue which was answered , https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/1027

**Comment by davidrabinowitz** [comment]
Hi @idc101 , can you please share a reproduction code? Also, please check issue #1027 mentioned above, as the recent change forces the BigQuery numeric restrictions that are needed in order to properly write Decimals into BigQuery

**Comment by davidrabinowitz** [comment]
FYI, PR #1033

**Comment by davidrabinowitz** [comment]
Fixed in release 0.32.1
