### ISSUE TITLE
how to use 'datetimeZoneId' config in Spark Bigquery Connector

### ISSUE THREAD

**Issue by psonilloyds** [GoogleCloudDataproc/spark-bigquery-connector#1042]
There is a 'datetimeZoneId' config in Spark Bigquery Connector. How this config works ? I did follow the explanation and documentation https://github.com/GoogleCloudDataproc/spark-bigquery-connector, but couldn't understand completely.

A working example would really help to understand how this config works exactly. Can someone please explain how to use 'datetimeZoneId' by giving a working example.

**Comment by isha97** [comment]
Thanks for pointing it out. This config is not supported anymore. We support TimestampNTZ on spark 3.4 and above.
