### ISSUE TITLE
Try to clarify the pushAllFilters setting

### ISSUE THREAD

**Issue by lchen4snap** [GoogleCloudDataproc/spark-bigquery-connector#1045]
The README mentions that for **readDataFormat**
```
Data Format for reading from BigQuery. Options : ARROW, AVRO Unsupported Arrow filters are not pushed down and results are filtered later by Spark. (Currently Arrow does not suport disjunction across columns).
(Optional. Defaults to ARROW)
```
Does this mean by default, it's ARROW and pushAllFilters won't work?

But from **pushAllFilters** in the same README, this setting is default to **true**. 
```
If set to true, the connector pushes all the filters Spark can delegate to BigQuery Storage API. This reduces amount of data that needs to be sent from BigQuery Storage API servers to Spark clients.
(Optional, defaults to true)
```

The two default setting seems conflict to each other. So by default, does pushAllFilters work as false since ARROW is default?

**Comment by lchen4snap** [comment]
@davidrabinowitz if you could check. Thanks!

**Comment by isha97** [comment]
Thanks for pointing it out. We have updated the Readme with the correct explainations.
