### ISSUE TITLE
Writing empty dataframe in direct mode produces an extra temp table with random number suffix

### ISSUE THREAD

**Issue by ylashin** [GoogleCloudDataproc/spark-bigquery-connector#1051]
Reproduction steps:
- Create target table first on BigQuery for example `CREATE TABLE <dataset>.<table> (id INT)`
- Run Spark shell: `spark-shell --packages com.google.cloud.spark:spark-3.3-bigquery:0.32.2`
- Run the below snippet
```scala
val df = spark.range(100).where("1=2")
df.write.format("bigquery").option("table", <project>.<dataset>.<table>").option("writeMethod", "direct").mode("overwrite").save()
```

I know using table option is deprecated but the same behaviour happens with save+path combo.

![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/2197158/6dac6739-8301-4dbd-b2ab-bbcc4423629e)

What will happen is that a new additional table will be created under same table name + some random suffix.

**Sdie note:** 
I have checked the source code and found stuff like `df.rdd.getNumPartitions == 0` to check if a DataFrame is empty or not.
That works in some cases but not in others in case it matters.

![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/2197158/ee143947-5b10-4d41-938d-d9890bf576c6)

**Comment by isha97** [comment]
This issue was fixed as part of https://github.com/GoogleCloudDataproc/spark-bigquery-connector/commit/a66d23f43a33c183bbb2f701075f89287ce4b582 and is available in the latest version of the connector.

**Comment by ylashin** [comment]
Thanks for the update @isha97
