### ISSUE TITLE
Poor BigQuery write performance on large datasets

### ISSUE THREAD

**Issue by olivermharrison** [GoogleCloudDataproc/spark-bigquery-connector#106]
Because of the way this connector writes to BigQuery, working with large (>40GB) datasets becomes somewhat impractical:
- Temporary data chunks are stored on GCS as ~150MB .parquet files
- Each of those chunks takes ~30 seconds to be produced 
- This results in a write time of more than 2 hours for a 40GB dataset.

## Questions
- Is this the expected behaviour?
- Are there any suggestions/options to improve performance?  (e.g. by increasing the intermediate chunk size)
- Are there any short-term plans to improve write performance?

Thanks in advance!

**Comment by davidrabinowitz** [comment]
@olivermharrison This time does seem to be longer than expected. Do you have a BigQuery reservation? If you do, is it dedicated to processing load jobs?

Also, can you please provide a load job ID so we can take a look on the BigQuery side?

For the long run, we plan to add an [insertAll](https://cloud.google.com/bigquery/streaming-data-into-bigquery) based solution, but no deadline yet.

**Comment by olivermharrison** [comment]
Hi @davidrabinowitz,

1. No, we are using on-demand pricing.
2. Sure, here's a couple of job IDs: `0f8cc680f8ae45b4bdad5d2e50f37605` & `89d0df3e803046259844ccf07239a4d4`. Note that both of these jobs we're manually cancelled after realising how long they would take to complete.
3. Both of those jobs ran on a single node `n1-highmem-4` instance.

 FYI, I've been looking at Dataflow which seems like a better solution for our needs, so I'm no longer actively working with Dataproc.

**Comment by davidrabinowitz** [comment]
Hi @olivermharrison ,

Thanks for the information. If I understand you correctly, there were ~270 Parquet files (40GB/150MB), each took ~30 seconds to be written to GCS. How many executors did you have on that single machine? Also, have you tried to use larger clusters in order to enjoy higher output bandwidth?

**Comment by olivermharrison** [comment]
Yup, that's correct. 

Those jobs ran with the default Spark configuration, so they would've used the default number of executors.

I unfortunately did not try a large cluster in the interesting of savings costs for an initial evaluation
of Dataproc. I now realise that that was probably naive and may well explain the write performance.  

I'm happy to close this issue unless there's any other information you'd like from me. 

Thanks!

**Comment by davidrabinowitz** [comment]
Thanks for the information!
