### ISSUE TITLE
Not able to partition based on string column.

### ISSUE THREAD

**Issue by amandaolens** [GoogleCloudDataproc/spark-bigquery-connector#1064]

**Comment by vishalkarve15** [comment]
@amandaolens We are bound by the partitioning offered by BigQuery, and it is [limited](https://cloud.google.com/bigquery/docs/partitioned-tables#types_of_partitioning) to one of two types:

Integer range partitioning, as described also in issue https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/867
Date/Time partitioning (daily, hourly, monthly, or yearly)
