### ISSUE TITLE
Add Integer based partition Support 

### ISSUE THREAD

**Issue by amandaolens** [GoogleCloudDataproc/spark-bigquery-connector#1065]

**Comment by vishalkarve15** [comment]
@amandaolens we do already have Integer range based partition support.
We are bound by the partitioning offered by BigQuery, and it is [limited](https://cloud.google.com/bigquery/docs/partitioned-tables#types_of_partitioning) to one of two types:

Integer range partitioning, as described also in issue https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/867
Date/Time partitioning (daily, hourly, monthly, or yearly)

**Comment by amandaolens** [comment]
@vishalkarve15  can you share the reference for integer based partition

**Comment by vishalkarve15** [comment]
It's not released yet, you can refer to this for now: https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/README-template.md
You can use the nightly builds to try it out for now (based on your spark version):

gs://spark-lib-nightly-snapshots/spark-2.4-bigquery-0.0.20230808.jar
gs://spark-lib-nightly-snapshots/spark-3.1-bigquery-0.0.20230808.jar
gs://spark-lib-nightly-snapshots/spark-3.2-bigquery-0.0.20230808.jar
gs://spark-lib-nightly-snapshots/spark-3.3-bigquery-0.0.20230808.jar
gs://spark-lib-nightly-snapshots/spark-3.4-bigquery-0.0.20230808.jar
