### ISSUE TITLE
Failling to write to BigQuery using AVRO intermediateFormat

### ISSUE THREAD

**Issue by heyashy** [GoogleCloudDataproc/spark-bigquery-connector#1070]
**Using spark-bigquery-with-dependencies_2.12-0.24.2.jar**

I am trying to write a dataframe with string JSON columns to BigQuery which is failing with the following error:

```
Provided Schema does not match Table <_tableName_> Field <_columnName_> has changed type from JSON to STRING
```

In the scheam the column has been defined as a:
```
StructField("<_columnName_>", StringType(), True, {"sqlType": "JSON"})
```

The write has the following options:
```
.option("useAvroLogicalTypes","true") 
.option("intermediateFormat","AVRO") 
.option("writeMethod", "INDIRECT") 
```

It doesn't seem like the intermediateFormat conversion is passing the metadata to the AVRO file.

**Comment by davidrabinowitz** [comment]
Support for the JSON data type has been added in version [0.28.0](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/releases/tag/0.28.0), please upgrade your connector, preferably to the latest version (0.32.2)

**Comment by heyashy** [comment]
Amazing. Thank you for the speedy reply. I will try that now
