### ISSUE TITLE
array of string is getting save as STRUCT<list ARRAY<STRUCT<element STRING>>> 

### ISSUE THREAD

**Issue by amandaolens** [GoogleCloudDataproc/spark-bigquery-connector#1098]
<img width="1263" alt="Screenshot 2023-10-20 at 6 43 54 PM" src="https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/112611826/e3f5f675-e48a-4a66-b3cd-6af1c325ad69">

**Comment by davidrabinowitz** [comment]
You have three options:

* Switch to the DIRECT write method by adding  `.option("writeMethod", "DIRECT")`
* Set the `enableListInference` option to `true`  by adding  `.option("enableListInference", "true")`
* Set the intermediate format to AVRO   by adding  `.option("intermediateFormat", "AVRO")`

**Comment by amandaolens** [comment]
thanks for quick response @davidrabinowitz . option 3 is working fine for me.
