### ISSUE TITLE
Bad string encoding while reading from BQ

### ISSUE THREAD

**Issue by x-o-r** [GoogleCloudDataproc/spark-bigquery-connector#1100]
French accents are not well restitued while extracting data from a BQ table from Dataproc with BigQuery connector.

When I extract data directly from BQ everything is fine, event with other langage/component (Python Cloud Function for instance) but when I do from Spark I get that kind of stuff `"Saint-Exup?ry"` or `"St-Laurent-M?doc"`

I tried to force encoding like that : 
```
  protected def get_dataframe_reader: DataFrameReader =
    sc.read
      .option("encoding", "ISO-8859-1")
      .format("bigquery")
```

But no change. If I do after the `.format` I get a strange error. I can't find any documentation of the BQ connector options to change string charset.

No change also If I force another encoding 

`.withColumn("site.address.cityName", encode(col("site.address.cityName"), "ISO-8859-1"))`

**Comment by vishalkarve15** [comment]
It appears to be just a rendering issue on Spark side. I tried the following:
```
scala> val df = spark.read.format("bigquery").load("vkarve_ss_test.encodingtest")

scala> df.show()
+-------------------+                                                           
|               name|
+-------------------+
|Saint-Laurent-M?doc|
|      Saint-Exup?ry|
+-------------------+

scala> val rows = df.collect()
rows: Array[org.apache.spark.sql.Row] = Array([Saint-Laurent-M?doc], [Saint-Exup?ry])

scala> rows(0).get(0).equals("Saint-Laurent-Médoc")
res1: Boolean = true

scala> rows(1).get(0).equals("Saint-Exupéry")
res3: Boolean = true
```

**Comment by vishalkarve15** [comment]
You can fix the rendering issue by passing `--conf "spark.driver.extraJavaOptions=-Dfile.encoding=UTF-8"` and `--conf "spark.executor.extraJavaOptions=-Dfile.encoding=UTF-8"` to your spark-submit or spark-shell

**Comment by x-o-r** [comment]
Thank you for your replies. Adding those parameters don't resolve my issue. The retrieved data are not well encoded, not just the rendering of them.

**Comment by vishalkarve15** [comment]
Could you try checking one of the rows like I did?
```
rows(0).get(0).equals("Saint-Laurent-Médoc")
```
