### ISSUE TITLE
BQ labels are not inserted in information schema 

### ISSUE THREAD

**Issue by ojalbhandarkar** [GoogleCloudDataproc/spark-bigquery-connector#1123]
Hi Team,

As mentioned in document I have written below code but it is not inserting data in information schema can anyone help here?
```
spark.conf.set('temporaryGcsBucket', 'bucket_name')
spark.conf.set('materializationDataset','ds_poc')	
spark.conf.set("bigQueryJobLabel.table_id", "helloworld")
df=spark.read.format('bigquery'). \
        option('project',"project_id"). \
        option('table',"ds.table_name"). \
        load()  	
df.registerTempTable("table_name")
spark.sql("select * from table_name limit 10")
```
I was expecting key:value label pair in Information_chema.jobs but not present.

**Comment by davidrabinowitz** [comment]
When reading from a single table we use the BigQuery Storage Read API, and there is no query job which runs on BigQuery

**Comment by ojalbhandarkar** [comment]
thanks for the explanation.
