### ISSUE TITLE
No enum constant com.google.cloud.spark.bigquery.PartitionOverwriteMode.dynamic

### ISSUE THREAD

**Issue by bkinzle** [GoogleCloudDataproc/spark-bigquery-connector#1139]
I started getting this error with version 0.34.0 but wasn't previously -- I'm not sure if it might be related to https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/103.

I'm setting this using:
`SparkSession.builder.config("spark.sql.sources.partitionOverwriteMode", "dynamic")`

I was able to work around the error by moving this config to instead be set as an output option for a data source using key partitionOverwriteMode like this:
`dataframe.write.option("partitionOverwriteMode", "dynamic").save(path)`

Here's more of the error:
```
    .save()
     ^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 1461, in save
    self._jwrite.save()
  File "/opt/conda/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
    return f(*a, **kw)
           ^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o61.save.
: com.google.cloud.spark.bigquery.repackaged.com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: IllegalArgumentException: No enum constant PartitionOverwriteMode.dynamic
  at SparkBigQueryConnectorModule.provideSparkBigQueryConfig(SparkBigQueryConnectorModule.java:100)
  while locating SparkBigQueryConfig

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
PartitionOverwriteMode:       "com.google.cloud.spark.bigquery.PartitionOverwriteMode"
SparkBigQueryConfig:          "com.google.cloud.spark.bigquery.SparkBigQueryConfig"
SparkBigQueryConnectorModule: "com.google.cloud.spark.bigquery.SparkBigQueryConnectorModule"
========================
End of classname legend:
========================
```

**Comment by isha97** [comment]
Hi @bkinzle ,
Please use "DYNAMIC" (in caps) as per documentation.

**Comment by walmaaoui** [comment]
@isha97  in spark its case insensitive, "dynamic" would work. IMO It would be better to support the case insensitivity for easier usage and to be consistent with spark

**Comment by MichalBogoryja** [comment]
hi @isha97, 
I agree with @walmaaoui, having this property in caps generates issues, especially in the code prepared for originally other platforms. Also, in [Spark documentation](https://spark.apache.org/docs/3.5.1/configuration.html) this property is typed in lowercase.
