### ISSUE TITLE
How many times a the bq connector hits a table in bigquery ? 

### ISSUE THREAD

**Issue by PacoBahena** [GoogleCloudDataproc/spark-bigquery-connector#1140]
So from the [previous issue](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/1137) . i got this answer,  `That depends on the query plan and whether the DataFrame is cached or not. The best is to run .explain() on the result.`
 
So from looking at the physical plan in the spark ui, would it be correct to mention that the connector hits bq once every time i see the following on the plan

Scan com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation@4753eb60

![Screenshot 2023-12-06 at 13 26 04](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/15168671/37357e02-d7aa-45f7-a426-0ffbdaa568aa)

**Comment by vishalkarve15** [comment]
That wouldn't be entirely correct. If Spark AQE (adaptive query execution) is enabled (default), Spark can change the plans as it finds runtime statistics. This can rebuild the plan resulting in hitting bq again.
