### ISSUE TITLE
[question][hope-reply]: why here we use Java to implement spark-connector as for supporting spark datasourceV2

### ISSUE THREAD

**Issue by littleDrew** [GoogleCloudDataproc/spark-bigquery-connector#1151]
- Here i see, in this repo we implement spark connector when based on datasourceV1, **we use `scala` program language**
> https://github.com/GoogleCloudDataproc/spark-bigquery-connector/tree/master/spark-bigquery-dsv1
- But as for implement spark connector when based on datasourceV2, **here i see here using `java` language**
> https://github.com/GoogleCloudDataproc/spark-bigquery-connector/tree/master/spark-bigquery-dsv2/spark-3.3-bigquery-lib/src/main/java/com/google/cloud/spark/bigquery/v2

hope some friendly guys, **help to explain, why we use java instead of scala when implement based on datasourceV2** ?
- is there some concern? as we know scala seems may has better feature and simple and less code than java

Thanks~

**Comment by littleDrew** [comment]
@davidrabinowitz hello, could help to explain it, thanks very much~

**Comment by davidrabinowitz** [comment]
Several reasons:
* DSv1 is Scala based, DSv2 is Java based
* Using Java let us reuse some of the code to other BigQuery connectors, such as the Hive-BigQuery connector
* The binary incompatibility between different Scala versions caused some issues for users, and it is very difficult to catch that and give proper error message. This has affected mostly first time users whose immediate reaction was "the connector is broken".
* While Scala is an amazing language, the updates of Java 8 brought it closer (lambdas and streams for example) so we don't sacrifice much

**Comment by littleDrew** [comment]
thanks for your reply~
