### ISSUE TITLE
Support use of bigquery-emulator for integration testing

### ISSUE THREAD

**Issue by JosefNagelschmidt** [GoogleCloudDataproc/spark-bigquery-connector#1169]
- It would be super useful to do integration tests with spark and bigquery
- there is an incubating module for BigQuery in the GCloud module of the official [testcontainers library](https://java.testcontainers.org/modules/gcloud/)
- However, this testcontainer uses plain text for gRPC communaction, while the bigquery connector seems to enforce SSL/TLS
- Additionally, the bigquery-connector seems not to allow for Dummy Credentials (or no credentials) when creating a bigquery connection

If feasible, it would be super helpful to support the [bigquery-emulator](https://github.com/goccy/bigquery-emulator) with this connector.

**Comment by lvijnck** [comment]
yes please.

**Comment by ryszardmakuch** [comment]
@vishalkarve15, are there any updates on this improvement? Do you have this in your roadmap and is there a realistic chance it will be possible in the near future?

**Comment by Luis-ob-uc3m** [comment]
@davidrabinowitz is there any update on the anonymous/dummy credentials issue? Is it going to be added to the roadmap?

**Comment by davidrabinowitz** [comment]
@Luis-ob-uc3m Have you tried to implement an [AccessTokenProvider](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/tree/master/bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/AccessTokenProvider.java)?

**Comment by Fabhi** [comment]
Hey @vishalkarve15, any updates on this? Or any workarounds?

**Comment by Luis-ob-uc3m** [comment]
> Notice that the bigquery-emulator is not a Google product and therefore it will not be used for testing.

Well, it would be such a huge contribution for developers to create an oficial emulator tool.

Providing help with the token issue will help developers to have this tool available in a second, despite not being official, it is a developers need.
