### ISSUE TITLE
Schema mismatch error needs to be more verbose

### ISSUE THREAD

**Issue by vishalkarve15** [GoogleCloudDataproc/spark-bigquery-connector#1175]
The current error message when writing to a BigQuery table is very vague: `"Destination table's schema is not compatible with dataframe's schema"`

The extent of the schema mismatch is unclear and there is no indication if only the mode check (required vs nullable) needs fixing.

https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/76dc21190a8d61585e3a0a82dda5c4af7648b155/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataSourceWriterContext.java#L151

**Comment by jster1357** [comment]
+1 for this. Being able to see what the offending columns are would reduce overall developer friction when building pipelines.

**Comment by vishalkarve15** [comment]
Fixed in version 0.41.0
