### ISSUE TITLE
Regarding snapshot support or incremental fetching of records from bigquery tables via spark bigquery connector

### ISSUE THREAD

**Issue by abraham-parusu** [GoogleCloudDataproc/spark-bigquery-connector#118]
Hi Team,

I am working on integrating spark big query connector and I have a use case to fetch the records from big query table incrementally. I would like to apply a filter using which I need to fetch the records that are inserted after the last processing time and want to process those only. And this last processing time is not a column in the big query table.
I see there is a concept of Snapshot in Storage API. Do we have support for this Snapshot feature in this connector?
Please share if we have any other way of doing it?

Thanks,
Abraham.

**Comment by davidrabinowitz** [comment]
Can you have the tables to be [ingestion time partitioned](https://cloud.google.com/bigquery/docs/creating-partitioned-tables)?

**Comment by abraham-parusu** [comment]
Yes David, we can have partitioned (Ingestion time or time stamp or number) and non-partitioned tables also.

Thanks,
Abraham.

**Comment by davidrabinowitz** [comment]
If you can have ingestion time partitioned table, then you can filter the read by the _PARTITIONTIME pseudo column, which if I understand correctly solves your issue.

**Comment by abraham-parusu** [comment]
Can we have a similar kind of approach for non-partitioned tables? Like fetching from the last snapshot? I think fetching from the last snapshot is feasible based on Storage API docs.
