### ISSUE TITLE
Setting UserDefined schema while writing to BigQuery

### ISSUE THREAD

**Issue by prathapreddy123** [GoogleCloudDataproc/spark-bigquery-connector#120]
Despite the SparkBigQueryOptions class has the option to accept schema, the same was not propagated to LoadJobConfiguration while loading data to bigquery. Due to this the dataframe/dataset schema is used as writer schema.

**Comment by Gaurangi94** [comment]
Hi @prathapreddy123 Indeed `SparkBigQueryOptions` can accept schema as parameter, it is provided by Spark in certain flows, and not by the user. Following our off-line chat, you can change the nullability value of the DataFrame's field before writing it to BigQuery. This can be done in the following mannar:
```
import org.apache.spark.sql.types._
val df = spark.read...
val requiredOnlySchema = StructType(df.schema.fields.map(f => StructField(f.name, f.dataType, false)))
val updatedSchemaDF = spark.createDataFrame(df.rdd, requiredOnlySchema)
updatedSchemaDF.write.format("bigquery")....
```

Please notice that if the intermediate format is ORC, fields are nullable by default.  Please use Parquet as an intermediate format if non-nullable fields are needed.
