### ISSUE TITLE
CreateDisposition is hardcoded to CREATE_IF_NEEDED

### ISSUE THREAD

**Issue by prathapreddy123** [GoogleCloudDataproc/spark-bigquery-connector#121]
Load Job should fail in case when the table doesn't exist instead of creating the table.  Since CreateDisposition is hardcoded to CREATE_IF_NEEDED the table is automatically created. 

Can we parameterize the option for user to control whether the table should be Created (CREATE_IF_NEEDED) or not (CREATE_NEVER) when table doesn't exist already.  If user has chosen CREATE_NEVER option and table is missing then throw error indicating "Table does not exist"

**Comment by davidrabinowitz** [comment]
Will be available in the next version
