### ISSUE TITLE
Unable to write to a partitioned table in spark 3.5 with connector version spark-3.4-bigquery-0.34.0

### ISSUE THREAD

**Issue by hierr** [GoogleCloudDataproc/spark-bigquery-connector#1228]
I am getting the following error:

`com.google.cloud.bigquery.connector.common.BigQueryConnectorException: Failed to write to BigQuery`

`Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Invalid table ID "tb_rh_n1$202405166494015418172". Table IDs must be alphanumeric (plus underscores) and must be at most 1024 characters long. Also, Table decorators cannot be used.`

`Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request`

When trying to write to the following table:

![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/25069969/566f5ac4-3134-4cb4-b30c-111a7d67431c)
![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/25069969/f3fb0ee8-66d9-4ddd-8060-40e23bf5f1ba)
![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/25069969/d22d9c4b-5779-49c8-88f9-bf4835a191c7)

With the following code in spark 3.5 with connector version spark-3.4-bigquery-0.34.0:

![image](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/25069969/04804587-97b2-4d91-a356-9158963e3eab)

**Comment by isha97** [comment]
Hi @hierr ,

I am unable to reproduce this issue, can you please provide the full stack trace?
I will also suggest to use Dynamic Partition Overwrite if you want to only overwrite the partitions which are contained in `df_base` 
Please check for the usage of `spark.sql.sources.partitionOverwriteMode` config in the Readme.

**Comment by isha97** [comment]
@hierr If you are using partitionOverwriteMode as DYNAMIC, you don't need to set the other options such as "partitionType", "partitionField" and "datePartition"
It will automatically overwrite the required partitions.

Can you also please grep the logs for "tb_rh_n1$202405161868823060940"?
Do you see any log for "Deleting table"?

As you mentioned that this error is only recent and was working as expected previously, did something change?

**Comment by hierr** [comment]
Well it's actually news to me that this got implemented, but it works, so good news! It seems to keep throwing the error if i take the config off and set the datePartition though (just as a test). 

By "been doing this write" I meant that I've been doing like this in general, not in this particular cluster/environment.

**Comment by hierr** [comment]
Well it's actually news to me that this got implemented, but it works, so good news! By "been doing this write" I meant that I've been doing like this in general, but not in this particular cluster.

If i take the config off and set the datePartition it keeps throwing the error though (just as a test). There are no logs for that table in particular, and neither for the one that I just got the error. Do you understand why is it trying to write to a table ID in this format? It seems weird to me since the table is day partitioned and also the error calls that "table decorators cannot be used".

**Comment by isha97** [comment]
@hierr we create a temporary table to write to a specific partition but it should be just `tb_rh_n1$20240516`, which is what I got when I tried to reproduce.
I am not able to reproduce the generation of the whole table name `tb_rh_n1$202405166494015418172`.

From your previous comment, are you unblocked now by using partitionOverwriteMode as DYNAMIC?

**Comment by hierr** [comment]
@isha97 Yeah, I don't see a reason for that since the code specifies '20240516' in datePartition. Tbh this cluster is behaving weirdly, throwing random errors and recovering later, so there is that.

But yes, I am unblocked now, so closing this. Many thanks!
