### ISSUE TITLE
Viewing connector metrics

### ISSUE THREAD

**Issue by Swebask** [GoogleCloudDataproc/spark-bigquery-connector#1252]
It isn't very clear from the documentation where the [connector metrics](https://github.com/GoogleCloudDataproc/spark-bigquery-connector?tab=readme-ov-file#connector-metrics-and-how-to-view-them) can be viewed. 
I'm running a job on a Dataproc 2.1 cluster using connector version gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.30.0.jar.

**Comment by davidrabinowitz** [comment]
You can see them in the Spark UI. Please upgrade to version 0.39.1 first as described [here](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#specifying-the--spark-bigquery-connector-version-in-a-dataproc-cluster)

**Comment by Swebask** [comment]
Thank you for your quick response. Upgraded to version 0.39.1, still don't see it. Is there a particular section of the Spark UI to look for the metrics?

**Comment by isha97** [comment]
@Swebask After you go to the applicate page in the Spark UI, navigate to `SQL/Dataframe` section from the top.
Then you can select the job and get the job graph which will show the metrics. (https://spark.apache.org/docs/3.0.0/web-ui.html#sql-tab)

**Comment by Swebask** [comment]
@isha97 Are the metrics supposed to show up under a BatchScan node? 
Is the reason why we're not seeing it because we're using the scala based connector spark-bigquery-with-dependencies_2.12-0.30.0.jar which are not build on Data Source API v2?
