### ISSUE TITLE
proxyAddress variable is not used if default application credentials method is used

### ISSUE THREAD

**Issue by milicevica23** [GoogleCloudDataproc/spark-bigquery-connector#1260]
Hi, i just want to ask if the proxyAddress variable is intentionally not used if the default application credentials is used? 

So in the  [line](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/4154060999f3e16358181cb26ea985870b49fc4a/bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryCredentialsSupplier.java#L83)  with default application credentials we don't provide the proxyAddress informatiom? In another [one](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/4154060999f3e16358181cb26ea985870b49fc4a/bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryCredentialsSupplier.java#L81C11-L81C36) where the credentialsFile is provided the proxy information is also there?

**Comment by isha97** [comment]
@milicevica23 We are using the `DefaultHttpTransportFactory` for `default application credentials`
Do you have any requirement to use proxyAddress information to create the HttpTransportFactory?

**Comment by milicevica23** [comment]
We want to use it behind the proxy and default credentials cant go through the proxy. So the variable which i provide is just ignored. In this case the default credentials is not possible to use 
Is therea way to to setup DefaultHttpTransportFactory to work with proxy?

**Comment by isha97** [comment]
Hi @milicevica23, can you please try adding the proxyAddress configs with this jar and let me know if it works
https://storage.googleapis.com/ishatarte-public/spark-3.5-bigquery-07302024-2114.jar

**Comment by isha97** [comment]
Hi @milicevica23,  please reopen the issue if you still need this feature.
