### ISSUE TITLE
"ClusteredFields" creation not supported in Direct write method from Pyspark to BigQuery

### ISSUE THREAD

**Issue by deena10545** [GoogleCloudDataproc/spark-bigquery-connector#1263]
Since auto table creation is possible from PySpark to BigQuery, when I write the DataFrame to BigQuery using the direct write method and the option "clusteredFields," the clustered fields are not being created. I didn't see any mention in the documentation about lack of support in the direct write method.

```
df.write.format("bigquery").mode("append").option("writeMethod", "direct") \
   .option("clusteredFields", "id") \
   .save("project_id.dataset_id.table_id")
```

The BigQuery table is created successfully, but the clustered fields are not created.

**Comment by isha97** [comment]
This issue is fixed and will be available in the next release.

**Comment by deena10545** [comment]
Thanks @isha97
