### ISSUE TITLE
Possible incompatibility with Spark v 2.11:2.3.1

### ISSUE THREAD

**Issue by ogrygorian-clgx** [GoogleCloudDataproc/spark-bigquery-connector#129]
Hi, we're using  Spark version 2.11:2.3.1 and we always have a different kind of exceptions, when trying to set GCP credentials with our service account.(that are related to some methods from Guava) What I see, that this spark version use guava version 11.02, and BigQuery connector use 28.02-android. 
Is actually a `spark-bigquery-connector` compatible with this version of Spark? And if it is, if you have any suggestions how to avoid `guava` versions incompatibility? And more Java examples, how to use the connector, set credentials etc?
Thank you in advance.

**Comment by davidrabinowitz** [comment]
If you use the latest versions of the connector (shaded or spark-bigquery-with-dependencies) you would get a repackaged version of guava which does not interfere with the Spark version. 

Also, as Spark in general has outdated dependencies (Spark, Jackson, etc) it is usually better to include a shaded versions of these in your application uber-jar.

Regarding setting the credentials, have you looked at the [How do I authenticate outside GCE / Dataproc?](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#how-do-i-authenticate-outside-gce--dataproc) section?
