### ISSUE TITLE
Setting a different client api endpoiint for Bigquery 

### ISSUE THREAD

**Issue by EmilioIppoliti** [GoogleCloudDataproc/spark-bigquery-connector#1296]
Hi all ,  

I created a provate endpoint for my  Google Bigquery instance , and  I wolud like to connect to this endpoint using  the spark-bigquery-connector in Python  . At the moment  it seems there isn't any possibility to set a different endpoit on the Spark options uding bigquery formart , Could you me suggest something to resolve this issue ? 

![image](https://github.com/user-attachments/assets/5e29f436-8692-4736-9758-82d0bd0e1212)

As illustrated in the previous image  , I was able to setup only the proxy but no private endpoint .

Thanks

**Comment by davidrabinowitz** [comment]
You can set the following options:
* `bigQueryHttpEndpoint` - the endpoint for the BigQuery V2 API REST endpoint.
* `bigQueryStorageGrpcEndpoint` - The endpoint for the Spark BigQuery Storage API, used to read and write the data (DIRECT write)

Any reason you need to do that?
