### ISSUE TITLE
[Glue 4.0 integration]

### ISSUE THREAD

**Issue by Repomano** [GoogleCloudDataproc/spark-bigquery-connector#1299]
Hi,

I want to report an issue with Spark 3.3 for Glue 4.0.

When I try to retrieve data from BigQuery using a connector, I get the error: "BigNumeric precision is too wide (76), Spark can only handle decimal types with a max precision of 38."

I noticed that this issue is mentioned in the README.md, but I don't see a way to create a mapping that allows me to map the BigQuery values correctly into a DataFrame.

How can I resolve this issue?

Thanks.

**Comment by isha97** [comment]
HI @Repomano, Please look at the configs `bigNumericDefaultPrecision` and `bigNumericDefaultScale` described in the Readme to set the Precision and scale of your Bigquery tables.
