### ISSUE TITLE
Metadata of the columns not available in a DataFrame

### ISSUE THREAD

**Issue by abraham-parusu** [GoogleCloudDataproc/spark-bigquery-connector#130]
Hi Team,

I am unable to retrieve metadata information of the Tables using spark-bigquery-connector. Below is the sample code I used to retrieve data.
**org.apache.spark.sql.Dataset<Row> r = sqlContext.read().format("bigquery")             .option("table","<projectid>.<dataset>.<tablename>").load();
dataFrame.schema().json()**

My requirement is to retrieve the description of the columns.

Please share if there is a way to achieve this.

Thanks,
Abraham.

**Comment by davidrabinowitz** [comment]
Which Spark version, Java version and connector version are you using? Here is what I got on with the latest connector (0.13.0-beta) on Spark 2.3.4/Java 1.8.0_232
```
scala> val df = spark.read.format("bigquery").option("table","bigquery-public-data.samples.wikipedia").load()
df: org.apache.spark.sql.DataFrame = [title: string, id: bigint ... 13 more fields]

scala> df.schema
res3: org.apache.spark.sql.types.StructType = StructType(StructField(title,StringType,false), StructField(id,LongType,true), StructField(language,StringType,false), StructField(wp_namespace,LongType,false), StructField(is_redirect,BooleanType,true), StructField(revision_id,LongType,true), StructField(contributor_ip,StringType,true), StructField(contributor_id,LongType,true), StructField(contributor_username,StringType,true), StructField(timestamp,LongType,false), StructField(is_minor,BooleanType,true), StructField(is_bot,BooleanType,true), StructField(reversion_id,LongType,true), StructField(comment,StringType,true), StructField(num_characters,LongType,false))

scala> df.schema.json
res4: String = {"type":"struct","fields":[{"name":"title","type":"string","nullable":false,"metadata":{}},{"name":"id","type":"long","nullable":true,"metadata":{}},{"name":"language","type":"string","nullable":false,"metadata":{}},{"name":"wp_namespace","type":"long","nullable":false,"metadata":{}},{"name":"is_redirect","type":"boolean","nullable":true,"metadata":{}},{"name":"revision_id","type":"long","nullable":true,"metadata":{}},{"name":"contributor_ip","type":"string","nullable":true,"metadata":{}},{"name":"contributor_id","type":"long","nullable":true,"metadata":{}},{"name":"contributor_username","type":"string","nullable":true,"metadata":{}},{"name":"timestamp","type":"long","nullable":false,"metadata":{}},{"name":"is_minor","type":"boolean","nullable":true,"metadata":{}},{"name"...
scala> 
```
Can you re-create on one of the public data tables?

**Comment by abraham-parusu** [comment]
Yes, @davidrabinowitz.

If you observe res4 in your comment, metadata is an empty object:
res4: String = {"type":"struct","fields":[{"name":"title","type":"string","nullable":false,"metadata":{}}]

I want to extract the comments/descriptions that the user provided for each of the columns. I am expecting that information in the metadata object.

Thanks,
Abraham.

**Comment by abraham-parusu** [comment]
@davidrabinowitz, Appreciate your help in solving this issue. It seems the code is in master now. When can we expect this change to be in _latest(gs://spark-lib/bigquery/spark-bigquery-latest.jar.) jar file?

Thanks,
Abraham.

**Comment by davidrabinowitz** [comment]
Probably within a few weeks, there are several other changes coming.
