### ISSUE TITLE
BQ session expired exception in 6 hours and our spark job gets failed.

### ISSUE THREAD

**Issue by shaikhmohdjaffer** [GoogleCloudDataproc/spark-bigquery-connector#1316]
We recently upgraded our spark dataproc version to 2.2 from 2.0. we are using spark-bigquery-connector-2.12: 0.34.0. After this update we are getting BQ session expired exception in 6 hours and our spark job gets failed.

_Caused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: FAILED_PRECONDITION: there was an error operating on 'projects/wmt-mp-papi-dataproc-stage/locations/us/sessions/CAISDGNRTGNER1ZXUGVzMhoCcHgaAnB5/streams/CAUaAnB4GgJweSgC': session expired at 2024-11-23T09:59:13+00:00
	at com.google.cloud.spark.bigquery.repackaged.io.grpc.Status.asRuntimeException(Status.java:537)_

**Comment by davidrabinowitz** [comment]
A BigQuery ReadSession is a resource with an expiration time of 6 hours, regardless of the connector version. Pending on your code, you may see better results by setting the connector to `spark-3.5-bigquery:0.41.0`, by adding `--metadata SPARK_BQ_CONNECTOR_URL=gs://spark-lib/bigquery/spark-3.5-bigquery-0.41.0.jar` to your cluster creation.

If it doesn't help, I would recommend to open a ticket via your account manager so we can research this.

**Comment by davidrabinowitz** [comment]
The 6 hour expiration time is set by the BigQuery Storage backend, and cannot be tuned from the client side.
