### ISSUE TITLE
Incompatibility with OL 1.24.0+

### ISSUE THREAD

**Issue by tnazarew** [GoogleCloudDataproc/spark-bigquery-connector#1317]
While running application with spark-3.5-bigquery-0.41.0 I got the following error: 
`java.util.ServiceConfigurationError: io.openlineage.client.transports.TransportBuilder: Provider io.openlineage.client.transports.KinesisTransportBuilder not found` 
event though I didn't configure OL to use `KinesisTransport`

after some digging it turned out that `META-INF/services/io.openlineage.client.transports.TransportBuilder` was left in `spark-extension-interfaces` artifact version `1.19.0`. In OL version `1.24.0` the `KinesisTransport` was removed from the list of transports so spark bq connector is incompatible with newer versions of OL. The file is removed from the `spark-extension-interfaces` in newly released `1.25.0`, so bumping the OL version in connector dependencies should fix the issue.

**Comment by davidrabinowitz** [comment]
Will be fixed in version 0.42.0

**Comment by codelixir** [comment]
Hi @davidrabinowitz @ddebowczyk92,  

Does this mean connector version 0.42.x is not backwards compatible with older (pre-1.24.0) versions of OpenLineage?
