### ISSUE TITLE
DYNAMIC partitionOverwriteMode doesn't work with Integer Partitioned Tables having Partition Filter = Required 

### ISSUE THREAD

**Issue by walmaaoui** [GoogleCloudDataproc/spark-bigquery-connector#1321]
Hello,

Trying to write to a Partitioned Tables having `Partition Filter = `Required` when activating  `partitionOverwriteMode = DYNAMIC` resulted to 

```

Cannot query over table 'untienots.it_test.partitioned_by_campaign_dummy__data_model__20241128_092801' without a filter over column(s) 'campaign_id2' that can be used for partition elimination

```

Seeing the generated Query, I don't see filters on the partitioning column
```
MERGE
  `it_test.partitioned_by_campaign` AS TARGET
USING
  (
  SELECT
    *
  FROM
    `it_test.partitioned_by_campaign_092801761668294739208`
  CROSS JOIN
    UNNEST([TRUE, FALSE]) _1234567890123456789) AS SOURCE
ON
  IFNULL(
  IF
    (source.campaign_id2 >= 10000, 0, RANGE_BUCKET(source.campaign_id2, GENERATE_ARRAY(0, 10000, 1))), -1) = IFNULL(
  IF
    (target.campaign_id2 >= 10000, 0, RANGE_BUCKET(target.campaign_id2, GENERATE_ARRAY(0, 10000, 1))), -1)
  AND _1234567890123456789
  WHEN MATCHED THEN DELETE
  WHEN NOT MATCHED
  AND NOT _1234567890123456789 THEN
INSERT
  (`campaign_id2`,
    `bar`)
VALUES
  (`campaign_id2`,`bar`)

```

The same thing in the code, the integer partitioned query seems missing a step like the one for dates partitioned table `DECLARE partitions_to_delete DEFAULT....`

**Comment by isha97** [comment]
This is fixed and will be available in the next release. You can use this jar meanwhile which has the fix : gs://spark-lib-nightly-snapshots/spark-bigquery-metrics-nightly-snapshot.jar

**Comment by isha97** [comment]
This is being fixed as part of https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/1326 and would be available in the next release.
