### ISSUE TITLE
Intermediate formats

### ISSUE THREAD

**Issue by dmitrybugakov** [GoogleCloudDataproc/spark-bigquery-connector#133]
Hi colleagues!
Do you have any plans to add Avro as intermediate format?
Thank you

**Comment by kmjung** [comment]
I’m not sure that I understand your question here. The connector currently
uses the BigQuery Storage API, and reads data as blocks of serialized Avro
rows. Are you asking if there are plans to support exporting data from
BigQuery as Avro files, and subsequently reading from Google Cloud Storage?

**Comment by dmitrybugakov** [comment]
I'm asking about "intermediateFormat".
It's an option for writer.
Connector has [limitations](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/connector/src/main/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptions.scala#L78) for temporary files.

**Comment by kmjung** [comment]
I see. I can't speak to this at the moment; @davidrabinowitz is out of the office this week, but may be able to weigh in once he's back.

**Comment by digger** [comment]
@davidrabinowitz , why does the connector restrict the intermediate file formats to parquet and ORC? 

As I understand, the connector itself doesn't do anything with the intermediate files, it just allos Spark to write the files and the passes the format name to the BQ load job. BQ load jobs support more formats than these 2, e.g. avro and json are supported.

**Comment by kmjung** [comment]
@digger @dmitrybugakov: for my understanding, can you clarify why you're interested in Avro support specifically? Is there a functional or performance gap of some kind?

**Comment by digger** [comment]
@kmjung we were intending to use Avro as it's the recommended format per the BQ docs. See "Avro is the preferred format for loading data into BigQuery" at https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro. We did not do any testing comparing formats. Most likely we'll be fine with parquet or orc but I'm still curious about the reason for the restriction.

**Comment by kmjung** [comment]
Thanks for clarifying. I don't want to speak for David here; let's see what he has to say next week.

**Comment by davidrabinowitz** [comment]
It was mainly done out of support and performance reasons - for example Avro is not a built in format in Spark.

However there is no reason not to add those, and they will be added in the upcoming days once the tests are complete.

**Comment by dmitrybugakov** [comment]
@davidrabinowitz Thank you
