### ISSUE TITLE
Avoid list.element when writing to BigQuery

### ISSUE THREAD

**Issue by zaroursamy** [GoogleCloudDataproc/spark-bigquery-connector#135]
Hi,

I have a deep structure of my data, like this (but with more nested fields):
```scala
case class Person(name: String, friends: Seq[Friend])
case class Friend(age: Int, links: Seq[Link])
case class Link(uri: String)
```

So I have a `Dataset[Person]` I want to write in BigQuery, but in the schema I have lot of useless fields **list.element** that pollute the schema: something like **friends.list.element.links.list.element**

Because of this, I have this error: 

> It has definition level 16 while maximum allowed definition level is 15.

How can we avoid these list.element fields ?

**Comment by zaroursamy** [comment]
This append only when Parquet format is used for writing.
I avoided this **list.elements** level by using ORC format : `.option("intermediateFormat", "orc").
I think using Avro format will also be OK: the problem is just with Parquet.
`

**Comment by davidrabinowitz** [comment]
Thanks @zaroursamy , that's a great input. We are working now on the schema write and adding more intermediate formats.

**Comment by Gaurangi94** [comment]
We have added Avro as an intermediate format.
