### ISSUE TITLE
Wildcard Tables Are Not Supported

### ISSUE THREAD

**Issue by chrisbeckett8** [GoogleCloudDataproc/spark-bigquery-connector#139]
Hey, I was wondering what is a good workaround to the "wildcard tables are not supported?" Meaning, I am trying to call project.table.subtable_* in the spark.read.format. Do you guys happen to have any ideas for what I could do to call all the ~600 tables at once? Or do I have to do it separate? 

a = spark.read.format("bigquery") \
.option('table',table.subtable_*') \
.option('project', 'project') \
.option('parentProject', 'project') \
.option('credentialsFile','credentials.json') \
.load()

Thanks for the help,
Chris

**Comment by kmjung** [comment]
At a high level, I imagine the BigQuery team's guidance would be "move to a partitioned table" assuming such a thing make sense for your use case -- wildcard tables have issues with schema divergence over time, and partitioned tables are frequently a better option.

With that said --what's your use case? We might be able to recommend some short-term fixes which are less drastic.

**Comment by chrisbeckett8** [comment]
Thanks for the quick reply. It is the ga_sessions raw data, with separate tables by day. I am trying to do some aggregation in preparation for modeling on the whole data set.

**Comment by kmjung** [comment]
I see -- I don't know that either the Spark connector or the storage API provides an easy way to do this, or has plans to do so in our roadmap at the moment. Could you use BigQuery (which does support wildcard tables as far as I know) to do the aggregation, and then pull the data into a dataframe from there?

I'll look into why the GA data isn't partitioned.

**Comment by chrisbeckett8** [comment]
Would I have to create a new table in BigQuery, or is there a function call for .option('query') in the spark big query connector?

**Comment by kmjung** [comment]
@davidrabinowitz do you know if there's such an option in the connector?

At worst, you can execute a query and write the results to a named table, and then read the data from there (as per https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/examples/python/query_results.py).

**Comment by davidrabinowitz** [comment]
An `.option("query","...")` is on our roadmap, but without concrete release date yet. Your two options are:

1. Use the BigQuery API directly, creating a query with and specifying a destination table for it, use spark to read the table using `spark.read.format("bigquery")...`. Don't forget to delete the table once you're done.
2. If you can - create a view with your query, and then use the connector's [view support](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#reading-from-views) to read the data.

**Comment by chrisbeckett8** [comment]
That makes sense. These are good workarounds, thanks. Question, @davidrabinowitz what is the purpose of deleting the table once I am done?

**Comment by davidrabinowitz** [comment]
I assume your wildcard change from time to time - for example, "last 60 days" means different dates based on the day of the query. Therefore you don't want the aggregate table to remain, creating a new "last 60 days" table every day. Of course, if you do have a use for keeping the data in this form, then go ahead and keep it.

**Comment by chrisbeckett8** [comment]
Ah I see. That makes sense. Thanks for the explanation.
