### ISSUE TITLE
A project ID is required

### ISSUE THREAD

**Issue by morganvill** [GoogleCloudDataproc/spark-bigquery-connector#161]
Hi,

I try to use the spark connector on my Apache Spark cluster with Scala but can't because of the following error: java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.

Here my code

```
import org.apache.spark.sql.SparkSession
import com.google.cloud.spark.bigquery._

val spark = SparkSession.builder
  .getOrCreate()

spark.conf.set("credentialsFile", "my.json")

spark.read.bigquery("project_id.datasets.tablel")
```

I installed spark_bigquery_latest.jar on the cluster and even try the global environment variable option but nothing works.

**Comment by davidrabinowitz** [comment]
Hi @morganvill 

Is the credential file a personal one or a service account?  Personal credentials files do not contain the project id. You can either set the parent project id in the code in the read option: §spark.read.format("bigquery").option("parentProject", "<your-gcp-project-id>").option("table", "project_id.datasets.tablel").load()`; Alternatively you can set the `GOOGLE_CLOUD_PROJECT` environment variable, pointing to your project id.

**Comment by morganvill** [comment]
Hi @davidrabinowitz 

It's a service account. I tried to set the option and global environment variable but when I do, it says that he doesn't found my .json even though i have it available where i point it.

**Comment by davidrabinowitz** [comment]
Can the spark process read the JSON? Does it have read permissions?
Also - is it a single node cluster or is it a larger cluster? If the latter, do all the members of the cluster have the JSON file in the same path? Notice that a spark driver does not run on the YARN cluster master, but on one of the slaves.

**Comment by morganvill** [comment]
Ok i resolved the problem and gave permission, sorry that was a bad question but big thanks.

**Comment by davidrabinowitz** [comment]
Glad I could help :-)

**Comment by Paulito123** [comment]
Adding the option .option("parentProject", "<your-gcp-project-id>") did the trick for me. Thanks for the help!

**Comment by denouncein** [comment]
> Adding the option .option("parentProject", "") did the trick for me. Thanks for the help!

This worked for me too! thanks!
