### ISSUE TITLE
BigQuery error was Incompatible table partitioning specification.

### ISSUE THREAD

**Issue by B4XTER** [GoogleCloudDataproc/spark-bigquery-connector#164]
The exact error that I am getting is  
```
Expects partitioning specification interval(type:day,field:ordermonth) clustering(businesssector,soid,orderdate), but input partitioning specification is interval(type:day,field:ordermonth) clustering(['businesssector', 'soid', 'orderdate'])
```
and I can't figure out how I could input the clustering fields any better way.
My current way of doing it is by extracting the clustering fields and putting them into a list I named cluster_list, which I then reference in the code I use to write to bigquery:

```
df_sql_result.write.format("bigquery") \
  .option('table', action_target) \
  .option('partitionField', partition) \
  .option('clusteredFields', cluster_list) \
  .mode('overwrite') \
  .save() 
```
The README says that I should be using a comma separated list of the columns, but since I am doing that here, I don't know what else I could do to fix it.

**Comment by davidrabinowitz** [comment]
Hi @B4XTER ,

The options expects either strings, numeric or boolean types, but not complex types such as list. What you can see is the result of converting the list into string. Please try the following:
```
df_sql_result.write.format("bigquery") \
  .option('table', action_target) \
  .option('partitionField', 'ordermonth') \
  .option('clusteredFields', 'businesssector,soid,orderdate') \
  .mode('overwrite') \
  .save() 
```

**Comment by B4XTER** [comment]
That worked, thanks a ton!
