### ISSUE TITLE
Authentification Fail

### ISSUE THREAD

**Issue by alexisgaziello** [GoogleCloudDataproc/spark-bigquery-connector#167]
I have been trying to authenticate this service without luck for days know. I have tried to follow the instructions and I just don't know what else to do. 

When trying to do a query I get this error:
`u'A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.`

I successfully downloaded the .jar file and launched pyspark with:

`pyspark --jars spark-bigquery-latest.jar`

After I called: 

`spark.conf.set("credentialsFile", "/home/hadoop/credential.json")`

also
`spark.conf.set("credentialsFile", "./credential.json")`

also:

```
credential = """{
  "type": "service_account",
  "project_id": "XXXXXXX-XXXXXXX",
  "private_key_id": "XXXXXXX",
  "private_key": "-----BEGIN PRIVATE KEY-----XXXXXXX\n-----END PRIVATE KEY-----\n",
  "client_email": "XXXXXXX-XXXXXXX@XXXXXXX-XXXXXXX.iam.gserviceaccount.com",
  "client_id": "XXXXXXX",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/XXXXXXX.iam.gserviceaccount.com"
}"""
import base64
credential_encoded = base64.b64encode(credential)
spark.conf.set("credentials", credential_encoded)
```

But nothing works.
What am I doing wrong?

I am running pyspark on an EMR in AWS.

**Comment by davidrabinowitz** [comment]
Hi @alexisgaziello Have you downloaded the jar and the credentials file to all the members of the EMR cluster? Please note that the spark driver run on one of the cluster's worker nodes, not on the master. Therefore, if you have the connector jar and the credentials file only on the master it wouldn't work. I would suggest in this case to have the credentials files installed using a bootstrap action, and refer to the jar using the `--packages` parameter, see more [here](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#downloading-and-using-the-connector)

**Comment by alexisgaziello** [comment]
Hello @davidrabinowitz. Thank you for your response. No luck. 

I tried launching pyspark as suggested with: 
`pyspark --packages com.google.cloud.spark:spark-bigquery-with-dependencies_2.11:0.15.1-beta`

and to avoid adding the credential file to all nodes, I used the base64 string which I copy pasted into the interpreter. Still the same error message.

**Comment by davidrabinowitz** [comment]
Please add the following option when trying to read the table:
```
.option('parentProject', '<YOUR-GCP-PROJECT>')
```

**Comment by alexisgaziello** [comment]
@davidrabinowitz 
Nice! Finally some update :)

When I use the credential key encoded in base64 as shown in the first message I get this new error:

```
File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o200.load.
: com.google.cloud.spark.bigquery.repackaged.com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
```

Apparently this is due to the fact that there is '\n' character in the key which have to be escaped. I would suggest to maybe add this to the parser or the instructions, since it will probably happen to all the people that try to encode the json key.

Anyway, another error appears:

`Caused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: PERMISSION_DENIED: request failed: the user does not have 'bigquery.readsessions.create' permission for 'projects/bigdatatech-275900'`

This probably has nothing to do with the connector but if you have any suggestions I would be grateful.

The account I am authenticating the service with has the predefined role "BigQuery Admin", that has 74 permissions including: bigquery.readsessions.create, so I'm lost again.

By the way, I can load the credentials from the original source file as
`spark.conf.set("credentialsFile", "/home/hadoop/key.json")`
and it will work too (up until the error I just described), even if the file is just in the node.

**Comment by davidrabinowitz** [comment]
Please go to the IAM console in the Google cloud console and verify the roles of your service account. If you see the `bigquery.readsessions.*` roles missing, you can add the `BigQuery Read Session User` role to your account

**Comment by alexisgaziello** [comment]
I am supposed to already have the `bigquery.readsessions.*` roles with `BigQuery Admin`. Anyway I added the role you suggested:

![image](https://user-images.githubusercontent.com/29357459/81019025-57714380-8e2b-11ea-99b0-e6c7216a6979.png)

But same problem.

**Comment by davidrabinowitz** [comment]
Can you please install the [gcloud CLI](https://cloud.google.com/sdk/docs/downloads-versioned-archives), and use this credentials file with the `bq` utility? I want to verify of the error is from this service account or something else

**Comment by alexisgaziello** [comment]
Indeed I end up getting the same error. Anyway using these tools is a pain, I will use something else. Thanks for the help anyway.

**Comment by davidrabinowitz** [comment]
Hi @alexisgaziello I'm sorry this is your experience, it seems that your project or service account are not configured properly. Have you asked for support from GCP?
