### ISSUE TITLE
are there any libraries for executing apriori algorithm in PySpark?

### ISSUE THREAD

**Issue by TracyWest** [GoogleCloudDataproc/spark-bigquery-connector#179]
Can we use Python library within PySpark or are there any other library which can provide a function for apriori in PySpark?

**Comment by davidrabinowitz** [comment]
You are welcome to use any function provided by the [PySpark API](http://spark.apache.org/docs/2.4.5/api/python/). Using [Dataproc](https://cloud.google.com/dataproc), you can add the [Anaconda optional component](https://cloud.google.com/dataproc/docs/concepts/components/anaconda), giving you access to all the algorithms provided by [Anaconda](https://www.anaconda.com/products/individual).

Are there any PySpark / BigQuery specific questions?
