### ISSUE TITLE
Query/Job Visibility

### ISSUE THREAD

**Issue by whittid4** [GoogleCloudDataproc/spark-bigquery-connector#188]
Is there any visibility of the jobs that have been executed against BigQuery?

I am running the spark connector in a standalone application, i.e not in Dataproc and would like to be able to check the magnitude of queries/jobs being executed against BigQuery. I have check the "Job History" and "Query History" but cannot see anything being executed. I can see metrics are available in the [Storage API metrics](https://console.cloud.google.com/apis/api/bigquerystorage.googleapis.com/metrics) UI, but cannot get a feel for how much data is being processed.

**Comment by davidrabinowitz** [comment]
Please check the "Project History" in the BigQuery console. Also, you can add the `traceApplicationName` and `traceJobId` to better identify the jobs, as well as set job labels using the `bigQueryJobLabel` option.
