### ISSUE TITLE
The 0.15.1-beta version fails with "java.lang.NoClassDefFoundError: org/apache/spark/sql/vectorized/ColumnVector"

### ISSUE THREAD

**Issue by mmarina7** [GoogleCloudDataproc/spark-bigquery-connector#189]
Following the fix of this issue: https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/187

and using the `gs://spark-lib/bigquery/spark-bigquery-latest.jar` 

the failure now encountered is `java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/apache/spark/sql/vectorized/ColumnVector`. 

For the code `spark.read.format("bigquery").option("table", "project.dataset.tablename").load()` the connector reads basic metadata, but fails on computing or materializing.

**Comment by mmarina7** [comment]
Stack trace:

`Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/apache/spark/sql/vectorized/ColumnVector
	at com.google.cloud.spark.bigquery.ArrowBinaryIterator.toArrowRows(ArrowBinaryIterator.java:79)
	at com.google.cloud.spark.bigquery.ArrowBinaryIterator.hasNext(ArrowBinaryIterator.java:66)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)`

**Comment by Gaurangi94** [comment]
I am not able to repro this error. Could you share more details on your environment setup and how you are executing the spark query?

**Comment by klorand** [comment]
We've tried in Google Cloud DataProc, with Spark 2.4.4 and it worked without issues.  

When tried with on premise Hadoop with Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112) and Spark 2.1 and Spark 2.2 had the same NoClassDefFoundError as reported. 

We will still try to run this with Spark 2.4.x to see if it is a Spark versioning problem. 

The previous (before the beginning of June) "latest" version was actually working with these Spark versions.

**Comment by klorand** [comment]
After checking the code of Apache Spark versions it looks like that class (org.apache.spark.sql.vectorized.ColumnVector) was introduced in the 2.3 version. So it seems the connector has a hard compatibility requirement of Spark 2.3 or higher.

**Comment by davidrabinowitz** [comment]
Which spark version are you using?

**Comment by davidrabinowitz** [comment]
Please re-open if supporting spark 2.2 and below is still an issue.

**Comment by karantirthani** [comment]
Hi @davidrabinowitz 
I am facing the same issue with spark 2.2
Is there a way to handle it ?

> Please re-open if supporting spark 2.2 and below is still an issue.

**Comment by davidrabinowitz** [comment]
Please set the `readDataFormat` to AVRO
