### ISSUE TITLE
Metadata of the Spark columns not available in BigQuery Table

### ISSUE THREAD

**Issue by AmineSagaama** [GoogleCloudDataproc/spark-bigquery-connector#190]
Hi,

I'm unable to retrieve the description of each column from the BigQuery Table, 
when I sink a Dataframe to Bigquery.
I set the spark column metadata like this : 
```
StructField(
      name = fieldName,
      dataType = primitiveType.sparkType,
      nullable = nullable,
      metadata = Metadata.fromJson("{\"description\": \"" + description.getOrElse("") + "\"}")
    ).withComment(description.getOrElse(""))
```
But when I sink the Dataframe to BigQuery, the description column is Empty.
I think this issue is related to #130, just the opposite path is missing .

Spark Version : 2.4.5
Connector Version : 0.16.1

**Comment by stettix** [comment]
I'm seeing this too in connector version 0.18.0. Is there any update on this?

**Comment by bskim45** [comment]
Why don't we use builtin `comment` instead of `description`? or providing both if necessary?

**Comment by dylanwilder** [comment]
Any update on this?

**Comment by davidrabinowitz** [comment]
PR #353 has been approved and will be merged soon into master
