### ISSUE TITLE
Auto refreshing Access token

### ISSUE THREAD

**Issue by mayurdb** [GoogleCloudDataproc/spark-bigquery-connector#194]
As a part of this [change](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/146) we have added support for access token-based authorization.

But considering the Access token has a short expiry (50 mins from generation), this becomes an issue with the long-running applications and the users have to generate access token immediately before running the command (so that the token is valid for a min of 50mins). We should add the functionality of auto-refreshing the access token when required parameters are passed (refresh token, client ID & client secret..)

Currently, on access token expiry, spark applications fail with:
```com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: java.lang.IllegalStateException: OAuth2Credentials instance does not support refreshing the access token. An instance with a new access token should be used, or a derived type that supports refreshing.```

Can we add support for refreshing the token in the Authorization library used by the connector itself? Doing this in the connector will not be very straightforward considering access tokens shared with the live executors also has to be refreshed.

For adding it in the executor I was thinking something on the lines of -
- User passes the refresh token, client ID, and client secret to Spark along with the access token if she wants to auto-refresh the access token.
- When the BigQueryRelation gets created, on the driver, generate the access token if not already available.
- Broadcast the generated access token so that each executor has access to it.
- Run a daemon thread on the driver which asynchronously refreshes the access token before the expiry so that each executor always has the valid access token. Spark Broadcast does not support updating the values, so this will require some brainstorming.

**Comment by davidrabinowitz** [comment]
Assuming you have the client ID, client secret and refresh token, you can create a UserCredentials and pass them to the connector in the following manner:
```
val json = new GenericJson();
json.setFactory(JacksonFactory.getDefaultInstance());
json.put("client_id", clientId);
json.put("client_secret", clientSecret);
json.put("refresh_token", refreshToken);
json.put("type", "authorized_user");
val credentialsKey = Base64.getEncoder().encodeToString(json.toPrettyString().getBytes(StandardCharsets.UTF_8));

val df = spark.read.format("bigquery")
                 .option("credentialsKey", credentialsKey)
                 .load(....)
```
UserCredentials auto-refresh the token if needed on requests.

**Comment by ParitoshChaudhary2810** [comment]
Hey guys, any updates on this ? I'm looking for a solution to support OAuth while extracting the data from google bigquery using spark. Since there is no support for refreshing the token yet is there a workaround for refreshing the tokens ? Any leads would be really helpful.

**Comment by davidrabinowitz** [comment]
@ParitoshChaudhary2810 AccessToken cannot be refreshed on its own, however you can create your own [implementation of   `AccessTokenProvider`](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#how-do-i-authenticate-outside-gce--dataproc) and it will be called on token refresh.

**Comment by CrashLaker** [comment]
hi @davidrabinowitz,

sorry to bother in this thread.
do you know if there's the same implementation for AWS expired temporary access tokens?

regards,c.
