### ISSUE TITLE
Keep GCS data after import

### ISSUE THREAD

**Issue by leoneuwald** [GoogleCloudDataproc/spark-bigquery-connector#195]
Hi,

I would like do make import to BQ and keep the data in GCS. 

I read the code a I don't found a way to do this.

Can I contribute with this feature?

Tks

**Comment by davidrabinowitz** [comment]
Hi, @leoneuwald 

Of course! we would love to have contributions. Feel free to add a configuration flag so that the intermediate data will be kept on GCS.  Please notice the intermediate data is kept in a temporary location, which at the moment is not exposed to driver code.
