### ISSUE TITLE
[FEATURE] - Issuing a query in a dry run mode

### ISSUE THREAD

**Issue by AmineSagaama** [GoogleCloudDataproc/spark-bigquery-connector#215]
I think, it's a good idea to estimate the cost of querying a Table in dry_run mode, to estimate in advance the cost of the query.
Actually, we can't add a dry_run option when reading a Table into a Dataframe :

```
df = spark.read
  .format("bigquery")
  .load("bigquery-public-data.samples.shakespeare")
```
As a proposal, we can add a dry_run option when reading a Table into a Dataframe, to estimate the number of bytes read by the query, therefore we are not charged for performing the dry run : 

```
df = spark.read
  .format("bigquery")
  .option("dryRun", "true")
  .load("bigquery-public-data.samples.shakespeare")
```

@davidrabinowitz What do you think ?
Thanks.

**Comment by davidrabinowitz** [comment]
Please note that just creating a DataFrame (like in your first code sample) has no cost other than getting the table's metadata. Only when an action like `.show()` or `.write` occurs then the data is actually read.

**Comment by AmineSagaama** [comment]
Hi @davidrabinowitz, thank you for your reply. Indeed, reading a Dataframe is a transformation, and is therefore a lazy operation.
The idea behind this, is to perform a dry run of loading a BigQuery Table into a spark Dataframe.
For example, if we have this code : 
```
spark.read
  .format("bigquery")
  .option("dryRun", "true")
  .load("bigquery-public-data.samples.shakespeare")
  .createOrReplaceTempView("dfTable")
session.sql("""SELECT * FROM dfTable""")
```
We will have in return, something to tell us, the cost of loading the Table, like **total_bytes_processed** (https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults).
So, we will have the possibility, to estimate the total bytes processed, after loading the Table into a Dataframe.
BigQuery client already offers this feature : 
https://cloud.google.com/bigquery/docs/dry-run-queries
I think, it's a good idea to have the same thing in spark-bigquery-connector.

**Comment by davidrabinowitz** [comment]
I understand we can get the total processed bytes estimation, have you thought of a way to return this value to the user? The DataFrame API does not help us here.

**Comment by zwelshman** [comment]
Hello, I see this issue is not closed @AmineSagaama where you able to make any progress with this feature? I too am looking for something similar, but for spark-sql
