### ISSUE TITLE
Unable to save data on bigquery using hourly partition.

### ISSUE THREAD

**Issue by OatmealLick** [GoogleCloudDataproc/spark-bigquery-connector#226]
BigQuery supports now hourly partitioning. In your library there already is an enum with Type.HOUR but is not being supported. When I'm trying to save hourly partition with partition format set with
`.option("datePartition", "2020080212")`
I end up with date validation/formatting Exception.

Would you provide a way to save data using BigQuery hourly partitions?

**Comment by OatmealLick** [comment]
Hi, are there any plans for this feature? Do you have roadmap for this project? I'd like to be able to somewhat estimate is it up for use :)

**Comment by davidrabinowitz** [comment]
I'm actively working on it, should be released soon

**Comment by davidrabinowitz** [comment]
Fixed by PR #267
