### ISSUE TITLE
Unable to specify a schema for output table

### ISSUE THREAD

**Issue by SevakAvet** [GoogleCloudDataproc/spark-bigquery-connector#234]
As far as I understand there's no way to specify a schema for an output table.
So there's a json file with a BQ table schema definition:

```json
{
  "fields": [
    {
      "mode": "NULLABLE",
      "name": "name",
      "type": "STRING"
    },
    {
      "mode": "REPEATED",
      "name": "categories",
      "type": "STRING"
    },
    {
      "mode": "NULLABLE",
      "name": "title",
      "type": "STRING"
    },
...
}
```

How I write data to BQ:
```java
products.write()
  .mode("overwrite")
  .format("bigquery")
  .option("table", tableName)
  .save();
```

So I want to pass this schema as an option (let's say 'schema_json', value would be plain json as in example above). I'd be glad to contribute if somebody points to the place where this can be done.

Right now, in order to achieve this I have to use `com.google.cloud.bigdataoss` and `result.saveAsNewAPIHadoopDataset(hdConf)` with appropriate config (this is where I can define schema), which seems ugly for just writing data to BQ.

**Comment by davidrabinowitz** [comment]
@SevakAvet Can I ask why do you need to pass a custom schema? The BigQuery schema is derived from the DataFrame's schema. I have seen the fix, and I'm afraid it may collide with upcoming changes to the connector.

**Comment by SevakAvet** [comment]
@davidrabinowitz sure, there're two things, we have an output table with a huge number of columns and for some of them 
 inferred data type is incorrect and downstream pipeline fails because of that, easy fix would be to just pass schema explicitly. The other thing is minor, but still, you can specify columns order if schema is explicitly defined. Anyways, I'd just love to get rid of boilerplate code that we currently have, instead of simple write like:
```
        validProducts
                .write()
                .option("temporaryGcsBucket", jobContext.getStageDataBucket())
                .option("bqSchema", jobContext.getProductTableSchema())
                .format("bigquery")
                .mode(SaveMode.Overwrite)
                .save(jobContext.getOutputTableId());
```

we have this:

```
private static <T> void writeResultsToBigTable(JavaPairRDD<String, T> result, JavaSparkContext sparkContext,
                                                   String tableId, String tableSchema, String stageDataBucket) {
        try {
            Configuration hdConf = configureOutput(sparkContext, tableId, tableSchema, stageDataBucket);
            result.saveAsNewAPIHadoopDataset(hdConf);
        } catch (IOException e) {
            throw new RuntimeException("Unable to configure connection with BigQuery", e);
        }
    }

    private static Configuration configureOutput(JavaSparkContext sparkContext, String tableId, String tableSchema,
                                                 String stageDataBucket) throws IOException {
        String[] projectNameToTableName = tableId.split(":");

        Configuration hdConf = sparkContext.hadoopConfiguration();
        hdConf.set(BigQueryConfiguration.PROJECT_ID_KEY, projectNameToTableName[0]);
        hdConf.set(BigQueryConfiguration.GCS_BUCKET_KEY, stageDataBucket);

        String tmpDir = "gs://" + stageDataBucket + "/tmp/" + tableId + "/" + System.currentTimeMillis();
        if (tableSchema != null) {
            BigQueryOutputConfiguration.configure(hdConf, tableId, tableSchema, tmpDir,
                    BigQueryFileFormat.NEWLINE_DELIMITED_JSON,
                    TextOutputFormat.class);

        } else {
            BigQueryOutputConfiguration.configureWithAutoSchema(
                    hdConf,
                    tableId,
                    tmpDir,
                    BigQueryFileFormat.NEWLINE_DELIMITED_JSON,
                    TextOutputFormat.class);
        }
        hdConf.set(BigQueryConfiguration.DELETE_EXPORT_FILES_FROM_GCS_KEY, "true");

        hdConf.set(BigQueryConfiguration.OUTPUT_TABLE_WRITE_DISPOSITION_KEY, "WRITE_TRUNCATE");
        hdConf.set("mapreduce.job.outputformat.class", IndirectBigQueryOutputFormat.class.getName());
        return hdConf;
    }
```

**Comment by davidrabinowitz** [comment]
That's totally understandable. I'd be happy to get more details about the data types that has an incorrect inference. As this shouldn't happen I'd like to fix those first.

**Comment by SevakAvet** [comment]
Thanks! I'll try to reproduce that and attach more info here

**Comment by davidrabinowitz** [comment]
Hi @SevakAvet , are there any updates?

**Comment by SevakAvet** [comment]
@davidrabinowitz hey, no luck so far, I'm not working on that project anymore, asked guys to help & reproduce the incorrect inference issue. Anyways, I think we can close this issue, I'd open another with with more details.

**Comment by davidrabinowitz** [comment]
Ok, please feel free to re-open if you have additional data. I'll close the PR as well.
