### ISSUE TITLE
Writes for Dataframes with more than 10000 partitions fail

### ISSUE THREAD

**Issue by davidrabinowitz** [GoogleCloudDataproc/spark-bigquery-connector#248]
When trying to write dataframes with more than 10000 partitions the load job fails with a  "Too many sources provided: XXXX. Limit is 10000" error. This should be fixed with a better URI provided to the load job.

**Comment by anton-statutov-booking** [comment]
Hello, I just stumbled upon on this problem. Do you know a good workaround?

**Comment by davidrabinowitz** [comment]
Fixed in version 0.18.1

**Comment by anton-statutov-booking** [comment]
Thanks. I've tested it - the fix works.

**Comment by asiunov** [comment]
This solution in https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/295 may not work in all cases, e.g. when there are many skipped partitions (because *usually* spark doesn't write empty parts). The easiest workaround is to do `df.coalesce(10000).write...`.

**Comment by yeshvantbhavnasi** [comment]
Even I see the error popping on with latest version of bigquery-connector
