### ISSUE TITLE
Array types in spark are written incorrectly

### ISSUE THREAD

**Issue by sa-** [GoogleCloudDataproc/spark-bigquery-connector#253]
Connector creates addition nested struct "list" when writing array types

This is an excerpt from my print Schema statement:
```
 |-- clicks: array (nullable = true)
 |    |-- element: struct (containsNull = false)
 |    |    |-- vendor_code: string (nullable = true)
 |    |    |-- click_count: long (nullable = false)
```

And when I use `df.write.format("bigquery").save("dest")`, this is what I see in BQ
![image](https://user-images.githubusercontent.com/1297369/95476900-11934b00-0988-11eb-9853-84df477f09b3.png)
As you can see `clicks` in my schema is an array of struct with no element called `list` but this connector creates one anyway. Writing to JSON and loading from GCS is a better solution for now, if anyone else reading this is facing the same issue

**Comment by davidrabinowitz** [comment]
Please see issue #251
