### ISSUE TITLE
UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available

### ISSUE THREAD

**Issue by sa-** [GoogleCloudDataproc/spark-bigquery-connector#256]
Getting this error

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 0.0 failed 1 times, most recent failure: Lost task 2.0 in stage 0.0 (TID 2, xxxx, executor driver): java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available
	at com.google.cloud.spark.bigquery.repackaged.io.netty.util.internal.PlatformDependent.directBuffer(PlatformDependent.java:490)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.buffer.NettyArrowBuf.getDirectBuffer(NettyArrowBuf.java:257)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.buffer.NettyArrowBuf.nioBuffer(NettyArrowBuf.java:247)
	at com.google.cloud.spark.bigquery.repackaged.io.netty.buffer.ArrowBuf.nioBuffer(ArrowBuf.java:248)
...
```

When trying to run 
```
val data = spark.read
    .format("bigquery")
    .load("...")
    .cache

data.count
```

Context:
Using adopt open jdk 11
Scala 2.12
Spark 3.0.1
spylon kernel with this as my init conf
```
%%init_spark
import psutil

launcher.packages = [
    "com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.17.3", 
    "org.apache.lucene:lucene-suggest:8.6.2",
    "org.apache.lucene:lucene-queryparser:8.6.2",
    "org.apache.lucene:lucene-analyzers-icu:8.6.2"
]
launcher.conf.set("spark.driver.memory", f"{int(psutil.virtual_memory().total / 1024**3 * 0.9 - 2)}g")
```

**Comment by sa-** [comment]
I should add that I was able to fix this by downgrading my JDK to 8 but it would be nice if I didn't have to do that

**Comment by davidrabinowitz** [comment]
Unless you are using Java 11 specific APIs, you can compile with Java 8 and run it on Java 11. We haven't adapted the connector to be compiled with Java 11 (but it's on the roadmap). Another option - bring the connector in runtime by adding it to the `spark.jars` or `spark.jars.packages`.

**Comment by michTalebzadeh** [comment]
Hi David,

Has this issue with Java 11 and Java 8 been resolved please as I am having the same issue reading from GBQ table. Writes are OK. I am doing it through GKE cluster with 3.1.1 docker image and Debian buster which is on Java 11.

Thanks

**Comment by michTalebzadeh** [comment]
Just to add on prem I use JAVA 8 and has no problem reading and writing to GBQ.

Also can you clarify below please

"Unless you are using Java 11 specific APIs, you can compile with Java 8 and run it on Java 11. We haven't adapted the connector to be compiled with Java 11 (but it's on the roadmap). Another option - bring the connector in runtime by adding it to the spark.jars or spark.jars.packages."

Thanks
