### ISSUE TITLE
Failed to find data source: bigquery

### ISSUE THREAD

**Issue by nick-msca** [GoogleCloudDataproc/spark-bigquery-connector#261]
I followed instructions for "Using in Jupyter Notebooks", but keep getting "java.lang.ClassNotFoundException: Failed to find data source: bigquery".  I did check my Scala version and chose correct dependency "com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.17.3"

I am executing from Google Dataproc Hub
[BigQuery_Spark_v2.zip](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/files/5460837/BigQuery_Spark_v2.zip)

**Comment by nick-msca** [comment]
spark.sparkContext._jvm.scala.util.Properties.versionString()
'version 2.12.12'

spark = SparkSession.builder\
  .config("spark.jars.packages", "com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.17.3")\
  .getOrCreate()

df = spark.read.format("bigquery")\
  .load("bigquery-public-data.chicago_crime.crime")

Py4JJavaError: An error occurred while calling o63.load.
: java.lang.ClassNotFoundException: Failed to find data source: bigquery. Please find packages at http://spark.apache.org/third-party-projects.html

**Comment by mingjialiu** [comment]
Please check your syntax. 

To use datasource V1: 
df = spark.read.format("bigquery").load('bigquery-public-data.chicago_crime.crime')
df.createOrReplaceTempView(table)

To use datasource V2: 
df = spark.read.format("com.google.cloud.spark.bigquery.v2.BigQueryDataSourceV2").option("table",'bigquery-public-data.chicago_crime.crime').load()

**Comment by nick-msca** [comment]
My syntax is identical to your V1.

df = spark.read.format("bigquery").load('bigquery-public-data.chicago_crime.crime')

Py4JJavaError: An error occurred while calling o63.load.
: java.lang.ClassNotFoundException: Failed to find data source: bigquery. Please find packages at http://spark.apache.org/third-party-projects.html


I tried your V2 example as well.  Getting the same

df = spark.read.format("com.google.cloud.spark.bigquery.v2.BigQueryDataSourceV2").option("table",'bigquery-public-data.chicago_crime.crime').load()

Py4JJavaError: An error occurred while calling o68.load.
: java.lang.ClassNotFoundException: Failed to find data source: com.google.cloud.spark.bigquery.v2.BigQueryDataSourceV2. Please find packages at http://spark.apache.org/third-party-projects.html

**Comment by mingjialiu** [comment]
From the attached notebook, you are using kernel pyspark. 
Please change it to python3. 

I am able to repro your issue with pyspark kernel. But it's gone after switching to python3.

**Comment by nick-msca** [comment]
Thanks.  That solved the problem.  As FYI: there was nothing in the instructions indicating we should be using Python3 kernel vs PySpark (which is kind of counter-intuitive)

**Comment by nmusku** [comment]
Sorry for the naive ques: what is the difference between com.google.cloud.spark.bigquery.v2.BigQueryDataSourceV2 and V1

**Comment by davidrabinowitz** [comment]
@nmusku Not naive at all - com.google.cloud.spark.bigquery.v2.BigQueryDataSourceV2 is the next version of the connector underlying implementation, still in development. You are welcome to use is for testing purposes. The V1 implementation is the standard "bigquery" format.
