### ISSUE TITLE
What should be the default readDataFormat?

### ISSUE THREAD

**Issue by gandola** [GoogleCloudDataproc/spark-bigquery-connector#264]
Documentation says that the default `readDataFormat` is `AVRO` but in the code looks like it is `ARROW` as we can see [here](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java#L54). 

Not sure if this is is a typo in the documentation or if it the default should actually be `AVRO`.

Cheers

**Comment by davidrabinowitz** [comment]
Arrow is the default format. Thanks for the bringing this to our attention.
