### ISSUE TITLE
Operator precedence on pushed down filters

### ISSUE THREAD

**Issue by gandola** [GoogleCloudDataproc/spark-bigquery-connector#265]
Using `AVRO` as `readDataFormat`, the connector is pushing down the following filter query into BigQuery as expected.

```scala
df
.filter(
  (col("c1") >= to_date(lit("2020-09-01")) or col("c1").isNull)
  and
  (col("c2") >= to_date(lit("2020-09-15")) or col("c2").isNull)
  and
  (col("c3") <= to_date(lit("2020-09-15")) or col("c3").isNull)
)
```

However, the filter that comes in the logs is:

```
((`col1` >= '2020-09-01') OR (`col1` IS NULL) AND (`col2` >= '2020-09-15') OR (`col2` IS NULL) AND (`col3` <= '2020-09-15') OR (`col3` IS NULL))
```

Shouldn't `ORs` be enclosed into `()`? 
Due the operator precedence this won't give me the result that I expect from BQ.

Thank you,
Cheers

**Comment by himanshukohli09** [comment]
Hi Pedro, 

Thanks for bringing this up.  This issue has been resolved.
