### ISSUE TITLE
Writing a complex filter fails with a strange exception

### ISSUE THREAD

**Issue by AmineSagaama** [GoogleCloudDataproc/spark-bigquery-connector#268]
I'm reading a BigQuery Table using spark-bigquery-connector, and manually specifying a filter option to pushdown filter : 

```
spark.read.bigquery("mybqproject.dataset.table")
.option("filter", "first_name = 'test' OR (first_name = 'joe' AND last_name = 'go') OR ( first_name = 'test2' AND last_name = 'name2')")
```

When I execute this query, I get this error : 
`INVALID_ARGUMENT: request failed: row filter '(first_name = 'test' OR (first_name = 'joe' AND last_name = 'go') OR ( first_name = 'test2' AND last_name = 'name2'))' is too complex to be processed in filtering; consider executing a query instead.`

Note: This query works perfectly with BigQuery console.

When I execute another query on this table, but with a simple filter, it works : 
```
spark.read.bigquery("mybqproject.dataset.table")
.option("filter", " first_name = 'test' OR first_name = 'joe' ")
```

spark-bigquery-connector : '2.12-0.17.3'
spark version : 3.0.1
scala version : 2.12.12

Thanks,

**Comment by davidrabinowitz** [comment]
Please try the following:
```
spark.read
  .option("readDataFormat", "AVRO")
  .option("filter", "first_name = 'test' OR (first_name = 'joe' AND last_name = 'go') OR ( first_name = 'test2' AND last_name = 'name2')")
  .bigquery("mybqproject.dataset.table")
```
