### ISSUE TITLE
[DOCUMENTATION ONLY] Update PySpark Job Example

### ISSUE THREAD

**Issue by cpcgoogle** [GoogleCloudDataproc/spark-bigquery-connector#272]
In the hello world for the Dataproc job, you should consider updating to show that you need the latest jar specific to the scala version for clusters > 1.5. i.e. gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar.

Using the hello world example as-is returns a ": java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider com.google.cloud.spark.bigquery.BigQueryRelationProvider could not be instantiated"

**Comment by charlesa101** [comment]
I am running into this same issue, any fix or suggestion on how to fix this?

**Comment by charlesa101** [comment]
i have tried to compile the code from the source as well

**Comment by gomrinal** [comment]
Any fix for this issue?

I'm running into issue when I'm trying to use bigquery-spark connector
