### ISSUE TITLE
Can we use a subquery in the filter option ?

### ISSUE THREAD

**Issue by AmineSagaama** [GoogleCloudDataproc/spark-bigquery-connector#278]
Hello,

I want to use a subquery, when reading from bigquery table, to get the last partition (I don't know the last partition in advance).
So, I used this query to get the last partition (I used a date partition column 'event_date' in my Table) : 

```
spark.read.bigquery("mybqproject.dataset.table")
.option("filter", "event_date = (SELECT max(event_date) FROM mybqproject.dataset.table))
.load()
```

When, I execute this query, I got this error : 

`INVALID_ARGUMENT: request failed: Row filter for table mybqproject.dataset.table is invalid. Filter is (event_date = (SELECT max(event_date) FROM mybqproject.dataset.table))`

Note: This query works perfectly with BigQuery console.

spark-bigquery-connector : '2.12-0.17.3'
spark version : 3.0.1
scala version : 2.12.12

Thanks,

**Comment by davidrabinowitz** [comment]
I'm afraid it is not supported by the BigQuery Storage API. You should get the last partition before reading the data, which you can do either:

* Running this query directly using `bigquery.query()`
* Avoid a full table scan by calling `bigquery.listPartitions()`
