### ISSUE TITLE
Shakespeare.scala link is missing in readme.

### ISSUE THREAD

**Issue by Zamlos** [GoogleCloudDataproc/spark-bigquery-connector#282]
It seems we don't have a documented example to run `spark-bigquery-connector` using Scala. It would be useful having it back.

**Comment by kumgaurav** [comment]
@Zamlos @davidrabinowitz created a working demo in Scala2.12, spark 3.1.1. lets me know if it helps.
https://github.com/kumgaurav/BigQuerySpark3Scala12.git

**Comment by davidrabinowitz** [comment]
Hi @Zamlos , thanks for your comment. Cn you please have a look at the exmaples linked from https://github.com/GoogleCloudDataproc/spark-bigquery-connector#reading-data-from-a-bigquery-table and let us know if you find anything missing?
