### ISSUE TITLE
Using multiple `.filter` methods does not get recognized by partition requirements

### ISSUE THREAD

**Issue by map222** [GoogleCloudDataproc/spark-bigquery-connector#284]
Hi,
I am using Spark to query a BigQuery table. If I run the code below, which filters on the partition column `date`, I am able to register the dataframe without errors:
```
exp_sdf = (spark.read
                 .option("parentProject", <private>)
                 .format("bigquery")
                 .option("table", exp_table)
                 .option("filter", f"DATE(date) = '{start_date}'")
                 .load()
                 .persist()
          )
```

However, if I add a second filter statement, I get an error:
```
exp_sdf = (spark.read
                 .option("parentProject", <private>)
                 .format("bigquery")
                 .option("table", exp_table)
                 .option("filter", f"DATE(date) = '{start_date}'")
                 .option("filter", f"metric_id IN {metric_str}")
                 .load()
                 .persist()
          )
```

```com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.InvalidArgumentException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: Cannot query over table <exp_table> without a filter over column(s) 'date' that can be used for partition elimination```

The solution is quite easy (combine the filters into a single statement, `.option("filter", f"DATE(date) = '{start_date}' AND metric_id IN {metric_str}")`), but I find dot-chaining filter statements to be more idiomatic Spark.

Or maybe I could reframe this as a question: are we only able to set one `filter` option because they are specific fields in a config? And in the code above, I am overwriting the `filter` be assigning it a second time?

**Comment by davidrabinowitz** [comment]
Spark's DataFrameReader options are backed by a map, so multiple setting of the same option will cause the last setting to overrun the previous one, Which is what had happened in this case. The way to solve it is to concatenate the conditions using `AND` : `.option("filter", f"DATE(date) = '{start_date}' AND metric_id IN {metric_str}")

**Comment by jaceklaskowski** [comment]
I'm curious why not let users specify these filter conditions using `filter` or `where` operators? Why is this required for the filters to be defined as options?

**Comment by davidrabinowitz** [comment]
It is not required, it was just added as an option. The only case where it is mandatory is when a table is partitioned on the insert date (using the _PARTITIONDATE pseudo column) and the user wants (or required to) filter by this column.
In the normal case the usage of `.where()` (including chained `.where()` calls) is supported and very common.

**Comment by walmaaoui** [comment]
It seems that there are some case where its required to use filter (correct me if I am wrong):
- **between** operator  https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/98
- **IN** operator (just tested in local, seems to not work if the IN list contains more than 1 element)

Do you confirm? Is this list compete?

**Comment by davidrabinowitz** [comment]
The issue #98 issue was because spark treated the values as String where the type was `date` - Spark does not provide implicit conversions to the Data Sources.

I suspect that the long->int casting may have the same effect, please provide a code snippet to reproduce this issue. Also, please open another issue for this, as issue #284 has been closed
