### ISSUE TITLE
ALLOW_FIELD_ADDITION not working

### ISSUE THREAD

**Issue by cejj** [GoogleCloudDataproc/spark-bigquery-connector#287]
I tried executing the below snippet of code and looks like ALLOW_FIELD_ADDITION is not working:-

```
val df = spark.read.bigquery("bigquery-public-data.samples.shakespeare")

#Create table with word and word_count columns
df.select("word","word_count").write.mode("append").format("bigquery").option("temporaryGcsBucket",<bucket_name>.option("allowFieldAddition","true").save("demo.table_shake_1")

#Append corpus column
df.select("word","word_count","corpus").write.mode("append").format("bigquery").option("temporaryGcsBucket",<bucket_name>).option("allowFieldAddition","true").save("demo.table_shake_1")
```

When I execute the df.write by adding the "corpus" column I am getting the error "Cannot add required fields to an existing schema. (field: corpus)" even though I have set allowFieldAddition to true.

**Comment by davidrabinowitz** [comment]
Please note that according to the [documentation](https://cloud.google.com/bigquery/docs/samples/bigquery-add-column-load-append#bigquery_add_column_load_append-java):

> 'REQUIRED' fields cannot  be added to an existing schema, so the additional column must be 'NULLABLE'.

Therefore, please convert all the new columns' schema to nullable.
