### ISSUE TITLE
Getting User does not have bigquery.tables.create permission

### ISSUE THREAD

**Issue by dineshvelmuruga** [GoogleCloudDataproc/spark-bigquery-connector#288]
**Scenario**
I have two projects pinned in Big Query say, **project_dev** and **project_prod**. One is my dev area and other one is production. I have full access on dev area and read access in prod. 

**Requirements**
I want to read the prod dataset/tables using the spark-bigquery-connector.

**Code**
spark = SparkSession.builder \
.appName('1.1. BigQuery Storage & Spark DataFrames - Python') \
.getOrCreate()

df = spark.read.format('bigquery') \
.option("viewsEnabled", "true") \
.load('project_prod.<prod_dataset>.<prod_table>')

Project associated with service account is  **project_dev**

**Error**
Py4JJavaError: An error occurred while calling o229.count.
: com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.UncheckedExecutionException: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Access Denied: Dataset **project_prod.<prod_dataset>**

User does not have bigquery.tables.create permission for dataset **project_prod.<prod_dataset>**.

**Question**
I have read access on project_prod but why it throws error for create table permission. Why it is trying to creating table in project_prod

How to resolve this error? Can I give temp dataset to create the tables?

**Comment by davidrabinowitz** [comment]
In order to read views the data needs to be materialized, and a temporary table is created. In order to do that, the `bigquery.tables.create` permission is needed. You can control the matrialization project and dataset using the `matrializationProject` and `matrializationDataset` options

**Comment by A-JXS7183-temp** [comment]
@davidrabinowitz   We are facing same issue . I just want to be know this temp table creation issue is only in case of spark job or another as well.

**Comment by MyTestCheck** [comment]
Hi @davidrabinowitz , We are facing same issue. I just want to be know this create temp table issue is only occur in case of  Spark or any other as well.
