### ISSUE TITLE
Issue with writing Date datatype in BigQuery

### ISSUE THREAD

**Issue by arunkindra** [GoogleCloudDataproc/spark-bigquery-connector#300]
I am trying to write the data into Date Column of BigQuery and its failing with below exception.

BigQuery error was Provided Schema does not match Table <project_id>:<datasetname>.<tablename>. Field createdDate has changed type from DATE to INTEGER
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:156)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:89)
	... 36 more

**Sample Code:**

Dataset<Row> ds = session.createDataset(
        Collections.singletonList(1), Encoders.INT()).toDF()
        .select(col("value").as("Sno"));
ds = ds.withColumn("createdDate", current_date());
ds.printSchema();
ds.write().format("bigquery")
                .option("temporaryGcsBucket",temporaryGcsBucket)
                .option("table", projectId+"."+dataSetName+"."+tableName)
                .option("project", projectId)
                .option("parentProject", projectId)
                .option("intermediateFormat","avro")
                .mode(saveMode)
                .save();

**BigQuery Table DDL**
  CREATE TABLE <datasetname>.<tablename> (
  Sno int64,
  createdDate date);
  
  Print Schema gives correct schema though, not sure what is causing this issue.
  
  root
 |-- Sno: integer (nullable = true)
 |-- createdDate: date (nullable = false)

**Comment by davidrabinowitz** [comment]
Which connector version are you using? I was not able to reproduce this issue.

**Comment by arunkindra** [comment]
Hi @davidrabinowitz 

Here is the pom dependency.

<dependency>
            <groupId>com.google.cloud.spark</groupId>
            <artifactId>spark-bigquery-with-dependencies_2.11</artifactId>
            <version>0.17.3</version>
</dependency>

Dataproc version:- dataproc-release-1.4

**Comment by arunkindra** [comment]
Hi @davidrabinowitz 

I found the root cause of the root cause of this. The intermediate format avro is causing this issue. If I comment (.option("intermediateFormat","avro")), then it is working fine.
Based on our earlier discussion on other issue(https://stackoverflow.com/questions/65023156/save-arrayt-in-bigquery-using-java/65079560#65079560), you suggested us to use intermediateFormat avro/orc. As we have Array string and Array Struct datatype in our tables. 

Can you please let us know if you can provide the fix for the same, so that we can plan our release?

**Comment by davidrabinowitz** [comment]
I was still were not able to reproduce the issue. Can you please use the `useAvroLogicalTypes` option added in the last version 0.18.1?
