### ISSUE TITLE
Error with latest jar file when trying to show dataframe

### ISSUE THREAD

**Issue by charlesa101** [GoogleCloudDataproc/spark-bigquery-connector#303]
@davidrabinowitz: Any suggestions on what I may be doing wrong here? I am running

``` java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
```

but any time I try to run a simple select query statement i am getting this error? when I call the

`df.show()` or `df.count()` on my dataframe in pyspark

```py4j.protocol.Py4JJavaError: An error occurred while calling o38.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task serialization failed: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.spark.util.io.ChunkedByteBufferOutputStream.toChunkedByteBuffer(ChunkedByteBufferOutputStream.scala:115)
        at org.apache.spark.broadcast.TorrentBroadcast$.blockifyObject(TorrentBroadcast.scala:323)
        at org.apache.spark.broadcast.TorrentBroadcast.writeBlocks(TorrentBroadcast.scala:138)
        at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:91)
        at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:35)
        at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:77)
        at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1509)
        at org.apache.spark.scheduler.DAGScheduler.submitMissingTasks(DAGScheduler.scala:1383)
```

**Comment by davidrabinowitz** [comment]
Hi @charlesa101 ,

Can you please share the spark version, scala version, environment (Dataproc/other) and add a code snippet for reproducing the issue?

**Comment by charlesa101** [comment]
spark version =  3.2.0-SNAPSHOT
scala version = 2.12
environment = Spark Dockker container for Kubernetes

what's the recommended spark/scala/jvm version to run a pyspark job?

**Comment by JordanYankovich** [comment]
Also encountering this issue, @davidrabinowitz can you provide update (..or preferred versions to run the pyspark jobs?)

**Comment by davidrabinowitz** [comment]
Can you also share the Java version?

**Comment by JordanYankovich** [comment]
@davidrabinowitz 

openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

**Comment by JordanYankovich** [comment]
FYI @davidrabinowitz also trying to run via a docker container

**Comment by davidrabinowitz** [comment]
@JordanYankovich @charlesa101 can you please share the docker configuration (the non-sensitive parts)?

**Comment by JordanYankovich** [comment]
Sure, the base spark image I am using is directly from https://github.com/apache/spark/ 

With this image I am using JRE v8 since v11 isn't yet supported by this connector (based on your response from another ticket). 

I'm unable to get the example from GCP docs (https://cloud.google.com/dataproc/docs/tutorials/bigquery-connector-spark-example) running in any docker image. 

Dockerfile I have currently: 

FROM spark-py:v3.0.0 (this image was created from the github link above)

COPY  spark-bigquery-latest_2.12.jar /opt/spark/jars/spark-bigquery-latest_2.12.jar.  (copies bigquery jar file) 

COPY xxxxxx (copies example python file from GCP link above to container)

**Comment by brettleighton** [comment]
Also encountering this issue

**Comment by JordanYankovich** [comment]
@davidrabinowitz some research indicates the issue is consistent for environments that run JDK 1.8 but compiled with a higher version. 

Were JDK version were the artifacts in this repository (i.e. gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar ) compiled with?

**Comment by davidrabinowitz** [comment]
Can you please try with one of the following jars:
* `gs://davidrab-public/spark-bigquery-issue-303_2.11.jar`
* `gs://davidrab-public/spark-bigquery-issue-303_2.12.jar`

**Comment by JordanYankovich** [comment]
Hey David, 

I was able to get around this issue by changing the Docker base image I was using.

I downloaded spark v3.0.1 w/ Hadoop 3.2 and later from spark.apache.org to build a docker image and that fixed my issue. Downloading directly from https://github.com/apache/spark and building an image from there seemed to cause issues.

**Comment by davidrabinowitz** [comment]
@charlesa101 @brettleighton I'd appreciate if you can test my above suggestion. Also, is your image based on a github download?

**Comment by charlesa101** [comment]
Thanks, @davidrabinowitz, and @JordanYankovich! that fixed my issue as well

The base image was built with what @JordanYankovich  recommended, we needed to customize the base image
