### ISSUE TITLE
BigQueryPartition ClassNotFoundException error in Dataproc PySpark Jupyter Notebook

### ISSUE THREAD

**Issue by Ernestyj** [GoogleCloudDataproc/spark-bigquery-connector#304]
When I execute below code to query a BigQuery table with partitions, it raises BigQueryPartition ClassNotFoundException. But if I query a table without  partitions, it works.

```python
from pyspark.sql import SparkSession

spark = SparkSession \
  .builder \
  .master('yarn') \
  .config("spark.jars.packages", "com.google.cloud.spark:spark-bigquery-with-dependencies_2.11:0.18.1") \
  .appName('spark-bigquery-demo') \
  .getOrCreate()

bucket = "ces-test-bigquery"
spark.conf.set('temporaryGcsBucket', bucket)

df = spark.read.format("bigquery").option("table", "pp-devcos-dta-ces.test.xxxx")\
    .option("filter", "_PARTITIONTIME > '2021-01-10'")\
    .load()
df.printSchema()
df.show(5)
```

Py4JJavaError: An error occurred while calling o167.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 11, spark-jupyter-ces-test-bigquery-w-0.c.pp-devcos-dta-ces.internal, executor 2): java.lang.ClassNotFoundException: com.google.cloud.spark.bigquery.direct.BigQueryPartition
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

**Comment by davidrabinowitz** [comment]
@Ernestyj Can you please specify the spark version, scala version and java version? Are you running on Dataproc?

**Comment by Ernestyj** [comment]
openjdk version "1.8.0_275"
Scala code runner version 2.11.12
Spark version 2.3.4
Python version 2.7.14

**Comment by davidrabinowitz** [comment]
I'm afraid I was not able to reproduce the issue. Can you please share more environment details? Is the error consistent? Can you try the following option instead of `spark.jars.packages` - `.option('spark.jars','https://storage.googleapis.com/spark-lib/bigquery/spark-bigquery-latest_2.11.jar')` ?
