### ISSUE TITLE
Unable to overwrite table partition\s

### ISSUE THREAD

**Issue by spark49** [GoogleCloudDataproc/spark-bigquery-connector#308]
Hello, i was trying to perform some operations over a SparkDataFrame that than must be overwritten into specific date partion.
I was using this kind of configuration: 

```Python
 spark = SparkSession.builder.master('yarn') \
              .config('spark.jars', 'gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar') \
              .appName('spark-bigsdquery-demo').getOrCreate()
```

over DataProc cluster with image: **1.5-debian10**

The last column of the SparkDataFrame is the following: 
![image](https://user-images.githubusercontent.com/15384039/107980661-f208d080-6fc0-11eb-96cc-e5985db1c9c9.png)

and according to the date **datePartition** option the column is in the right format.

During overwriting: 

```Python
spark.conf.set("temporaryGcsBucket",bucket)
table = f"{gcp_project_id}.{gcp_dataset_id}.{gcp_table}"
frame_to_write_on_bq.write \
  .format("bigquery") \
  .option('createDisposition', 'CREATE_IF_NEEDED') \
  .option("datePartition", date) \
  .option('partitionField', "insert_date") \
  .option('partitionType', 'DAY') \
  .mode('overwrite') \
  .save(table)

```

It always gives me the following the error: 

---------------------------------------------------------------------------

> Py4JJavaError                             Traceback (most recent call last)
> /usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
>      62         try:
> ---> 63             return f(*a, **kw)
>      64         except py4j.protocol.Py4JJavaError as e:
> 
> /opt/conda/anaconda/lib/python3.7/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
>     327                     "An error occurred while calling {0}{1}{2}.\n".
> --> 328                     format(target_id, ".", name), value)
>     329             else:
> 

> Py4JJavaError: An error occurred while calling o818.save.
> : java.lang.IllegalArgumentException: Invalid argument for option datePartition, format is YYYYMMDD
> 	at com.google.cloud.spark.bigquery.SparkBigQueryConfig.validateDateFormat(SparkBigQueryConfig.java:239)
> 	at com.google.cloud.spark.bigquery.SparkBigQueryConfig.lambda$from$2(SparkBigQueryConfig.java:137)
> 	at java.util.Optional.ifPresent(Optional.java:159)
> 	at com.google.cloud.spark.bigquery.SparkBigQueryConfig.from(SparkBigQueryConfig.java:136)
> 	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createSparkBigQueryConfig(BigQueryRelationProvider.scala:139)
> 	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:99)
> 	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
> 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
> 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
> 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
> 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:131)
> 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:155)
> 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
> 	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
> 	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
> 	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
> 	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
> 	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:696)
> 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:80)
> 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
> 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
> 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:696)
> 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:310)
> 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:291)
> 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:249)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 	at py4j.Gateway.invoke(Gateway.java:282)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
> 	at java.lang.Thread.run(Thread.java:748)
> 
---------------------------------------------------------------------------

Is there something else that is needed to be setted on writing disposition? It seems that according README file this was the right way to overwrite a partition. 

Moreover i would like to know It at once more than one partition could be updated

**Comment by davidrabinowitz** [comment]
Please make sure that the data is a string in the format YYYYMMDD, as the error says: `Invalid argument for option datePartition, format is YYYYMMDD`.

**Comment by spark49** [comment]
Ok thank you. The connector allow the possibilities to overwrite multiple partition at once, if yes how this could be managed? or is able to overwrite only one at time?
