### ISSUE TITLE
Join multiple tables together in Big query

### ISSUE THREAD

**Issue by phitotient** [GoogleCloudDataproc/spark-bigquery-connector#311]
Hi,

Is there any option which actually pushes down the spark sql query joins to bigquery in order to join them and fetch only the results back in dataframe instead of loading the complete tables separately in spark and then performing join on spark side

**Comment by davidrabinowitz** [comment]
In the upcoming release (very soon!) PR #305 is merged and will allow you to run any arbitrary sql query (including joins) directly on BigQuery, and just fetch the results.
