### ISSUE TITLE
Streaming sink into BigQuery table from Spark

### ISSUE THREAD

**Issue by michTalebzadeh** [GoogleCloudDataproc/spark-bigquery-connector#321]
Hi,
I am trying to create a streaming sink from Spark structured streaming to BigQuery. The source of data is live market data prices that are streamed through Kafka topic into Spark structured streaming and then a BigQuery sink needs to be created such that this data is added to a BigQuery table.

I have not seen any example of this yet. The usual Spark-BigQuery API will not be useful in this case. although there is a fair bit of overlap.

```
class MDStreaming:
    def __init__(self, spark_session,spark_context):
        self.spark = spark_session
        self.sc = spark_context
        self.config = config

    def startStreaming(self):
        self.sc.setLogLevel("ERROR")

        # a Kafka row example shown below
        #{"rowkey":"c9289c6e-77f5-4a65-9dfb-d6b675d67cff","ticker":"MSFT", "timeissued":"2021-02-23T08:42:23", "price":31.12}

        schema = StructType().add("rowkey", StringType()).add("ticker", StringType()).add("timeissued", TimestampType()).add("price", FloatType())
        try:
            # construct a streaming dataframe streamingDataFrame that subscribes to topic config['MDVariables']['topic']) -> md (market data)
            streamingDataFrame = self.spark \
                .readStream \
                .format("kafka") \
                .option("kafka.bootstrap.servers", config['MDVariables']['bootstrapServers'],) \
                .option("schema.registry.url", config['MDVariables']['schemaRegistryURL']) \
                .option("group.id", config['common']['appName']) \
                .option("zookeeper.connection.timeout.ms", config['MDVariables']['zookeeperConnectionTimeoutMs']) \
                .option("rebalance.backoff.ms", config['MDVariables']['rebalanceBackoffMS']) \
                .option("zookeeper.session.timeout.ms", config['MDVariables']['zookeeperSessionTimeOutMs']) \
                .option("auto.commit.interval.ms", config['MDVariables']['autoCommitIntervalMS']) \
                .option("subscribe", config['MDVariables']['topic']) \
                .option("failOnDataLoss", "false") \
                .option("includeHeaders", "true") \
                .option("startingOffsets", "earliest") \
                .load() \
                .select(from_json(col("value").cast("string"), schema).alias("parsed_value"))
            return streamingDataFrame
        except Exception as e:
                print(f"""{e}, quitting""")
                sys.exit(1)

def processData(self, streamingDataFrame):

        result = streamingDataFrame. \
                     writeStream. \
                     foreach(ForeachWriter()). \
                     start()

        result.awaitTermination()

if __name__ == "__main__":
    appName = config['common']['appName']
    spark_session = s.spark_session(appName)
    spark_session = s.setSparkConfBQ(spark_session)
    spark_context = s.sparkcontext()
    mdstreaming = MDStreaming(spark_session, spark_context)
    streamingDataFrame = mdstreaming.startStreaming()
    mdstreaming.processData(streamingDataFrame)
```

That class ForeachWriter() is supposed to add data (batchsize 10 rows) to the GCP BigQuery table. My code is as follows: However, it does not seem to invoke methods in this class. Every 2 seconds a batch of 10 rows passed to this class. Specifically in the method process(self,row) what is rows_to_insert = [... signify?

```
class ForeachWriter:

    '''

    Class to send a set of rows to BigQuery.

    When used with `foreach`, copies of this class is going to be used to write

    multiple rows in the executor. See the python docs for `DataStreamWriter.foreach`

    for more details.

    '''
    def open(self):

        # This is called first when preparing to send multiple rows.

        # Put all the initialization code inside open() so that a fresh

        # copy of this class is initialized in the executor where open()

        # will be called.

        self.config = config

        self.table_id = self.config['MDVariables']['fullyQualifiedoutputTableId']

        self.client = bigquery.Client(self.config['MDVariables']['projectId'])

        self.table_ref = client.dataset(self.config['MDVariables']['targetDataset']).table(self.table_id)

        return True

    def process(self,row):



        # This is called for each row after open() has been called.

        # This implementation sends one row at a time.

        # A more efficient implementation can be to send batches of rows at a time.

        rows_to_insert = [

            {u"full_name": u"Phred Phlyntstone", u"age": 32},

            {u"full_name": u"Wylma Phlyntstone", u"age": 29},

        ]


        errors = client.insert_rows_json(self.table_id, self.config['MDVariables']['rows_to_insert'], row_ids=[None] * len(self.config['MDVariables']['rows_to_insert'])

        )  # Make an API request.

        if errors == []:

          print("New rows have been added.")

        else:

          print("Encountered errors while inserting rows: {}".format(errors))

    def close(self, err):

        # This is called after all the rows have been processed.

        if err:

            raise err
```

**Comment by michTalebzadeh** [comment]
Hi,

I sorted this one out using foreachBatch function in writeStream. Basically streaming data rows (securities) through Kafka to Spark structured Streaming and saving data to BQ via Spark BigQuery API.

Cheers

**Comment by michTalebzadeh** [comment]
Hi,

I am using the latest build of Dataproc 2.0.x release versions that uses Apache spark 3.1.1-RC 2 (release candidate).

2.0.x release versions  |  Dataproc Documentation  |  Google Cloud  
 

In short a spark structured streaming job runs OK on on-premise on Spark version version 3.0.1 and shows streaming data but it does not work on Dataproc with Spark 3.1.1

The problem is that Spark 3.1.1 is not available now for download from Spark site. What is used in Dataproc is 3.1.1-rc2 release candidate. This is concerning on how a release candidate version of Spark was chosen to build the cluster. Spark release site states

Release Notes for Stable Releases
Spark 3.0.2 (Feb 19 2021)
Spark 2.4.7 (Sep 12 2020)

Now as this is offered as PaaS, it would be good to know how can this be rectified. You are welcome to do your own testing.

Finally who should I contact in Google Cloud to raise this issue. FYI I raised a case in

cloud-dataproc-discuss@googlegroups.com

Thanks,

Mich
--





cloud-dataproc-discuss@googlegroups.com
--

**Comment by michTalebzadeh** [comment]
Thanks I added the details to Google Dataproc mailing list.

Cheers,

Mich

**Comment by kaiseu** [comment]
seems this topic is no longer active? do we finally have any guidelines for streaming sink into bigquery?

**Comment by michTalebzadeh** [comment]
Hi,

I have tested streaming job ONLY with Spark latest 3.4.0 and it works using
Python 3,9 see my notes below

Testing the newly released spark 3.4, sounds like some applications
require Python
3.9It used to work with Python 3.7.3 but spark structured streaming fails.
I had to build a Python virtual environment on Python 3.9.16 to make Spark
streaming to work. In addition, you will need this latest package
org.apache.spark:spark-sql-kafka-0-10_2.12:*3.4.0* added to your
spark-submit job. The package takes care of transitive dependencies.So
something like belowspark-submit --master local[4] --py-files $DEPENDENCIES
--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.0Where $DEPENDENCIES
is the zipped file from the virtual environment in my case vend3.9
/usr/src/Python-3.9.16/venv3.9/lib/python3.9/dependencies.zipGo to
site-packages directory site-packages in your virtual environment, like
below as root/usr/src/Python-3.9.16/venv3.9/lib/python3.9/site-packageszip
-r ../dependencies.zip .
ls -l ../dependencies.zipThen export
export
DEPENDENCIES="/usr/src/Python-3.9.16/venv3.9/lib/python3.9/dependencies.zip"
 (edited) .

Spark 3.4.0 connection to BigQuery

I tested the latest release of Spark 3.4 against BigQuery. It works fine as
long as you add the following two jar files to $SPARK_HOME/jars
spark-bigquery-latest_2.12.jar
gcs-connector-hadoop3-2.2.0-shaded.jarAnd softlinkgcs-connector.jar ->
gcs-connector-hadoop3-2.2.0-shaded.jar
*Also works with Java 8. Java 17 fails*

What version of Java with spark connector works with BigQuery?


   view my Linkedin profile
<https://www.linkedin.com/in/mich-talebzadeh-ph-d-5205b2/>


 https://en.everybodywiki.com/Mich_Talebzadeh



*Disclaimer:* Use it at your own risk. Any and all responsibility for any
loss, damage or destruction of data or any other property which may arise
from relying on this email's technical content is explicitly disclaimed.
The author will in no case be liable for any monetary damages arising from
such loss, damage or destruction.

**Comment by michTalebzadeh** [comment]
I have tested Google connectivity to BigQuery using VM hosts 

This is the version of Java that works OK with BigQuery and spark

 java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)


If you have higher version of Java, Spark connector to BigQuery will fail. I tested the latest Spark (3.4). As long as your VM host runs Java 8 it should work , regardless of Spark version.

So you have the choice of installing JAVA 8 and run your job again.

**Comment by michTalebzadeh** [comment]
Hi,

What version of  gcs-connector works with spark 3.4.1  please?

This one  gcs-connector-hadoop3-2.2.0-shaded.jar worked with 3.4.  But does not seem to work Spark 3.4.1

Thanks

**Comment by davidrabinowitz** [comment]
Hi @michTalebzadeh 

I believe this question should be asked in the [gcs-connector repo](https://github.com/GoogleCloudDataproc/hadoop-connectors).

Also, we'd appreciate it that new questions or issues will be opened as new GitHub issues.

Thanks!
