### ISSUE TITLE
[Question] Spark 3.x support

### ISSUE THREAD

**Issue by maasg** [GoogleCloudDataproc/spark-bigquery-connector#344]
Hi,

Would you have some roadmap information about when the connector is expected to support Spark 3.x ?
We had to downgrade our Spark from 3.0.1 to 2.4.5 to use the connector. I'd like to plan the upgrade to be back on the 3.x version :-)

Thanks!

**Comment by davidrabinowitz** [comment]
The connector has been tested on Spark 3.1 on Dataproc. You can also try version 0.19.0 which has updated dependencies.

**Comment by maasg** [comment]
Thanks, David! 
I'm using `com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.19.1`. Should it work?
I have now a Spark 2.4.5 + bqc 0.19.1 combo working. If I attempt to upgrade Spark back to 3.0.1, I get:
```
'void com.fasterxml.jackson.databind.JsonMappingException.<init>(java.io.Closeable, java.lang.String)'
java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.databind.JsonMappingException.<init>(java.io.Closeable, java.lang.String)'
	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:718)
```
Back in the days, I contributed to the Spark-Cassandra connector, so I'm familiar with the ecosystem, and yet, I've been having quite some trouble aligning all the moons of the library versions in this case.

But, we don't have a vanilla Spark cluster but rather a backend application that uses Spark as a data-abstraction layer. 
Some of our other dependencies might be playing a role here as well. (Arrow 3.0, for example)

**Comment by maasg** [comment]
This was due to a mismatch in the forced Jackson dependencies in the project.
Solved now. Thanks!
