### ISSUE TITLE
INVALID_ARGUMENT: request failed: Row filter

### ISSUE THREAD

**Issue by punishgarg** [GoogleCloudDataproc/spark-bigquery-connector#345]
Hi team,
I am using Spark Big query connector outside of GCP environment with Service account authentication:

below is my build.sbt file 

scalaVersion := "2.11.12"
"com.google.cloud.spark" % "spark-bigquery-with-dependencies_2.11" % "0.19.0"
org.apache.spark %% "spark-core" % "2.2.1" 
org.apache.spark %% "spark-sql" % "2.2.1"  
org.apache.spark %% "spark-hive" % "2.2.1"  

assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs@_*) => MergeStrategy.discard
  case _ => MergeStrategy.first
}

Code is very simple:

val df = spark.read.format("com.google.cloud.spark.bigquery")
      .option("credentials", "encoded")
      .option("viewsEnabled", "true")
      .option("project", "project_name")
      .option("parentProject", "project_name")
      .option("dataset", "Dataset-Name")
      .option("table", "consolidated_cost_view")
      .option("filter", "invoice.month='202102'") // passing this filter
      .load()
    df.show()

and facing below issue in our environment. can someone take a look into this.

com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.InvalidArgumentException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: **INVALID_ARGUMENT: request failed: Row filter for table billing-bucket:eg_gcp_billing._sbc_81885d6f01b94a7eb464cf3396c6eaa1 is invalid. Filter is '(invoice.month='202102')'**
App > 	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49)
App > 	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
App > 	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
App > 	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
App > 	at com.google.cloud.spark.bigquery.repackaged.com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
App > 	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1074)
App > 	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
App > 	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1213)
App > 	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
App > 	at com.google.cloud.spark.bigquery.repackaged.com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
App > 	at com.google.cloud.spark.bigquery.repackaged.io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
App > 	at com.google.cloud.spark.bigquery.repackaged.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
App > 	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:464)
App > 	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:428)
App > 	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:461)
App > 	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
App > 	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
App > 	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
App > 	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
App > 	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
App > 	at com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
App > 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
App > 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
App > 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
App > 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
App > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
App > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
App > 	at java.lang.Thread.run(Thread.java:748)

**Comment by davidrabinowitz** [comment]
What is the type of the `month` field in the view?

**Comment by punishgarg** [comment]
@davidrabinowitz it is yyyyMM format only, even i can see query is successfully completed at project history under Big query option. I am not sure what is an issue.

**Comment by punishgarg** [comment]
@davidrabinowitz This is billing table schema

https://cloud.google.com/billing/docs/how-to/export-data-bigquery-tables#data-schema

**Comment by punishgarg** [comment]
This was resolved. Issue was like, i am not selecting final invoice.month column in my final data frame. Looks like Big query connector is doing column pruning and pushing this column as not required which results it is throwing an exception. Invalid argument: row_filter.

I am not sure this is bug or as per designed. generally it won't happen in spark use case
@davidrabinowitz

**Comment by davidrabinowitz** [comment]
The BigQuery Storage API powering the connector does not support nested queries yet. You can replace reading from the view by crafting a sql query and load your data directly from from its result (a feature added in version 0.19), thus filtering the rows using the BigQuery query engine, not the storage API.
