### ISSUE TITLE
Unable to write into __NULL__ partition of BQ table

### ISSUE THREAD

**Issue by pythonrocks** [GoogleCloudDataproc/spark-bigquery-connector#349]
BQ supports __NULL__ partition for [partitioned tables](https://cloud.google.com/bigquery/docs/partitioned-tables#date_timestamp_partitioned_tables). It seems it's not possible (or I'm missing something) to overwrite that partition as `datePartition` option only supports YYYYMMDD date formatted value and doesnt accept "__NULL__" or null value. Is it possible to support writing to such partitions?

Thanks

**Comment by himanshukohli09** [comment]
Hi Mykola,

Currently overwriting the "NULL" partition is not supported by the spark-bigquery-connector. Alternatively what can be done is, you can delete the rows with null values (see : https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#delete_statement) and then can write the new values with SaveMode.Append

**Comment by pythonrocks** [comment]
Thank you for the claficication, any plans to add such support?

**Comment by himanshukohli09** [comment]
Its in the roadmap, but won't be able to comment on the timeline.
