### ISSUE TITLE
Unable to write bigquery partition table with date column as partition 

### ISSUE THREAD

**Issue by anjijava16** [GoogleCloudDataproc/spark-bigquery-connector#358]
Hi Team,
@davidrabinowitz 
I am trying to write bigquery partition table but i am unable to write getting different errors 

**pyspark submit :** 
```
gcloud dataproc jobs submit pyspark --cluster cluster-d550  --region us-central1    --jars gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar  gs://iwinner-data/pyspark/read_file_write_bigquery.py
```

```
df.write \
    .format("bigquery") \
    .option("temporaryGcsBucket", "iwinner-data-temp") \
    .option("datePartition", "YYYYMMDD") \
    .option('partitionField', "process_date") \
    .mode('overwrite').save(target_table)
```

**Error :**

1) Error in custom provider, java.lang.IllegalArgumentException: Invalid argument for option datePartition, format is YYYYMMDD
  at com.google.cloud.spark.bigquery.v2.SparkBigQueryConnectorModule.provideSparkBigQueryConfig(SparkBigQueryConnectorModule.java:68)
  while locating com.google.cloud.spark.bigquery.SparkBigQueryConfig

**2nd tried like below :**
```
df.write \
    .format("bigquery") \
    .option("temporaryGcsBucket", "iwinner-data-temp") \
    .option('partitionField', "process_date") \
    .option('partitionType', 'DAY') \
    .mode('overwrite').save(target_table)
```
**Error**   Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Incompatible table partitioning specification. Expects partitioning specification interval(type:day,field:process_date) clustering(id), but input partitioning specification is interval(type:day,field:process_date)

**Comment by jtvmatos** [comment]
Hi,
In the first test, you must add the date you want to write in datepartition. Something like .option("datePartition", "20200101") .

In the second test i believe that the `clusteredFields` have not been declared:
expected:
`interval(type:day,field:process_date) clustering(id)`
provided: 
`interval(type:day,field:process_date)`

JT

**Comment by davidrabinowitz** [comment]
@anjijava16 As @jtvmatos wrote, in (1) you need to write the actual date in `YYYYMMDD` format for daily partitioned tables, such as `20210420`.

For (2) this will overwrite the entire table.

**Comment by kumgaurav** [comment]
@anjijava16 , you can try like this:
https://github.com/kumgaurav/BigQuerySpark3Scala12/blob/main/src/main/scala/com/kumargaurav/WriteBQTableWithPartitionDemo.scala
