### ISSUE TITLE
Default location is US - set EU

### ISSUE THREAD

**Issue by morisraelii** [GoogleCloudDataproc/spark-bigquery-connector#374]
My datasets are located in EU.
seems like queries are run in US by default
how should I set EU as location?

**Comment by morisraelii** [comment]
GET https://www.googleapis.com/bigquery/v2/projects/****/queries/****?location=US&maxResults=0&prettyPrint=false
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "Not found: *** was not found in location US",
    "reason" : "notFound"
  } ],
  "message" : "Not found: Dataset **** was not found in location US",
  "status" : "NOT_FOUND"

**Comment by shlapfish** [comment]
Did you figure out how to do it?
