### ISSUE TITLE
"Reading data from a BigQuery query" not working: dataset not parsed or provided

### ISSUE THREAD

**Issue by bogo96** [GoogleCloudDataproc/spark-bigquery-connector#382]
I'm using
~~~
Java 8
scala 2.12
dataproc image: 2.0-debian10
~~~

In my project, i have to send query to bigquery not using spark sql.
And i tried three ways but doesn't work.

### first try
```scala

var bigQueryOption = new HashMap<String, String>() {{
put("credentials", credentials);
put("viewsEnabled", "true");
}}

var dfReader = spark.read
      .options(bigQueryOption)
      .format('bigquery')

val df = dfReader
      .load("SELECT * FROM `project.dataset.table` LIMIT 5")
      .cache()
```

When i run this code, i got message like below.
~~~
Exception in thread "main" com.google.cloud.spark.bigquery.repackaged.com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.IllegalArgumentException: 'dataset' not parsed or provided.
  at com.google.cloud.spark.bigquery.v2.SparkBigQueryConnectorModule.provideSparkBigQueryConfig(SparkBigQueryConnectorModule.java:68)
  while locating com.google.cloud.spark.bigquery.SparkBigQueryConfig

1 error
        at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
        at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097)
        at com.google.cloud.spark.bigquery.repackaged.com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:76)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:47)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:354)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:326)
        at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:308)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:308)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:240)
~~~

### second try
```scala
var bigQueryOption = new HashMap<String, String>() {{
put("credentials", credentials);
put("viewsEnabled", "true");
put("query", "SELECT * FROM `project.dataset.table` LIMIT 5");
}}

var dfReader = spark.read
      .options(bigQueryOption)
      .format('bigquery')

val df = dfReader
      .load()
      .cache()
```
but doesn't work with same error.

### third try
```scala
var bigQueryOption = new HashMap<String, String>() {{
put("credentials", credentials);
put("viewsEnabled", "true");
put("query", "SELECT * FROM `project.dataset.table` LIMIT 5");
}}

var dfReader = spark.read
      .options(bigQueryOption)
      .format('bigquery')

val df = dfReader
      .load("project.dataset.table")
      .cache()
```
This code works same as 
```
spark.read.format('bigquery').load('project.dataset.table').cache()
```
which is no query option.

Is it related on java or scala version?
I think exception is from `parseTableId` function (https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/connector/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java#L116)

I checked that "project.dataset.table" matched to `QUALIFIED_TABLE_REGEX `(https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/connector/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java#L56)
but there's no problem.

i've seen the issue(https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/330) that solved with using dataproc image 1.4 But i don't want to downgrade image..

**Comment by davidrabinowitz** [comment]
Please add the `materializationDataset` option (see [here](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#reading-data-from-a-bigquery-query)), make sure that the use has write permission to this dataset

We will fix the error message

**Comment by kumgaurav** [comment]
@davidrabinowitz, Hi David, its a valid bug, please do not close it. For Example - our organization policy in production is not write by individuals. But we do query our data for quick validation and much more. The newer version which is forcing to set  materializationDataset is not allowing us to query as I do not have any dataset with write access in production.

**Comment by davidrabinowitz** [comment]
Reading from queries require the results to be materialized before the spark could actually read them, as stated in the documentation. Unfortunately there is no workaround this (unless you are using BigQuery's `query` API, but then you are limited into a single thread read. If this case is relevant for you, please check BigQuery's JDBC driver for easier integration with spark.

My suggestion is to work with the production owners to create a special dataset (can be in a different project as well) that will serve as a "temp" dataset for this purpose.

**Comment by kumgaurav** [comment]
Our environments are secured by VPC firewall which does not allow cross project access. I will give a try for jdbc big query spark api. thank you for quick response. Will not get into technical implementation but ideally I should have a way to query using connector if I have read permission to schema(For example - I can query table without having write access to any dataset). May be not now, but consider this as future enhancement.

**Comment by tav1nald3rs0n** [comment]
Hi @davidrabinowitz, so you mean Beam/Dataflow `BigQueryIO.readTableRows()` was also forced to implement the read function like you said, limited by single thread read?
