### ISSUE TITLE
avro.shaded not in fatJar causing java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by rnonnon** [GoogleCloudDataproc/spark-bigquery-connector#393]
Hi,

I'm using spark-bigquery-with-dependencies 0.20.0 and facing a 
```java
 java.lang.NoClassDefFoundError: com/google/cloud/spark/bigquery/repackaged/avro/shaded/com/google/common/base/Preconditions
```
When calling com.google.cloud.spark.bigquery.SchemaConverters#toBigQuerySchema

It seems this class does an import on `avro.shaded.com.google.common.base.Preconditions`
But `avro.shaded` is not included into the FatJar.

**If my searches are fine :**
`org.apache.avro` comes with `hadoop-common` itselft coming with `beam-sdks-java-io-hadoop-common` but as a **provided dependency**. This is the reason why it's not embedded into the fatJar. 

To fix the issue I argue to replace com.google.cloud.spark.bigquery.SchemaConverters:18
`import avro.shaded.com.google.common.base.Preconditions;`
with
`import com.google.common.base.Preconditions;`

Thanks ;)

**Comment by davidrabinowitz** [comment]
Fixed by PR #394
