### ISSUE TITLE
Multiple "Successfully repaired" logs 

### ISSUE THREAD

**Issue by gnobre** [GoogleCloudDataproc/spark-bigquery-connector#415]
Hi, I'm getting flooded by GoogleCloudStorageFileSystem logs when running a Spark job on Dataproc:
 
`21/06/14 16:21:22 INFO com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem: Successfully repaired 'gs://.spark-bigquery-application_1623686036410_0001-94c32075-6b93-47d2-9196-e1dd06aefef2/' directory.`

Weirdly, these started to appear after I migrated from Spark 2.4.4 to Spark 3.1.2. The job is taken longer to complete, which I think is due to this repair process.

EDIT: I found this discussion about the same issue https://groups.google.com/g/cloud-dataproc-discuss/c/JKcimdnskJc

Setting `--properties=spark.hadoop.fs.gs.implicit.dir.repair.enable=false` fixes the issue.

**Comment by davidrabinowitz** [comment]
As mentioned in the thread, this is a trait of the GCS connector, and can be solved with the above setting.

Another option to overcome this is to use the DIRECT write method, which uses the BigQuery Storage write API and completely bypasses GCS.
