### ISSUE TITLE
PySpark to BigQuery timestamp: null values converted to 1970-01-01 00:00:00 UTC

### ISSUE THREAD

**Issue by vlad-ds** [GoogleCloudDataproc/spark-bigquery-connector#426]
I am loading a Spark table with some timestamp columns and dropping it in BigQuery. The conversion seems to work fine, except that every time the Spark timestamp column has a `null` value, it is saved as `1970-01-01 00:00:00` UTC in BigQuery. Is there a way to keep the nulls in the conversion?

**Comment by davidrabinowitz** [comment]
Can you please share the schema of the spark table and the BigQuery table? Are you writing the data to an existing table or create new one on the fly?
