### ISSUE TITLE
Is there a way to use pure Spark SQL to query BQ?

### ISSUE THREAD

**Issue by SanGreel** [GoogleCloudDataproc/spark-bigquery-connector#427]
It's [mentioned](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#reading-data-from-a-bigquery-table) that Python, Scala and Java can be used to read data from BQ. 
Is there an option to use only SparkSQL to do this task?

**Comment by davidrabinowitz** [comment]
Spark sql can read data from BigQuery tables like this:
```
CREATE or REPLACE GLOBAL TEMPORARY VIEW foo USING bigquery options (table 'dataset.table');
```

Reading an arbitrary query has not been tested yet but you can try to run the following:
```
CREATE or REPLACE GLOBAL TEMPORARY VIEW foo USING bigquery options (viewsEnabled 'true' materializationDataset 'DATASET' query 'SQL');

```

**Comment by SanGreel** [comment]
Thanks a lot for your help.
