### ISSUE TITLE
Connector fails with "java.lang.NoClassDefFoundError: org/apache/spark/sql/vectorized/ColumnVector" with spark 2.2

### ISSUE THREAD

**Issue by karantirthani** [GoogleCloudDataproc/spark-bigquery-connector#454]
We are connecting to BigQuery using spark from On-prem cluster which has the following versions:
Spark version 2.2.0.2.6.3.0-235
Using Scala version 2.11.8, Java Version: 1.8.0_73
It is related to previous issue: https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/189#issuecomment-646710667

Also, bigquery connector we are using is spark-bigquery-with-dependencies_2.11:0.22.0.
Running via Java.

**Comment by davidrabinowitz** [comment]
Please set `readDataFormat` to AVRO

**Comment by karantirthani** [comment]
Thanks @davidrabinowitz 
Setting ```readDataFormat``` resolved the issue for me.
