### ISSUE TITLE
 Connector doesn’t correctly do filter pushdown on nested fields

### ISSUE THREAD

**Issue by michalmisiewicz** [GoogleCloudDataproc/spark-bigquery-connector#464]
## Tested on:
Dataproc version: 1.5-ubuntu18

## Problem
Spark BigQuery connector doesn’t correctly do filter pushdown on nested fields.

**Test case**
Spark job which loads data from partitioned BigQuery table with additional filters. Used filters:
* Partition filter
* tag.raw = ‘Listing’
* offer_listing.page = 1
* measures.ndcg.at = 60
* all_listing_offers_count > 0
* service_id in array

Table partition size: **24,9M** rows.

### Code

```python
some_df = (
    spark.read.format('bigquery')
        .option('table', 'some_private_table')
        .option('filter', (
            f"_PARTITIONTIME = '{args.date}' AND "
            "tag.raw = 'Listing' AND " 
            "offer_listing.page = 1 AND  "
            "measures.ndcg.at = 60 AND "  
            "all_listing_offers_count > 0 AND "
            "service_id in ('service_a', 'service_b')"
        ))
        .load()
)
```

### Log from connector:

>21/09/20 20:15:22 INFO com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation: Going to read from SOME_PRIVATE_TABLE columns=[_PARTITIONTIME, page_view, all_listing_offers_count, user, service_id, offer_listing, measures], filter='(_PARTITIONTIME = '2021-09-11' AND tag.raw = 'Listing' AND  offer_listing.page = 1 AND  measures.ndcg.at = 60 AND  all_listing_offers_count > 0 AND  service_id in ('service_a', 'service_b'))'

### Result
BigQuery query returned **15.4M** rows.

### Code

```python
some_df = (
    spark.read.format('bigquery')
        .option('table', 'some_private_table')
        .option('filter', f"_PARTITIONTIME = '{args.date}'")
        .where(f.col('tag.raw').isin('Listing'))
        .where(f.col('offer_listing.page') == 1)
        .where(f.col('measures.ndcg.at') == 60)
        .where(f.col('service_id').isin('service_a', 'service_b'))
        .where(f.col('all_listing_offers_count') > 0)
        .load()
)
```

In this case, the connector correctly built filters for **_PARTITIONTIME** column as well for **service_id** and **all_listing_offers_count**. The connector failed to create filters on nested fields, such as **measures**, **offer_listing**, and **tag**.

### Log from connector:

>21/09/20 20:21:38 INFO com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation: Going to read from SOME_PRIVATE_TABLE columns=[_PARTITIONTIME, tag, page_view, all_listing_offers_count, user, service_id, offer_listing, measures], filter='(_PARTITIONTIME = '2021-09-11') AND (\`all_listing_offers_count\` IS NOT NULL AND **\`measures\` IS NOT NULL** AND **\`offer_listing\` IS NOT NULL** AND \`service_id\` IN UNNEST(['service_a', 'service_b']) AND **\`tag\` IS NOT NULL** AND all_listing_offers_count > 0)'

### Result

BigQuery query returned **23.8M** rows.

## Summary

Relying on Spark BigQuery connector filter-pushdown functionality can lead to bigger resource consumption on Spark clusters. In the presented case the BigQuery connector loads additional **8.4M** records (**33%** table partition size), which could be discarded on the BigQuery level. 

At the scale of the organisation I work for, it is practically impossible to enforce one filtering method. BigQuery connector should load the same data no matter if using Spark DSL or manually specifying filter clauses. 

Filter-pushdown on nested fields for Parquet [was added](https://issues.apache.org/jira/browse/SPARK-17636) in Spark 3.0. It would be great if this functionality was also implemented in Spark BigQuery connector.

**Comment by davidrabinowitz** [comment]
Can you please share the log of the `DirectBigQueryRelation` logger?

**Comment by jaceklaskowski** [comment]
Isn't it what [README.md](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#predicate-filtering) says:

> There is a known issue in Spark that does not allow pushdown of filters on nested fields. For example - filters like address.city = "Sunnyvale" will not get pushdown to Bigquery.

**Comment by davidrabinowitz** [comment]
Thanks @jaceklaskowski, indeed there's an issue where spark does not provide us the full condition but just the `foo IS NOT NULL`. I want to verify this with the log
