### ISSUE TITLE
Support service account impersonating

### ISSUE THREAD

**Issue by 3cham** [GoogleCloudDataproc/spark-bigquery-connector#472]
Hi, is there anyway to read/write data from bigquery through service account impersonation. Currently I have to generate a short-live access token, which must be specified by dataframe read write operation (or am I doing wrong here?)

Thanks in advance.

**Comment by davidrabinowitz** [comment]
Can you please provide more context:
* Is it for a local run, on a cluster or on a notebook such as Jupyter/Zeppelin?
* How do you provide the credentials at the moment?

**Comment by chihhanyu** [comment]
Hope to see if there's other solution for this issue, we also have the same requirement for service account impersonating since our security policy does not allow us to export service account key file. 
We can only use personal account to get impersonated credential which is only supported by BigQuery client, so now our job is using BigQuery client and Storage client to connect BigQuery and GCS which is very inconvenient. :(

**Comment by davidrabinowitz** [comment]
Another way to set the credentials is using the `credentials` option, which let you serialize the key file's JSON to Base64 and use that. This way you don't need a key file and can take the data from any back-end storage at your choosing.

**Comment by mohammedkhursheed-nylas** [comment]
@davidrabinowitz observed an extra backslash is getting read as an escape sequence character, as below. 

`.option("credentialsFile", "gs://path/to/file.json") `

Error: 

```
Caused by: java.io.FileNotFoundException: gs:/path/to/file.json (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at com.google.cloud.bigquery.connector.common.BigQueryCredentialsSupplier.createCredentialsFromFile(BigQueryCredentialsSupplier.java:89)
        ... 39 more
```

**Comment by davidrabinowitz** [comment]
The credentials file need to be on the physically on each member of the cluster, it cannot be loaded from GCS
