### ISSUE TITLE
Add configuration option to use compression from the Read API for Arrow

### ISSUE THREAD

**Issue by emkornfield** [GoogleCloudDataproc/spark-bigquery-connector#481]
We should give users the option of using compression with Arrow.  The applicable API reference is [here](https://cloud.google.com/bigquery/docs/reference/storage/rpc/google.cloud.bigquery.storage.v1#google.cloud.bigquery.storage.v1.BigQueryRead.CreateReadSession).  For Java ZSTD is going to be the preferred method (LZ4 is very slow).

**Comment by davidrabinowitz** [comment]
Merged to master
