### ISSUE TITLE
BigQuery Connector should re-use BigQueryReadClient instances

### ISSUE THREAD

**Issue by emkornfield** [GoogleCloudDataproc/spark-bigquery-connector#482]
It looks like BigQueryReadClientFactory was created to avoid injecting singletons that are closeable.  This comes at the expense of needing to create new clients for every call to the BigQueryStorageService.

The [gRPC performance guide](https://grpc.io/docs/guides/performance/) recommends "Always re-use stubs and channels when possible."

I think a better solution here could be to either eliminate the factory class or keep the factory class and have it cache connection objects (per endpoint?) and make it closeable.  When the factory class is first created as a singleton register a new [SparkListener](http://spark.apache.org/docs/3.0.1/api/scala/org/apache/spark/scheduler/SparkListener.html#onApplicationEnd(applicationEnd:org.apache.spark.scheduler.SparkListenerApplicationEnd):Unit) that has an implementation for onApplicationEnd that will close either the connection or the factory.

**Comment by VinayLondhe14** [comment]
Closed by #495
