### ISSUE TITLE
Pyspark: Issue while inserting nested data into bigquery using aws glue job using google bigquery connector

### ISSUE THREAD

**Issue by AltafHussain4748** [GoogleCloudDataproc/spark-bigquery-connector#484]
I am having issue while inserting nested data into bigquery using aws glue job using google bigquery connector

Below is my bigquery table scheme

```
competition	FLOAT	NULLABLE	
categories	RECORD	REPEATED	
    id	INTEGER	REQUIRED	
```

And in custom transform of aws glue I am trying to send list of python dict to categories like below:
```
[{"id":10004},{"id":10009},{"id":10301}]
```

Schema of my dataframe is something like

```
root
 |-- categories: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- id: integer (nullable = false)
```

Please note that categories is one of dataframe column. 
Also Fields that are not nested they are inserted into bigquery.

Below is the Error:

```
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Provided Schema does not match Table ml-training-231514:data_for_seo_test.au_2021_11. Field categories.id is missing in new schema
```

**Comment by davidrabinowitz** [comment]
add `.option('intermediateFormat','orc')`
