### ISSUE TITLE
Error getting access token from metadata server in azure data brick

### ISSUE THREAD

**Issue by shubhamdangare-cldcvr** [GoogleCloudDataproc/spark-bigquery-connector#485]
Issue found getting error when trying to connect to bigquery via azure data bricks

solution 

There is problem while setting credential file, key file vin data bricks so i used 

libraryDependencies += "com.github.samelamin" %% "spark-bigquery" % "0.2.6"
to setup  in one notebook in scala

import com.samelamin.spark.bigquery._

// Set up GCP credentials
sqlContext.setGcpJsonKeyFile("<JSON_KEY_FILE>")

// Set up BigQuery project and bucket
sqlContext.setBigQueryProjectId("<BILLING_PROJECT>")
sqlContext.setBigQueryGcsBucket("<GCS_BUCKET>")

and we are able to connect to google correctly 
with other notebook via python

**Comment by davidrabinowitz** [comment]
Unfortunately you are referring to [another library](https://github.com/samelamin/spark-bigquery) an is free to open this issue there. As an alternative, you can use this library, which have [plenty of documentation](https://github.com/GoogleCloudDataproc/spark-bigquery-connector).
