### ISSUE TITLE
Quick question: How can I delete BigQuery partitions via this connector

### ISSUE THREAD

**Issue by timshen24** [GoogleCloudDataproc/spark-bigquery-connector#491]
With a BigQuery partitioned table, how can I delete certain partitions via this connector, in a quick and handy way?
Can we do that?
If not, can we overwrite some partitions while keep the rest of others intact? Thank you all

**Comment by davidrabinowitz** [comment]
You can overwrite a single partition in the following manner:
```
emptyDF.write.format("bigquery")
   .option("datePartition","20211128")
  .save("dataset.table")
```
Notice that the data frame should have the same schema as the table.

Direct delete is not supported yet.

**Comment by timshen24** [comment]
Please don't close, how can I overwrite a ranges of partitions then?
