### ISSUE TITLE
Does Spark Big Query Connector provides Atomicity 

### ISSUE THREAD

**Issue by ajaykamal3** [GoogleCloudDataproc/spark-bigquery-connector#498]
Info needed: I would like to know if the Spark Big Query connector provides Atomicity or not.

**Comment by davidrabinowitz** [comment]
Can you please elaborate? Do you refer to write atomicity? If this is the case, then at the moment writing is done by first writing to GCS, and then loading the data to BigQuery. Both actions are atomic in the sense that if the full write to GCS fail then Spark will fail the first step, and in the case that not all the data is properly loaded the load job will fail. If any of those fail, the write fails.

We are now introducing support for the BigQuery Storage Write API, which supports atomic writing directly to BigQuery, without the GCS part.

**Comment by ajaykamal3** [comment]
Thanks David for the quick response. Currently, I'm having a BigQuery table and I'm trying to write data (Insert Records in append mode) from 6 different processes at same time using the BigQuery Connector. So all the 6 operations will be have atomicity?
Also, Thank you for having the plan to introduce BigQuery Storage write API. Looking forward to use it

**Comment by davidrabinowitz** [comment]
You can simulate it by running 6 `bq load` in parallel. To the best of my knowledge it should be ok.

**Comment by ajaykamal3** [comment]
Thanks David.
