### ISSUE TITLE
Spark24 connector missing

### ISSUE THREAD

**Issue by Letreguilly** [GoogleCloudDataproc/spark-bigquery-connector#499]
The readme now reference a spark24 version of the connector with direct write mode : 
`https://github.com/GoogleCloudDataproc/spark-bigquery-connector#writing-data-to-bigquery`

However all the links of this versions are broken and it is not available on the maven central repository. It is just a typo or the connector is not (yet ?) available ?

Thank in advance for your answer.

**Comment by davidrabinowitz** [comment]
The connector will be available by the end of the week
