### ISSUE TITLE
Add timezone property to support TIME & DATETIME parsing

### ISSUE THREAD

**Issue by pmkc** [GoogleCloudDataproc/spark-bigquery-connector#5]

**Comment by isha97** [comment]
We support custom type converters https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/TypeConverter.java
which can be used.
Sample Type Converter : https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/spark-bigquery-dsv2/spark-3.4-bigquery-lib/src/main/java/com/google/cloud/spark/bigquery/v2/TimestampNTZTypeConverter.java
Spark 3.4 and above also support TimeStampNTZ.
