### ISSUE TITLE
Failed to find data source: bigquery

### ISSUE THREAD

**Issue by cvsanthosh** [GoogleCloudDataproc/spark-bigquery-connector#505]
I am trying read a Bigquery table onto a pyspark pandas dataframe. I am getting the error "Failed to find data source: bigquery.".  Code is below.

from pyspark.sql import SparkSession
spark = SparkSession.builder \
  .config("spark.jars", "gs://spark-lib/bigquery/spark-2.4-bigquery-latest.jar")\
  .getOrCreate()

table = "bigquery-public-data.samples.shakespeare"
df = spark.read.format("bigquery").option("table",table).load()
df.show()
df.printSchema()

I am using Jupyter Notebook Pyspark cluster on Google Cloud. I Guess need to import Bigquery library. Please let me know the fix for the same. Thanks.

**Comment by davidrabinowitz** [comment]
Pyspark notebook initializes the SparkSession for you in many cases, and after that you cannot add additional jars. Please try a python notebook instead.
