### ISSUE TITLE
Scala diffrent version with pyspark

### ISSUE THREAD

**Issue by sobelek** [GoogleCloudDataproc/spark-bigquery-connector#512]
So I have a dataproc cluster with spark 2.4.8 compiled using scala 2.12 where I run workload
I also do integration testing locally using pyspark 2.4.8 downloaded from PyPi which is compiled using scala 2.11.

I would like to have miminum diffrences between dataproc and testing enviroment.
Currently for dataproc i use `com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.23.1`
And for local testing `com.google.cloud.spark:spark-bigquery-with-dependencies_2.11:0.23.1`

And I wonder if  there can be any diffrences between using the two?
Also whats the diffrence betwen above versions and `com.google.cloud.spark:spark-2.4-bigquery:0.23.1-preview`?

**Comment by VinayLondhe14** [comment]
Thank you for your questions. 

The only difference between `com.google.cloud.spark:spark-bigquery-with-dependencies_2.11:0.23.1` and `com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.23.1` is that the former is a Scala 2.11 based connector, targeting Spark 2.3 and 2.4 using Scala 2.11 whereas the latter is a Scala 2.12 based connector, targeting Spark 2.4 and 3.x using Scala 2.12. There should not be any code differences between the 2 connectors.

`com.google.cloud.spark:spark-2.4-bigquery:0.23.1-preview` is a Java based connector targeting Spark 2.4 of all Scala versions built on the new Data Source APIs(Data Source API v2) of Spark. 

See https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/CONTRIBUTING.md for more details.

**Comment by sobelek** [comment]
Thank you for answer. Indeed Contributing page explains it a lot better. It wasn't obvious reading just README. Do you mind if I do a PR updating it in README?

**Comment by VinayLondhe14** [comment]
Sure! That sounds great. Thank you
