### ISSUE TITLE
Missing dataset is not properly handled

### ISSUE THREAD

**Issue by davidrabinowitz** [GoogleCloudDataproc/spark-bigquery-connector#517]
If you provide the materialization dataset that does not exist, the connector will try to use the dataset that is provided in the query. However, it always searches for it in the US region, so it cannot find it if it exists in a different region (or multi-region, e.g. EU). BigQuery then returns:
```
"message" : "Not found: Dataset <project_id>:<dataset_id> was not found in location US".
```

**Comment by isha97** [comment]
If the materialization dataset doesn't exist, the existing behavior is failing the operation.

**Comment by isha97** [comment]
Same as Issue #628
