### ISSUE TITLE
support direct write for Spark 3.x

### ISSUE THREAD

**Issue by kmook** [GoogleCloudDataproc/spark-bigquery-connector#520]
Hi.
currently, it seems only Spark 2.4 connector supports direct write using spark storage write API.
do you have plan to support direct write for Spark 3.x?
Thank you in advance.

**Comment by davidrabinowitz** [comment]
The work for supporting direct write on Spark 3.1 is being done these days. No release date yet.

**Comment by evgeniy-b** [comment]
Hi, are there any updates on this topic? Thanks.

**Comment by davidrabinowitz** [comment]
Thanks for your interest. We are working on it, but as the Spark internal API we use (the DataSource API) was changed significantly in Spark 3.x and was incorporated to the Catalog API. In addition, many of the internal flows are very different from Spark 2.4 to 3.x. As a result, this support is taking longer than expected, as we want to maintain backward compatibility.

**Comment by evgeniy-b** [comment]
Understood, thanks for the details 👍🏻
