### ISSUE TITLE
How to perform UPSERT using this Connector

### ISSUE THREAD

**Issue by saadatbhatti** [GoogleCloudDataproc/spark-bigquery-connector#527]
Can someone please suggest how to perform UPSERT using this Connector. Documentation doesn't say anything about that.

**Comment by davidrabinowitz** [comment]
Both BigQuery and Spark do not support `UPSERT` directly, however there is a workaround: You can save your dataframe to a staging table in BigQuery, and then issue a [BigQuery `MERGE`](https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#merge_statement) call. After this is done, delete the staging table.
