### ISSUE TITLE
Issue when writing dataframe to BigQuery table using connector (2.11-0.22.0)

### ISSUE THREAD

**Issue by fjho7** [GoogleCloudDataproc/spark-bigquery-connector#534]
Hi, I'm currently facing an issue when trying to write a Spark dataframe to BigQuery. I'm getting a `Temporary or persistent GCS bucket must be informed.` error, which is coming from BigQueryWriteHelper.scala (line 60). I'm getting this even when I specify the parameter `temporaryGcsBucket` to Spark context.

This is being executed in RStudio which is deployed on a GKE cluster in GCP. We are using `sparklyr` library and Livy to connect to a Dataproc cluster through `spark_connect`. BigQuery connector is being set on Spark configuration through `spark.jars` parameter as well as `temporaryGcsBucket `parameter, these are being set on a configuration list which is being passed to `spark_connection` as a parameter. 
Example:

`config=c(config,list("spark.jars" = "gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.11-0.22.0.jar"
                     ,"temporaryGcsBucket" = "my_bucket"
))`

`spark_connect(master = paste("https://", "<dataproc_vm_name>", sep=""), method = "livy", config = config, version = "2.4.8")
`

Versions in use:
Sparklyr = 1.7.1
Spark = 2.4.8
Scala = 2.11
Spark-BigQuery Connector: 0.22.0

**Comment by VinayLondhe14** [comment]
@fjho7 Thank you for submitting this issue.

Since you are passing this config from outside the Spark code, can you try using `spark.datasource.bigquery.temporaryGcsBucket="my_bucket"` instead of  `"temporaryGcsBucket" = "my_bucket"`?

**Comment by fjho7** [comment]
Thanks @VinayLondhe14!!! It worked like a charm :) 

Closing the issue.
