### ISSUE TITLE
BigNumeric support - python zip file not available on GCS

### ISSUE THREAD

**Issue by t-zaton** [GoogleCloudDataproc/spark-bigquery-connector#539]
Hi, in the repo readme file: https://github.com/GoogleCloudDataproc/spark-bigquery-connector#bignumeric-support it is mentioned that a zip archive needs to be added in Spark to be able to use the BigNumeric datatype:

```
# use appropriate version for jar depending on the scala version
pyspark --jars gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.11-0.23.2.jar
  --py-files gs://spark-lib/bigquery/spark-bigquery-support-0.23.2.zip
  --files gs://spark-lib/bigquery/spark-bigquery-support-0.23.2.zip
```

When I check in the GCS location, the zip file **gs://spark-lib/bigquery/spark-bigquery-support-0.23.2.zip** (or any other version) is not there - only jar files. Can you please upload the zip file?

**Comment by davidrabinowitz** [comment]
Thanks for raising the issue. 
```
$ gsutil ls gs://spark-lib/bigquery/ | grep zip
gs://spark-lib/bigquery/spark-bigquery-support-0.23.0.zip
gs://spark-lib/bigquery/spark-bigquery-support-0.23.1.zip
gs://spark-lib/bigquery/spark-bigquery-support-0.23.2.zip
```
