### ISSUE TITLE
Trying to load data from BigQuery to Spark Dataframe using query option

### ISSUE THREAD

**Issue by akashgangulyhf** [GoogleCloudDataproc/spark-bigquery-connector#543]
When i execute the following code, I expect the filter pushdown to work.
```
reader = self.spark.read.format("bigquery") \
                .option('parentProject', self.project_id) \
                .option('viewsEnabled', True) \
                .option("materializationDataset", "tmp") \
                .option("query", f"select * from `{table_id}`")\
                .option("filter", "CAST(`_TABLE_SUFFIX` AS STRING) = '20170405'")
```

But instead I get an error
Caused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: Row filter for bigquery-rollup.tmp._bqc_c372ae3bcf3a46019600500ebacdf15d is **invalid**. Filter is '(CAST(`_TABLE_SUFFIX` AS STRING) = '20170405')'

When I run the same without operation without "query" option, it works
```
reader = self.spark.read \
                .format('bigquery') \
                .option('parentProject', self.project_id) \
                .option('dataset', self.dataset_id) \
                .option('table', self.table_id) \
                .option('filter', "CAST(`_TABLE_SUFFIX` AS STRING) = '20170405'")
```

Don't you have support for filters in query based read? Please suggest. Thanks.

**Comment by davidrabinowitz** [comment]
My guess is that you are reading from a table with a dated suffix as way of partitioning. When loading from query you actually run the query on BigQuery and the materialized result is save in a temporary table (`bigquery-rollup.tmp._bqc_c372ae3bcf3a46019600500ebacdf15d` in our case), which you cannot use the filter on it.

As an alternative, you can combine the query and the filter:
```
reader = self.spark.read.format("bigquery") \
                .option('parentProject', self.project_id) \
                .option('viewsEnabled', True) \
                .option("materializationDataset", "tmp") \
                .load(f"SELECT * FROM `{table_id}` WHERE CAST(`_TABLE_SUFFIX` AS STRING) = '20170405'")
```

**Comment by akashgangulyhf** [comment]
Okay, great. This makes sense. So for non pseudo partition column, I can use the filter option even after the query option right?

**Comment by akashgangulyhf** [comment]
Also, how long will the data in materializationDataset stay? Is there an auto purge mechanism?

**Comment by davidrabinowitz** [comment]
You can use the filter option, but it means that the materialized table may be larger and scan more data, which will incur higher BigQuery cost.

The tables are deleted once the application is terminated, but as a percussion (e.g. in case of application crash) they have a TTL of 24 hours and then BigQuery deletes them.

**Comment by akashgangulyhf** [comment]
Thanks for all the info. Was really very helpful. Have a good one.
