### ISSUE TITLE
How to handle schema change in Bigquery connector

### ISSUE THREAD

**Issue by ajaykamal3** [GoogleCloudDataproc/spark-bigquery-connector#549]
I'm having a big query table for which i'm **appending data** after processing it using spark bigquery connector. If i have a new column in the spark dataframe, I want that column to get created and insert the data in the big query table instead of an error for schema mismatch. How can I do this? Kindly let me know the solution for this problem (with sample code if possible).

**Comment by xneg** [comment]
I've just used approach from [this issue](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/287):
`.option("allowFieldAddition", "true")`
and it added new fields for me without problems.
