### ISSUE TITLE
Passing specific formatOptions to LoadJob dans BigQuery

### ISSUE THREAD

**Issue by walmaaoui** [GoogleCloudDataproc/spark-bigquery-connector#555]
Is there any current way to pass additional properties to the load job? 

I am interested in passing [enableListInference](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#ParquetOptions)  as `parquetOptions` to the load job into BQ. But the approach could be generalised to any `formatOptions` or even to any [additional property](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfigurationLoad) of the lodJob

**Comment by isha97** [comment]
`enableListInference` property can be specified.
Please elaborate on which options would you like to be supported and the usecases.
