### ISSUE TITLE
Temp table costing on Query Result Write?

### ISSUE THREAD

**Issue by akashgangulyhf** [GoogleCloudDataproc/spark-bigquery-connector#574]
Hi, from the README file, I can see it is mentioned the following: 
Important: This feature is implemented by running the query on BigQuery and saving the result into a temporary table, of which Spark will read the results from. This may add additional costs on your BigQuery account.

But BigQuery documentation says "You are not charged for storing temporary tables" https://cloud.google.com/bigquery/docs/writing-results#:~:text=You%20are%20not%20charged%20for%20storing%20temporary%20tables

Can you explain what exactly is the cost model when a query is executed in BigQuery?

**Comment by davidrabinowitz** [comment]
The connector cannot create a temporary table in the sense that `CREATE TEMP TABLE` creates. All the tables it creates are regular BigQuery tables. In the above case, we need temporary place to store the data, and it is deleted immediately as it is no longer needed. However, from the BigQuery perspective, this is a regular table and is billed accordingly.
