### ISSUE TITLE
What API does the "indirect write" use and how is it compared to the direct API?

### ISSUE THREAD

**Issue by jiayue-zhang** [GoogleCloudDataproc/spark-bigquery-connector#585]
I understand that the direct API uses the BigQuery Storage Write API. What about the indirect API? What mechanism does it load the data from GCS to BigQuery? Is there a BQ load job? I didn't find any such BQ jobs in my Google console.
How does the indirect write compare to direct write, in real-timeliness, price, fault-tolerance(delivery semantics) and restrictions(quota limits)?

**Comment by davidrabinowitz** [comment]
Yes, indirect writes first write the data to GCS, and then trigger a BigQuery load job. 

Indirect is slower due to the nature of operation. Direct write of large datasets may need to update the quota of concurrent write streams.

**Comment by thirumalaics** [comment]
Will the batch dataframe written by direct method be stored in streaming buffer for a while? In other words, will the direct write be treated as streaming inserts? Which one is costlier out of direct and indirect? @davidrabinowitz

**Comment by VIKCT001** [comment]
is there any parameter in the bq load jobs which can suggest that we are using direct or indirect write method?

**Comment by davidrabinowitz** [comment]
DIRECT means using the BigQuery Storage Write API. INDIRECT means writing to GCS first, and then triggering a BigQuery Load job.

If there are further issues, please open another issue or contact the team via your account manager.

**Comment by VIKCT001** [comment]
Thanks for the updates. will DIRECT method supports writing to the bq partitioned tables as well.
