### ISSUE TITLE
Allow users to disable cache when loading data via SQL query

### ISSUE THREAD

**Issue by michalmisiewicz** [GoogleCloudDataproc/spark-bigquery-connector#593]
Currently connector caches all SQL queries. Cache can be problematic during integration tests. Cache expiration is controlled by `cacheExpirationTimeInMinutes` parameter. Currently there is no option to disable cache as connector [verifies](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java#L369) if `cacheExpirationTimeInMinutes` is greater than 0, despite Guava CacheBuilder.expireAfterWrite [allows](https://javadoc.io/static/com.google.guava/guava/31.1-jre/com/google/common/cache/CacheBuilder.html#expireAfterWrite(java.time.Duration) to disable cache by passing 0 as duration. Connector should allow to disable cache.

**Comment by VinayLondhe14** [comment]
@michalmisiewicz Thank you for raising this issue. We will take a look

**Comment by miillo** [comment]
Hi, 
When can we expect release of @suryasoma change? With **0.24.2** release and setting **cacheExpirationTimeInMinutes** parameter to 0 I still get error:
```
Cause: java.lang.IllegalArgumentException: cacheExpirationTimeInMinutes must have a positive value, the configured value is 0
[info]   at com.google.cloud.spark.bigquery.SparkBigQueryConfig.from(SparkBigQueryConfig.java:370)
```

**Comment by suryasoma** [comment]
Hey @miillo,

You can find the fix in next release.

Thanks,
Surya Soma

**Comment by PatrykGala** [comment]
Hi, 
A few weeks ago I reported the same issue: https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/452 and the method for clear was added:
https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/df2cc13806d78b5485d165e2ece658928c883331/connector/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java#L303-L306
