### ISSUE TITLE
The writeMethod `direct` flag does not perform streming insert into BigQuery.

### ISSUE THREAD

**Issue by austynherman** [GoogleCloudDataproc/spark-bigquery-connector#595]
Setting `writeMethod` to `direct` appears to have no effect. 

The following code:
```
df.write.format('bigquery') \
          .option("writeMethod", "direct") \
          .save(f"{self.gcloud_project}:{dataset}.{table}")
```

Produces the following error while attempting to write to the table:

```
pyspark.sql.utils.IllegalArgumentException: Either temporary or persistent GCS bucket must be set
```

Directly follwoing the above error the code was modified to the following:
```
        df.write.format('bigquery') \
          .option("temporaryGcsBucket", self.gcs_bucket) \
          .option("writeMethod", "direct") \
          .save(f"{self.gcloud_project}:{dataset}.{table}")
```

With the `temporaryGcsBucket` set, the write operation proceeded to write temporary `parquet` (default) files to the temporary gcs location rather than performing a streaming insert.

##### Connector Jars
gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar
gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.24.2.jar \

##### Pyspark Version
2.4.0

**Comment by davidrabinowitz** [comment]
As written at the [documentation](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#direct-write-using-the-bigquery-storage-write-api) this is supported only by the spark-2.4-bigquery connector. We are working on adding support for spark 3.x as well.
