### ISSUE TITLE
loadDataIntoTable fails with NullPointerException if create job fails

### ISSUE THREAD

**Issue by irajhedayati** [GoogleCloudDataproc/spark-bigquery-connector#597]
When trying to write to a BigQuery table, if creating the job fails in `com.google.cloud.bigquery.connector.common.BigQueryClient#loadDataIntoTable` method, it will go to the `catch` clause which only takes into account the exceptions of the write operation. It tries to get the job ID while the job is `null` and causes a `NullPointerException` that hides the actual error (in my case it was due to the fact that the destination table did not exist and my account didn't have permission to create it).

Right now, when it fails, it actually prints in the output which doesn't say what was the actual cause

```java
Caused by: java.lang.NullPointerException
	at com.google.cloud.bigquery.connector.common.BigQueryClient.loadDataIntoTable(BigQueryClient.java:532)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:87)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:66)
	... 36 more
```

The actual message is 

```
Access Denied: Dataset ***:***: Permission bigquery.tables.create denied on dataset ***:*** (or it may not exist).
```

**Comment by irajhedayati** [comment]
I created this PR to review please https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/598

**Comment by VinayLondhe14** [comment]
@irajhedayati Thank you for creating the issue as well as the fix!
