### ISSUE TITLE
What's the meaning of the `_bqc_` prefix table?

### ISSUE THREAD

**Issue by diggzhang** [GoogleCloudDataproc/spark-bigquery-connector#607]
driver version:  ` implementation 'com.google.cloud.spark:spark-bigquery-with-dependencies_2.11:0.23.2'`

The logic of my query is very simple, I used `com.google.cloud.spark.bigquery` driver to made a simple table query:

```scala 
    val query = "select * from XXXXX"

    val options = Map(
      "viewsEnabled" -> "true",
      "materializationDataset" -> config.dataset,
      "parentProject" -> config.project,
      "credentials" -> config.credentials,
      "query" -> query
    )

    spark.read
      .format("com.google.cloud.spark.bigquery")
      .options(options)
      .load()
```

Each time the query is executed, a new table is created, the new table prefix is `_bqc_`, full name example: `_bqc_8930944ac1044f908c0598c79a2XXXXX `.

Why is this table created？Is this possible not create it?

**Comment by VinayLondhe14** [comment]
@diggzhang Thank you for the question.

When you submit a BigQuery query, the connector stores the result in a temporary table and then reads from this table in the Spark executors. The table name is generated dynamically with the `bqc` prefix concatenated with a UUID as seen [here](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java#L295). Note that the expiration time of this temporary table can be controlled with the `materializationExpirationTimeInMinutes` parameter. 

This temporary table has to be created if you are issuing a BigQuery query directly using the `query` parameter.

The documentation [here](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#reading-data-from-a-bigquery-query) provides more information.
