### ISSUE TITLE
Is there a way to change the name of folders created on the bucket?

### ISSUE THREAD

**Issue by Suzy12** [GoogleCloudDataproc/spark-bigquery-connector#609]
Hi! I am using a gcs bucket to write into a partitioned table. I want to track down the data written by the connector since i'm having duplicated data, and for this, i'm trying to look at the data written into the gcs bucket. 
But the folders created by the connector into the bucket are named randomly (correct me if i'm wrong) and don't have a creation date (unless you select the folder and look at the files). So folders are not in a particular order.  And there's a LOT of folders since i'm streaming data. So, is there a way I can customize the name of the gcs bucket folders created by the connector?

**Comment by davidrabinowitz** [comment]
If you use batch writes, then you can use the persistentGcsBucket and persistentGcsPath options - those give you the control of where the temporary data is written, and they are not cleaned up by the end of the log job - notice you will have to clean those yourself or use the GCS lifecycle to delete them (after 24 hours for example)

As you use streaming this makes it more difficult as each micro-batch needs its own directory. You can however use the [Cloud Functions GCS trigger](https://cloud.google.com/functions/docs/calling/storage) to trigger a cloud function that will track the intermediate data
