### ISSUE TITLE
Uneven distribution of data in partitions

### ISSUE THREAD

**Issue by s0nskar** [GoogleCloudDataproc/spark-bigquery-connector#61]
We were trying to run a count query on a public bigquery dataset (with 65GB data / 185,666,648 rows) with this connector. And noticed that initial tasks were taking around 1.5 min and later ones are taking only 0.3 sec.

After some digging what we found out that there was an uneven distribution of rows across that partitions. It divided the query into 140 tasks and out of 140 only initial 62 tasks got assigned some data, others were left empty.

Is this expected? If so, I think the expected behavior should be to equally distribute the tasks or create fewer partitions. I am attaching a snippet of my code. 

```scala
import com.google.cloud.spark.bigquery._

val df = spark.read
              .option("parallelism", "1024")
              .bigquery("bigquery-public-data:chicago_taxi_trips.taxi_trips")

val sizes = df.rdd.mapPartitions(iter => Array(iter.size).iterator, true).collect

>>> Output
sizes: Array[Int] = Array(2905482, 3286156, 2916555, 3249520, 3038311, 3177630, 3198400, 3472010, 3205490, 3225875, 3192130, 3188205, 3279867, 3200256, 3233956, 2865080, 3272523, 3201758, 3207450, 3165187, 3212764, 2837254, 3209174, 2881729, 3263254, 3295285, 3245724, 3209642, 3261901, 3470650, 3174603, 3228765, 2919202, 3269729, 3237928, 3259147, 3224187, 3309382, 3088440, 3215571, 3212322, 3200407, 3216581, 3192071, 3229153, 3227973, 3260958, 2882677, 2660676, 2872312, 3252960, 3219197, 2826124, 2564174, 2556998, 2593512, 1964467, 2166998, 2152987, 1284772, 1310224, 1522933, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...
```

**Comment by kmjung** [comment]
What version of the connector are you using? Can you share a read session ID?
