### ISSUE TITLE
Reading only requested number of partitions from BQ table doesn't work

### ISSUE THREAD

**Issue by JD-V** [GoogleCloudDataproc/spark-bigquery-connector#63]
I am trying to query table which is partitioned by date field. Like this,

```
val prog_logs = spark.read.format("bigquery")
        .option("table", "project1:dataset.table")
        .option("filter", " date between '2019-09-10' and  '2019-09-11' ")
        .load()
        .cache()
```

This is reading entire table instead of only '2019-09-10' and  '2019-09-11'  partitions.

**Comment by JD-V** [comment]
@pmkc I would really appreciate if anybody can take a look at this.

**Comment by pmkc** [comment]
@davidrabinowitz is the new maintainer. Though I think we will need to consult with BigQuery Storage devs.

I have successfully used _PARTITION_DATE like that in a filter before.

**Comment by kmjung** [comment]
@JD-V I'd like to figure out what filter is actually pushed down to the storage API here. Do you have the read session ID from this query, or can you get one from a repro?

**Comment by JD-V** [comment]
I got this from very recent run,
projects/mintreporting/locations/asia-southeast1/sessions/CAISCDlLRUpHSGlKGgJzZhoCc2k

@kmjung Let me know if this is helpful

**Comment by emkornfield** [comment]
Sorry for the late response but for proper push down in spark 2.4 I think you need:
 date between date('2019-09-10') and  date('2019-09-11') (i.e. explicitly cast values to date).

**Comment by jesuejunior** [comment]
> Sorry for the late response but for proper push down in spark 2.4 I think you need:
> date between date('2019-09-10') and date('2019-09-11') (i.e. explicitly cast values to date).

Did it work for someone?

I've to try and it always makes the table full scan.

Are there any tips to do it ?

**Comment by davidrabinowitz** [comment]
Can you please share a sample code? Also, can you please set the log level to debug and attach the output? I assume you use the latest version
