### ISSUE TITLE
StatusRuntimeException: RESOURCE_EXHAUSTED when loading data from bigquery to spark

### ISSUE THREAD

**Issue by kjoheyjo** [GoogleCloudDataproc/spark-bigquery-connector#671]
I am loading data from a view in bigquery with 1.3 billion rows. 

`sparkSession.conf.set("viewsEnabled", "true")

    val factEaEventDf = sparkSession.read.format("bigquery")
      .option("table", s"$dataset.$table")
      .option("filter", s"evnt_dt='$eventDate' AND evnt_hr=$eventHour")
      .load()
`

I am getting the following error after sometime and the job fails and exits
`com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: there was an error operating on 'projects/ccg24-hrzana-p-polestar/locations/us/sessions/CAISDGJIX0U2Y0NKU1h1RBoCb3YaAm9q/streams/CJQDGgJvdhoCb2ooAg': Concurrent stream usage exceeded.`

The same code has been working for a long time for higher loads as well.

full stack trace:

com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ResourceExhaustedException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: there was an error operating on 'projects/ccg24-hrzana-p-polestar/locations/us/sessions/CAISDGJIX0U2Y0NKU1h1RBoCb3YaAm9q/streams/CJQDGgJvdhoCb2ooAg': Concurrent stream usage exceeded.\tat com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:57)\tat com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)\tat com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)\tat com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.ExceptionResponseObserver.onErrorImpl(ExceptionResponseObserver.java:82)\tat com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)\tat com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:149)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\tat java.lang.Thread.run(Thread.java:748)\tSuppressed: java.lang.RuntimeException: Asynchronous task failed\t\tat com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.ServerStreamIterator.hasNext(ServerStreamIterator.java:105)\t\tat com.google.cloud.spark.bigquery.direct.ReadRowsIterator.hasNext(BigQueryRDD.scala:152)\t\tat scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)\t\tat org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)\t\tat org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)\t\tat org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)\t\tat org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$12$$anon$1.hasNext(WholeStageCodegenExec.scala:631)\t\tat scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)\t\tat scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)\t\tat org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:187)\t\tat org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)\t\tat org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)\t\tat org.apache.spark.scheduler.Task.run(Task.scala:109)\t\tat org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)\t\t... 3 moreCaused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: there was an error operating on 'projects/ccg24-hrzana-p-polestar/locations/us/sessions/CAISDGJIX0U2Y0NKU1h1RBoCb3YaAm9q/streams/CJQDGgJvdhoCb2ooAg': Concurrent stream usage exceeded.\tat com.google.cloud.spark.bigquery.repackaged.io.grpc.Status.asRuntimeException(Status.java:535)

**Comment by kmjung** [comment]
The read API is in the process of launching a new quota on concurrent `ReadRows` calls -- see https://cloud.google.com/bigquery/docs/release-notes#June_06_2022. Releases of the Spark/BQ connector starting with 0.23.0 will handle these errors gracefully without failing the Spark job, but this project appears to be using an older version of the connector (0.22.0). You can also request an increase in the limit for this project by filing a request with support.
