### ISSUE TITLE
value bigquery is not a member of org.apache.spark.sql.DataFrameReader

### ISSUE THREAD

**Issue by siddjain** [GoogleCloudDataproc/spark-bigquery-connector#681]
we are using these dependencies in our `build.sbt`:

```
scalaVersion := "2.12.16"

libraryDependencies ++= Seq(
	"org.apache.spark" %% "spark-sql" % "2.4.0",
	"com.google.cloud.spark" % "spark-2.4-bigquery" % "0.25.1-preview"
)
```

and have following code:

```
import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.functions._
import com.google.cloud.spark.bigquery._

object SimpleApp {
  def main(args: Array[String]) {
    val spark = SparkSession.builder.appName("Simple Application").config("spark.master", "local").getOrCreate()
    val df = spark.read.option("parentProject", "XXX").bigquery("bigquery-public-data.samples.shakespeare")
```

which gives this error:

```
[error] /Users/XXX/bigquery-scala2/SimpleApp.scala:14:76: value bigquery is not a member of org.apache.spark.sql.DataFrameReader
[error]     val df = spark.read.option("parentProject", "XXX").bigquery("bigquery-public-data.samples.shakespeare")
```

how can we fix this?

**Comment by davidrabinowitz** [comment]
This connector is written in Java only so it does not support Scala implicit imports yet. You can use the following equivalent code:
```
val df = spark.read.format("bigquery").option("parentProject", "XXX").load("bigquery-public-data.samples.shakespeare")
```

**Comment by siddjain** [comment]
thanks. I see there are 3 connectors listed in the `README.md`. is there a connector that you hope to converge to in the future? is there any work item on the roadmap to support writing directly to BQ (without uploading to GCS first) from the spark 2.12 connector? i thought that's the connector one should use as it uses a latter (more recent) version of spark compared to the other connectors. thanks for the clarifications.
