### ISSUE TITLE
Got session expired when using spark structured streaming

### ISSUE THREAD

**Issue by kitkit8120** [GoogleCloudDataproc/spark-bigquery-connector#684]
We use the dataproc to create a cloud cluster. 

Here is the bigquery connector version.
"bigquery-connector-version": "1.2.0",
"spark-bigquery-connector-version": "0.23.2"

We use spark structured streaming to read the Kafka data and join a table in Biqquery. Then save it to cloud storage.
The program was working at the beginning, however, it will throw a session expired error when running around 6 hours.

`
Caused by: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: FAILED_PRECONDITION: there was an error operating on 'projects/xxxxx/locations/us/sessions/CAISDEZfZDFIdTZLcjNiThoCanEaAml3/streams/GgJqcRoCaXcoAg': session expired at 2022-06-25T00:06:18+00:00
`

May I know how can solve this issue?

**Comment by kitkit8120** [comment]
The BigQuery Table will be truncated and inserted daily.
I already use the cache function after reading the table. But it is not working.
`
sql = f""" SELECT user_id as userId, all_client_id FROM {table_name} WHERE user_id is not null """
`
`
df = self.spark.read.format("bigquery").load(sql)
`
`
df = df.cache()
`

**Comment by davidrabinowitz** [comment]
@kitkit8120 please reopen if relevant

**Comment by arun-nemani** [comment]
Can we reopen this issue? I am facing the exact same error

**Comment by davidrabinowitz** [comment]
Hi @arun-nemani , please open a new issue with all the details

**Comment by caspherola** [comment]
Hi @kmjung  @davidrabinowitz we are facing same issue with spark structured streaming

1. spark-bigquery-with-dependencies_2.12_0.28.0
2. spark version -3.2.1

Out structured streaming jobs running continuously and its loads the data from bigquery table every 12 hrs and cache it. whenever it refresh the cache, job getting failed with session expired exception 

can you help on this?
Thanks in advance!

**Comment by davidrabinowitz** [comment]
@caspherola can you please open a new issue? Also notice that a ReadSession has a duration of 6 hours, after whihc you will need to re-read the data from BigQuery.
