### ISSUE TITLE
Does df.write.format("bigquery") in append mode works properly if the order of column changed in original bigquery table ? 



### ISSUE THREAD

**Issue by Rstar1998** [GoogleCloudDataproc/spark-bigquery-connector#719]
For example : my dataframe has columns in order [ A, C, B ] but the biguery has column in order of [ A,B,C]

**Comment by suryasoma** [comment]
Hey @Rstar1998, the ordering of the columns shouldn't matter even in case of append mode, the write should work

**Comment by Rstar1998** [comment]
Also do you have the mapping sheet for data types of spark dataframe to big query. Like what a data type (like int float ) from pyspark gets mapped to corresponding data type of big query.

**Comment by suryasoma** [comment]
Hey @Rstar1998, sorry for the delay in response. We do have a mapping from BigQuery to Spark https://github.com/GoogleCloudDataproc/spark-bigquery-connector#data-types. The reverse should be true for Spark to BQ.
Thanks

**Comment by suryasoma** [comment]
Closing this issue for now. you can re open if needed.
Thanks
