### ISSUE TITLE
Change the shaded jar name from classifier to a new artifact name

### ISSUE THREAD

**Issue by davidrabinowitz** [GoogleCloudDataproc/spark-bigquery-connector#72]
At the moment the shaded jar is published as a classifier on the original jar (such as com.google.cloud.spark.bigquery:spark-bigquery_2.11:shaded) but unfortunately spark does not permit the usage of a classifier.

It means that the shaded version should be deployed under another artifact name.

**Comment by bobingm** [comment]
I want to followup this issue. Any updates on this?

**Comment by davidrabinowitz** [comment]
I'm working on it, hope to release it soon

**Comment by davidrabinowitz** [comment]
`com.google.cloud.spark:spark-bigquery-with-dependencies_2.11:0.12.0-beta` and `com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.12.0-beta` are now available
