### ISSUE TITLE
How to fetch BQ job_id using Spark-BQ connector

### ISSUE THREAD

**Issue by ojalbhandarkar** [GoogleCloudDataproc/spark-bigquery-connector#726]
Hi Team,

We have requirement to connect view `{region_id}.INFORMATION_SCHEMA.JOBS` and fetch metadata of BQ we execute.
We require `job_id` to perform this operation. 

But I am not able to find how to fetch bq job_id using spark-bq connector.

I have tried using below mentioned jar but not able to find relevant information. 
 JAR-`gs://spark-lib/bigquery/spark-bigquery-latest.jar`

Can you please help me to guide how we can achieve this?

PFB code snippet for spark and BQ query I am trying :

```
SparkUtil.getSparkSession().read().format(BigQueryConstants.BIG_QUERY_FORMAT)
                .option(BigQueryConstants.QUERY, query)
                .option(BigQueryConstants.VIEWS_ENABLED, Boolean.TRUE.toString().toUpperCase(Locale.ENGLISH))
                .option(BigQueryConstants.MATERIALIZATION_DATASET, materializationDataset)
                .option(BigQueryConstants.MATERIALIZATION_PROJECT, materializationProject)
                .option(BigQueryConstants.MATERIALIZATION_EXPIRATION_TIME_IN_MINUTES,
                        materializationExpirationTimeInMinutes)
                .option(BigQueryConstants.PROJECT, projectId);
```
====

```
SELECT
  COLUMN_SELECTED
FROM
  {region}.INFORMATION_SCHEMA.JOBS
WHERE
  job_type ='QUERY'AND statement_type='SELECT'AND job_id='{my_job_id}'AND creation_time BETWEEN TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
  AND CURRENT_TIMESTAMP()
  AND end_time BETWEEN TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
  AND CURRENT_TIMESTAMP();
```

**Comment by davidrabinowitz** [comment]
Can you please share more details? Which Spark, Scala, Java and Dataproc image versions do you use? 

Also, do you have permissions to access the `INFORMATION_SCHEMA`? What is the error you get? Does this query work in the BigQuery console?

Last, can you please try the following query (notice the back-ticks around the table names)?
```
SELECT
  *
FROM
  `{region}.INFORMATION_SCHEMA.JOBS`
WHERE
  job_type ='QUERY'AND statement_type='SELECT'AND job_id='{my_job_id}'AND creation_time BETWEEN TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
  AND CURRENT_TIMESTAMP()
  AND end_time BETWEEN TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
  AND CURRENT_TIMESTAMP();
```

**Comment by ojalbhandarkar** [comment]
> Can you please share more details? Which Spark, Scala, Java and Dataproc image versions do you use?
> 
> Also, do you have permissions to access the `INFORMATION_SCHEMA`? What is the error you get? Does this query work in the BigQuery console?
> 
> Last, can you please try the following query (notice the back-ticks around the table names)?
> 
> ```
> SELECT
>   *
> FROM
>   `{region}.INFORMATION_SCHEMA.JOBS`
> WHERE
>   job_type ='QUERY'AND statement_type='SELECT'AND job_id='{my_job_id}'AND creation_time BETWEEN TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
>   AND CURRENT_TIMESTAMP()
>   AND end_time BETWEEN TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
>   AND CURRENT_TIMESTAMP();
> ```

==============
Hi @davidrabinowitz ,

Thanks for the reply.

1. Spark- 2.4.3
2. DataProc-global/images/pp-dataproc-1-4-80-ubuntu18-548
3. Java- 8

- Yes, I have access to INFORMATION_SCHEMA

- I have ran provided query giving result as expected similar to the query I posted in question. 


Just to add more We are trying to replicate below mentioned Job_uuid assignment to the query we will be execution in spark-job before execution via spark-bq connector jar so that later we should be able to fetch metadata using same Job_uuid :

https://cloud.google.com/bigquery/docs/samples/bigquery-create-job#bigquery_create_job-java:~:text=JobId%20jobId%20%3D%20JobId.newBuilder().setLocation(%22us%22).setJob(jobName).build()%3B

**Comment by isha97** [comment]
The Bq Job Id is now available in the info logs from connector version 0.35.0 onwards.
Reference : https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/20062042e29f282d9fce25d4617797c64ba22dfb/bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java#L914
