### ISSUE TITLE
Spark 3.3 support

### ISSUE THREAD

**Issue by o-shevchenko** [GoogleCloudDataproc/spark-bigquery-connector#731]
We would like to use BigQuery connector with Spark 3.3 and Scala 2.13.
Could you share a road map to understand your plans for such support?
Thanks!

**Comment by davidrabinowitz** [comment]
Thanks for your interest! We have started to work on it, and hope to release it in a few weeks.

**Comment by davidrabinowitz** [comment]
The connector have support for Scala 2.13 and Spark 3.3
