### ISSUE TITLE
Return the same temp 'bqc' table when read a same BigQuery twice.  BigQueryClient.class line 275 (TableInfo)destinationTableCache.get()

### ISSUE THREAD

**Issue by bigcaiyujie** [GoogleCloudDataproc/spark-bigquery-connector#735]
Hi, i tried to read a BigQuery table with query and do some transformation and then write back to the same table, and then do the process(read transform write) again in a spark application. All the BigQuery table is same.
Issue is i found out the data in the second read is original data, it is not the result what i write in first time.

Here is code:
```
    sparkSession.conf.set("viewsEnabled", "true")
    sparkSession.conf.set("materializationProject", projectName.getOrElse("pypl-edw"))
    sparkSession.conf.set("materializationDataset", materializationDataset.getOrElse("pp_scratch"))
    val inputDf1 = sparkSession.read.format(Constants.BIGQUERY).load("select * from pypl-edw.pp_scratch.TestData")
    inputDf1.createOrReplaceTempView("input1")
    //Double the data
    val union1 = sparkSession.sql("select * from input1 union all select * from input1")
    union1.write.mode("overwrite").format(Constants.BIGQUERY).option(Constants.TABLE, "pypl-edw.pp_scratch.TestData").save()
    val inputDf2 = sparkSession.read.format(Constants.BIGQUERY).load("select * from pypl-edw.pp_scratch.TestData")
    inputDf2.show()
    //Double inputDF2 and write back to the same table
    ......
```

For DataFrame union1 i want to double the data, but inputDf2 is original data in table(Not double), it is not the result of union1.

I know it will read from temp(name with _bqc_ ) if query exist, then I see the SparkUI found it read same temp table in two job so cause the second input 'inputDf2' is original data. Here is screenshot for  two read query
![Screen Shot 2022-08-11 at 10 15 53 AM](https://user-images.githubusercontent.com/18144459/184053893-3241f95a-acb2-4c87-abd7-01ad85bb64f7.png)

![Screen Shot 2022-08-11 at 10 16 52 AM](https://user-images.githubusercontent.com/18144459/184053969-92b4d2a7-7100-45ae-8e1d-d29206065ec6.png)

we can see the temp table is same in the two query : pypl-edw.pp_scratch._bqc_b80acfb739f7417a970ae3e7d201f7ac

And then I debug from the spark-bigquery-connector code.
BigQueryClient line 275
`return (TableInfo)destinationTableCache.get(querySql, new BigQueryClient.DestinationTableBuilder(this, querySql, destinationTableId, expirationTimeInMinutes));`
In twice time it return the same TableInfo even the 'destinationTableId' is different.

I think it is may due to the querySql is same, but it is not expected, because destinationTableId is different.

It might be an issue.

Verion is spark-bigquery-with-dependencies_2.11-0.23.2.jar

**Comment by suryasoma** [comment]
Hey @bigcaiyujie,
The above code works if you replace sql in the initial or later load with `option("table", "pypl-edw.pp_scratch.TestData").load()`

`
    sparkSession.conf.set("viewsEnabled", "true")
    sparkSession.conf.set("materializationProject", projectName.getOrElse("pypl-edw"))
    sparkSession.conf.set("materializationDataset", materializationDataset.getOrElse("pp_scratch"))
    val inputDf1 = sparkSession.read.format(Constants.BIGQUERY)**.option("table", "pypl-edw.pp_scratch.TestData").load()**
    inputDf1.createOrReplaceTempView("input1")
    //Double the data
    val union1 = sparkSession.sql("select * from input1 union all select * from input1")
    union1.write.mode("overwrite").format(Constants.BIGQUERY).option(Constants.TABLE, "pypl-edw.pp_scratch.TestData").save()
    val inputDf2 = sparkSession.read.format(Constants.BIGQUERY).load("select * from pypl-edw.pp_scratch.TestData")
    inputDf2.show()
    //Double inputDF2 and write back to the same table
    ......
`

When you use a query to load the data, we create a materialized view which would be cached (for 24 hours default).
And when you try to read the table again using the same query, we use the cache.
I hope this solves your issue. If not can you please elaborate what exact use case are you trying to achieve.

**Comment by bigcaiyujie** [comment]
@suryasoma  Thanks for your response.

**Comment by bigcaiyujie** [comment]
HI @suryasoma or teams
Because our case will use same sql(the sql not only read *, it can have where or any clause) to read same table multiple time, for example read -> transform -> write -> read -> trans ->write -> read.

Do we have way to disable the function that use same sql to query the same table will always read from cache view.?
Or how can i get the materialized view name than i can delete the view to avoid read data from the view?

Thanks

**Comment by suryasoma** [comment]
Hey @bigcaiyujie, can you try setting the `cacheExpirationTimeInMinutes` to 0 and try the same?
```
    sparkSession.conf.set("viewsEnabled", "true")
    sparkSession.conf.set("materializationProject", projectName.getOrElse("pypl-edw"))
    sparkSession.conf.set("materializationDataset", materializationDataset.getOrElse("pp_scratch"))
    val inputDf1 = sparkSession.read.format(Constants.BIGQUERY).load("select * from pypl-edw.pp_scratch.TestData")
    inputDf1.createOrReplaceTempView("input1")
    sparkSession.conf.set("cacheExpirationTimeInMinutes", 0)
    //Double the data
    val union1 = sparkSession.sql("select * from input1 union all select * from input1")
    union1.write.mode("overwrite").format(Constants.BIGQUERY).option(Constants.TABLE, "pypl-edw.pp_scratch.TestData").save()
    val inputDf2 = sparkSession.read.format(Constants.BIGQUERY).load("select * from pypl-edw.pp_scratch.TestData")
    inputDf2.show()
    //Double inputDF2 and write back to the same table
    ......
```

**Comment by davidrabinowitz** [comment]
@bigcaiyujie The common case is that changed tables are not immediately read, and therefor the connector caches the query->temp table map in order to improve performance and avoid redundant use of BigQuery resources. You can disable this caching by adding the following line
```
spark.conf.set("cacheExpirationTimeInMinutes", "0")
```
