### ISSUE TITLE
parallelism setting in connector

### ISSUE THREAD

**Issue by cwang9208** [GoogleCloudDataproc/spark-bigquery-connector#774]
Hi @davidrabinowitz , I'm wondering why the [maxStreamCount](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreator.java#L124) is set to such a big number (DEFAULT_MAX_PARALLELISM = 20_000)?  It seems BigQuery Storage API can only support a maximum of 1,000 parallel read streams. How this maxStreamCount should be exactly set :( 

Thanks for your time in advance.

**Comment by cwang9208** [comment]
@davidrabinowitz I'm sorry to bother you, but I'm still confused by this number. Could you possibly give us a hint on this 20_000 number? Many thanks.

**Comment by davidrabinowitz** [comment]
The BigQuery Storage API control the parallelism of the data, and is limited only by the provided maxStreamCount. In order not to limit it unnecessarily, the default parallelism is high, and we increase it for very larger (>20,000 executors) clusters.
