### ISSUE TITLE
Write to a temporary table

### ISSUE THREAD

**Issue by elongl** [GoogleCloudDataproc/spark-bigquery-connector#784]
Hi! I'd like to be able to create and write to a temporary table.
Is there any way of doing so? I wasn't able to find one.
Thanks.

**Comment by davidrabinowitz** [comment]
Can you please elaborate? What do you mean by "writing to a temporary table"?

**Comment by SaadAmien20** [comment]
you can do that with workarounds like make expiry date for the table less time as much as possibl
or create task in a dag to delete the table using cloud composer after write to the table

**Comment by isha97** [comment]
Hi @elongl ,
 
Please open a new issue with all the details specifying,
1. Are you using connector to write to a new table using the write API?
2. What's the usecase of creating a temporary table?
