### ISSUE TITLE
How to avoid Spark BQ Connector to overwrite the target tables Schema

### ISSUE THREAD

**Issue by saadatbhatti** [GoogleCloudDataproc/spark-bigquery-connector#787]
When I writing my dataframe to BQ table it overwrites the schema if it's not matching with the schema of the target table. Is there anyway it fails and don't write if Schema doesn't match between Source dataframe and target BQ table 

Code I am using 

df.write \
         .format("bigquery") \
         .mode("overwrite") \
         .option("temporaryGcsBucket","myBucket") \
         .option("projectId","project1") \
         .option("parentProject", "project1") \
         .option("table","myDataset.myTable") \
         .option("SchemaUpdateOptions","false") \
         .save()

**Comment by davidrabinowitz** [comment]
Set the following options
```
.option("allowFieldAddition","false")
.option("allowFieldRelaxation","false")
```

**Comment by gmiano** [comment]
I am having a similar issue and the options proposed didn't work. Using the code snippet below on a table with all the columns REQUIRED, modified many of them to be NULLABLE.
`
            df_writer = (
                data.write.format(source="bigquery")
                .mode(saveMode="overwrite")
                .option(key="table", value=table_fullname)
                .option(key="createDisposition", value="CREATE_NEVER")
                .option(key="allowFieldAddition", value="false")
                .option(key="allowFieldRelaxation", value="false")
                .option(key="temporaryGcsBucket", value=self._config.get_config("temp_gcs_bucket"))
            )
`
