### ISSUE TITLE
Table access denied when running a simple serverless spark scala  job

### ISSUE THREAD

**Issue by lisageek** [GoogleCloudDataproc/spark-bigquery-connector#791]
Hello,

I am trying to run a simple spark scala code with serverless dataproc. The code just reads a sample data of a table on a dataset outside the project then writes the data in another table in the project.

I created a service account with BigQuery Data Editor, BigQuery Job User, Dataproc Worker and Storage Object Viewer roles.
The service account also have bigquery data viewer role on the dataset of the table to read.

When i run the batch, i get this error 

![image](https://user-images.githubusercontent.com/114701571/193347719-b9a8d709-1df5-45f5-aefb-4dc07b0ae40f.png)

And when i click on the link (second line on the first image) here is the link content : 

![image](https://user-images.githubusercontent.com/114701571/193347952-4659815a-0bac-4055-949b-5f27aee57b3c.png)

I dont get the error because i read many tutorials but none mention anything more than creating a service account with the right roles then submitting it to the batch while running.

Can you please help? i have been working on this for 3 days now without any success.
Thank you

**Comment by davidrabinowitz** [comment]
Does the serverless job uses this service account? How is it being run?

**Comment by lisageek** [comment]
hi @davidrabinowitz, thank you for stopping by.

yes the serverless job uses the service account. i am using the console where i need to provide a service account or the default one will be used.
I just run a test where i am reading then writing from the same project and it worked fine with the same service account.
So the problem might be the fact that i am reading from a another project and writing in mine (wherei am running the job).
Still, the service account is part of a  group that has been granted viewer role on the dataset to read.
And i can see that the service account has right to read the dataset.

**Comment by isha97** [comment]
Hi @lisageek are you still facing this issue?

**Comment by isha97** [comment]
Please reopen if you are still facing this issue.
