### ISSUE TITLE
Standalone apache spark read from BigQuery errors out when loading data.

### ISSUE THREAD

**Issue by Rakshitha-BR** [GoogleCloudDataproc/spark-bigquery-connector#793]
Hi ,
I am using standalone apache spark on prem to connect to GCP BQ.

the connection is working and shows schema details (scala)

when I try to print data it throws error
```
df.show()
df.collect

java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
```
spark env: 2.3.1 with scala 2.11
connector used: spark-bigquery-with-dependencies_2.11.

Same issue with public cloud as well , am i missing any dependencies?
```
scala> val df = spark.read.format("bigquery").option("parentProject", "bigquery-public-data").option("table", "bigquery-public-data:samples.shakespeare").load()
df: org.apache.spark.sql.DataFrame = [word: string, word_count: bigint ... 2 more fields]

scala> df.columns
   def columns: Array[String]

scala> df.show()
java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
  at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:246)
  at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
  at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
  at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$DefaultProtocolNegotiator.newNegotiator(NettyChannelBuilder.java:628)
  at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:530)
  at com.google.cloud.spark.bigquery.repackaged.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyChannelTransportFactoryBuilder.buildClientTransportFactory(NettyChannelBuilder.java:188)
```

**Comment by davidrabinowitz** [comment]
Which Java version and connector version are you using?

**Comment by vidhyaguru** [comment]
Hi David, I work alongside with Rakshitha on this effort, passing on java version and connection string details. Pls let know if you need any other info

 java version "1.8.0_181"
connection string & connector - ./spark-2.3.1-bin-hadoop2.7/bin/spark-submit --packages com.google.cloud.spark:spark-bigquery-with-dependencies_2.11:0.17.1

Thanks

**Comment by vidhyaguru** [comment]
same issue with .cache(), .save() 

py4j.protocol.Py4JJavaError: An error occurred while calling o55.cache.
: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available

py4j.protocol.Py4JJavaError: An error occurred while calling o60.save.

printSchema() --- seems to work

**Comment by vidhyaguru** [comment]
update- 
Added conscrypt-openjdk-2.5.2-linux-x86_64.jar to spark library and observe different error now.

py4j.protocol.Py4JJavaError: An error occurred while calling o55.showString.
: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.PermissionDeniedException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: PERMISSION_DENIED: request failed: the user does not have 'bigquery.readsessions.create' permission for 'projects/g

Will recheck on permissions, but not sure if jar is really mandate for gcp-bq connection

thanks

**Comment by vidhyaguru** [comment]
update -
1. After resolving permissions issue, show() and cache() are working fine with pyspark script
2. conscrypt-xx.x.x.jar seems to be mandate to resolve netty-tcnative issue

Thanks

**Comment by davidrabinowitz** [comment]
Thanks, I will check the conscrypt issue

**Comment by isha97** [comment]
@Rakshitha-BR Since this an old issue, checking if you are still facing it with the newer connector release?

**Comment by isha97** [comment]
Closing this issue, @Rakshitha-BR Please reopen if you are still facing this.
