### ISSUE TITLE
Add support for SYSTEM_TIME AS OF

### ISSUE THREAD

**Issue by gatesn** [GoogleCloudDataproc/spark-bigquery-connector#808]
It would be useful to be able to specify the system time in the Spark read request, similar to Delta, Iceberg, etc.

**Comment by isha97** [comment]
This will be available in the next release of the connector (0.39)
https://github.com/GoogleCloudDataproc/spark-bigquery-connector/commit/5691e246de43d91b6fccd7f3557ee16a22eefe86
It can be set using `snapshotTimeMillis` config.
