### ISSUE TITLE
clusteredFields option

### ISSUE THREAD

**Issue by Liftingthedata** [GoogleCloudDataproc/spark-bigquery-connector#809]
as per the README.md 
<img width="571" alt="image" src="https://user-images.githubusercontent.com/107177143/198298938-66d0a7c5-5e4c-43b8-97e4-e3741f88f3c5.png">

it states here a comma separated list as input. 
However, after much pain, and errors like
```
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: The field specified for clustering cannot be found in the schema. Invalid field: FOO
```
despite logging before the spark operation and being 100% sure that the field exists.
in the end, it turns out the fields need to be ALL in a singular string.

as so
```
.option("clusteredFields", "foo,bar,baz")
```

and not
```
.option("clusteredFields": ["foo", "bar", "baz"])
``` 

this does not require a fix, but I think a small clarification in the table in the readme would save others the time it took me to figure it out.

**Comment by suryasoma** [comment]
Thank you for identifying it. We will update the README. https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/817
Thank you
