### ISSUE TITLE
Provide doc on making the connector available in Jupyter

### ISSUE THREAD

**Issue by functicons** [GoogleCloudDataproc/spark-bigquery-connector#81]
This was asked on [SO](https://stackoverflow.com/questions/58769692/how-to-add-jar-dependency-to-dataproc-cluster-in-gcp).

**Comment by mkleinbort** [comment]
I was the one that asked the SO question, and the [notebook example](https://github.com/GoogleCloudPlatform/spark-bigquery-connector/blob/master/examples/notebooks/Top%20words%20in%20Shakespeare%20by%20work.ipynb) helped me fix the issue.

It's probably enough to add something like:

---

To run this from within a Dataproc Jupyter instance, be sure to start a Python notebook (Not PySpark) and run:

`from pyspark.sql import SparkSession

spark = SparkSession.builder \
  .appName('EDA')\
  .config('spark.jars', 'gs://spark-lib/bigquery/spark-bigquery-latest.jar') \
  .getOrCreate()`

You can then load data as a spark dataframe through 

`s = spark.read \
  .format('bigquery') \
  .option('table', '{_project_}.{_database_}.{_table_name_}') \
  .load()`

**Comment by mkleinbort** [comment]
That said, I'm seeing terrible performance when I try to run anything. 

Even something like 
```
s = spark.read.format('bigquery').option('table', 'my_project.all_data.stores').load()
s.take(1)
```
Is taking minutes... and then crashing. 

Also 

```
s.columns
```
results in a crash. 

That said, that's nothing to do with this issue. I'll do some googling and then ask again.

**Comment by mkleinbort** [comment]
A correction on the above, I ran

```
%%time
s.columns
```
And got an answer, but it took ~5minutes. This was not registered by the %%time command which clocked a wall time of 57.5 µs

**Comment by mkleinbort** [comment]
Just found that changing things to 

```
s = spark.read \
  .format('bigquery') \
  .option('project', '{_project_name_}') \
  .option('table', '{_database_}.{_table_name_}') \
  .load()
```

resolved many of my issues, though 

```
s.take(1) 
```

results in 

```
Server Connection Error
Invalid response: 504
```

**Comment by davidrabinowitz** [comment]
https://github.com/GoogleCloudDataproc/spark-bigquery-connector#using-in-jupyter-notebooks
