### ISSUE TITLE
Error reading BigQuery table in Dataframe created by Storage Write API

### ISSUE THREAD

**Issue by shayaansaiyed** [GoogleCloudDataproc/spark-bigquery-connector#828]
Hi folks, we are attempting to use the Spark BigQuery connector to read a BigQuery table into a Spark dataframe, but we are encountering the following error:
`com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: CreateReadSession is not supported for tables that ingest data using BigQuery Storage Write API with upsert streams.`

Is reading from tables created using the Storage Write API not supported, and are there any plans to add support for this?

**Comment by isha97** [comment]
Hi @shayaansaiyed this issue was fixed and this error should not show up now.
