### ISSUE TITLE
Allow BigQuery logs to be viewable in spark job Logs Explorer

### ISSUE THREAD

**Issue by piotr-jankowiak-allegro** [GoogleCloudDataproc/spark-bigquery-connector#829]
Currently when there is a BigQuery save error (for example we didn't provide enough columns) in spark job we need to look at 2 different logs to determine why the job failed:

- Spark job logs
- BigQuery logs

In an ideal world we should be able to look at only the spark job logs in order to debug. Would it be possible to have such a view in Logs Explorer?

**Comment by isha97** [comment]
Hi @piotr-jankowiak-allegro ,

I tried running a spark job trying to write a df with only one field to a table with two required fields and I got the error in the driver logs,
`IllegalArgumentException: BigQueryConnectorException$InvalidSchemaException: Destination table's schema is not compatible with dataframe's schema`

Please reopen the issue if you still can't see the BigQuery save errors.
