### ISSUE TITLE
Schema comparison is very strict in direct write mode

### ISSUE THREAD

**Issue by OELSJAN** [GoogleCloudDataproc/spark-bigquery-connector#830]
Hi all,

in want to write some data as Spark dataframe to a BigQuery table using the dirext write mode. After trying this, i got an `InvalidSchemaException` with the message `Destination table's schema is not compatible with dataframe's schema`.  I compared the dataframe schema and BigQuery table schema and could not find any difference.

After this i investigated the source code and found that there is a  comparison between the dataframe schema (converted to a big query schema) and the big schema of the target table:

https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/cbca61deeed755a3827381f55f0e6314133eef26/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataSourceWriterContext.java#L123-L133

In this comparison not only the column names and datatypes are compared, but also the description and many other fields:

https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/cbca61deeed755a3827381f55f0e6314133eef26/bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java#L261-L283

Why is that so? In my dataframe there is no such description in the schema. So i thought i can disable this check by setting the flag `enableModeCheckForSchemaFields` to `false`. But this flag only disables the comparison of nullable mode. 

Is it possible to design the comparison less strict in case you want to direct write some dataframe data to a BigQuery table? Because i thing it is not very helpful to compare the description before writing some data into  an existing table where the description is defined already.

**Comment by MBrugnaroto** [comment]
Any solution? I'm facing the same problem

**Comment by davidrabinowitz** [comment]
Can you please try the latest version (0.28.0)?

**Comment by MBrugnaroto** [comment]
I tested it with the new version and it worked!
Thank you very much @davidrabinowitz.

**Comment by davidrabinowitz** [comment]
I'm glad the problem is fixed, but the credit goes to @suryasoma :-)
