### ISSUE TITLE
Credentials configuration inconstent with GSC spark connector

### ISSUE THREAD

**Issue by vprus** [GoogleCloudDataproc/spark-bigquery-connector#88]
1. Read https://github.com/GoogleCloudPlatform/bigdata-interop/blob/master/gcs/INSTALL.md#configure-hadoop and then https://github.com/GoogleCloudPlatform/spark-bigquery-connector#how-do-i-authenticate-outside-gce--dataproc

2. Observed: GCS connector uses keys under google.cloud.auth prefix to configure credentials, for example `google.cloud.auth.service.account.json.keyfile`. When setting from Spark code, there's additional `spark.hadoop` prefix. BigQuery connector documentation say to do:
```spark.conf.set("credentialsFile", "</path/to/key/file>")```

3. Expected: since both projects aim to interop with Google services closely related to each other, I would expect that I can configure my spark session with a single set of keys. Furthermore, I would not expect to ever use unqualified `credentialsFile` - if everybody do that, sooner or later two packages would clash.

**Comment by FurcyPin** [comment]
+1, especially about point 3.

**Comment by davidrabinowitz** [comment]
Will be released in the next version.
