### ISSUE TITLE
Documentation Update : How to Write to JSON Column using Spark

### ISSUE THREAD

**Issue by sarath-mec** [GoogleCloudDataproc/spark-bigquery-connector#880]
According to [Readme -> Datatypes -> JSON](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#data-types)

*Spark has no JSON type. The values are read as String. In order to write JSON back to BigQuery, the following conditions are* ***REQUIRED***:
- *Use the INDIRECT write method*
- *Use the AVRO intermediate format*
- *The DataFrame field MUST be of type String and has an entry of* ***sqlType=JSON*** *in its metadata*

1. Is Writing to a BigQuery JSON Column in `INDIRECT write method` supported?
2. Can you give an example of `entry of sqlType=JSON in its metadata` ?

**Comment by davidrabinowitz** [comment]
1. Yes, `INDIRECT` is the only supported write method for now
2. See below: ```
scala> val f = StructField("json_field", DataTypes.StringType, true, Metadata.fromJson("""{"sqlType":"JSON"}"""))
f: org.apache.spark.sql.types.StructField = StructField(json_field,StringType,true)

scala> f.metadata
res0: org.apache.spark.sql.types.Metadata = {"sqlType":"JSON"}
```
