### ISSUE TITLE
Commit the data from GCS to BQ in multiple batches in BigQueryDirectDataWriterHelper

### ISSUE THREAD

**Issue by blackvvine** [GoogleCloudDataproc/spark-bigquery-connector#883]
In Apache Beam, the BigQuery writer commits the data separately for each partition of the Collection and [automatically avoids](https://github.com/apache/beam/blob/622f38088eebfa85a58982a2638f74295b320314/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WritePartition.java#L206
) hitting the BQ quotas.

In the Spark BQ connector, when the `BigQueryIndirectDataSourceWriterContext` is used, we commit the DataFrame's staged files from GCS to BigQuery all at once:

https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/5c0358ab330f3776ac160e0b65f1e57b8bafa3a9/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/BigQueryWriteHelper.java#L130

This forces a 15 TB limit when writing to BigQuery, due to the [Maximum size per load job](https://cloud.google.com/bigquery/quotas#:~:text=The%20total%20size%20for%20all%20of%20your%20CSV%2C%20JSON%2C%20Avro%2C%20Parquet%2C%20and%20ORC%20input%20files%20can%20be%20up%20to%2015%20TB.) quota. Even if the quota is extended, it can't be more than a few hundred terabytes which is too limiting for many users.

**Comment by davidrabinowitz** [comment]
A write to BigQuery is supposed to be atomic. Creating multiple load jobs will complicate achieving the atomicity (unless we use a temporary table). I'm closing this for now until there's a larger demand for >15TB writes
