### ISSUE TITLE
intermediateFormat option doesn't default to parquet, and can't be overriden

### ISSUE THREAD

**Issue by david-royo-db** [GoogleCloudDataproc/spark-bigquery-connector#899]
Hi,

I'm using spark-2.4-bigquery:0.28.0-preview in a Dataproc 1.5 cluster 

Everything works fine and the data is ingested in bigQuery but I decided to persist the ingested data in a bucket in parquet format with the following options

```scala
df.write
   .format("bigquery")
   .mode(SaveMode.Overwrite)
   .option("bigQueryJobLabel", "LoadJob")
   .option("createDisposition", "CREATE_NEVER")
   .option("persistentGcsBucket","$bucket")
   .option("persistentGcsPath",s"$prefix/$proj.$dataset.$table")
   .option("intermediateFormat", "parquet") //Todo: It is ignoring this and saving avro!
   .save(s"$proj.$dataset.$table")
```

My surprise here is always avro is used. The documentation says parquet is the default, but also if we explicitly say intermediateFormat = parquet it uses avro.

I've been checking the repo and found [something ](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/DataSourceVersion.java)very suspicious.
As far as I know the library I'm using uses Spark's V2 api, right?

Does it look like it's defaulting to avro in any case?

```java
public enum DataSourceVersion {
  V1,
  V2;

  public void updateOptionsMap(Map<String, String> optionsMap) {
    // these updates are v2 only
    if (this == V2) {
      // no need for the spark-avro module, we have an internal copy of avro
      optionsMap.put(SparkBigQueryConfig.VALIDATE_SPARK_AVRO_PARAM.toLowerCase(), "false");
      // DataSource V2 implementation uses Java only
      optionsMap.put(
          SparkBigQueryConfig.INTERMEDIATE_FORMAT_OPTION.toLowerCase(),
          SparkBigQueryConfig.IntermediateFormat.AVRO.toString());
    }
  }
}
```

**Comment by davidrabinowitz** [comment]
I'm sorry, it's a missed documentation. In the new connectors (all named `spark-X.Y-bigquery`) the only option for an intermediate format for INDIRECT writes is Avro. We will update the documentation to reflect this more clearly
