### ISSUE TITLE
Connector can silently fail to update table content

### ISSUE THREAD

**Issue by dtraviszus** [GoogleCloudDataproc/spark-bigquery-connector#909]
When using a service account that doesn't have the `BigQuery Job User` role on either the project or parent project, the connecter seems to silently fail to apply updates. The connector appears to apply updates, but no change is observed in the destination tables. 403s appear in the API Dashboard in GCP indicating that some kind of permissions error occurred.

The proposal here is that the connector should throw an exception when this occurs rather than fail silently.

This was observed while performing direct writes.

**Comment by vishalkarve15** [comment]
Can you please share what permissions this service account does have?

**Comment by vishalkarve15** [comment]
Please reopen with reproduction steps if you still see this issue.
