### ISSUE TITLE
How to get the cost of BQ query

### ISSUE THREAD

**Issue by waltyou** [GoogleCloudDataproc/spark-bigquery-connector#926]
I am using this library to reading data from a BigQuery query. But I notice this statement in README.md:
```
Important: This feature is implemented by running the query on BigQuery and saving the result into a temporary table, of which Spark will read the results from. This may add additional costs on your BigQuery account.
```

Do you know how to get the cost of the BQ query? Any way to find the job_id of that BQ query?

**Comment by isha97** [comment]
The job id is added as part of https://github.com/GoogleCloudDataproc/spark-bigquery-connector/commit/350d93e98156ce6434da3bdc27ccec8575ded79e
and is available in release 0.33.0 and onwards.
