### ISSUE TITLE
Cannot change destination table schema when in overwrite mode

### ISSUE THREAD

**Issue by mdesnoyer** [GoogleCloudDataproc/spark-bigquery-connector#929]
When in overwrite mode, I would expect that the schema for the destination table could be changed because we are overwriting the table. However, when I try to do that, the following error is thrown:

java.lang.IllegalArgumentException: com.google.cloud.bigquery.connector.common.BigQueryConnectorException$InvalidSchemaException: Destination table's schema is not compatible with dataframe's schema

Digging into the code base, it looks like it's happening because there's a schema check applied even if it's running in overwrite mode:
https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/5f83d7cefb473e6130765756f52f3f16d184f95d/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataSourceWriterContext.java#L132

Which is probably necessary because the overwrite mode is implemented using the MERGE DML:
https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/2420af5d644a37db0154966b1279749fe982af65/bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java#L199

Is there a reason not to use 

CREATE OR REPLACE TABLE dest COPY source 

and then skip the pre-schema check for overwrite mode?

**Comment by suryasoma** [comment]
Hey, overwrite here is to to overwrite the data in the table but not change the schema of the table. https://cloud.google.com/bigquery/docs/managing-table-data#append-overwrite

**Comment by mdesnoyer** [comment]
I see. So the spark interface is purely using the BigQuery streaming approach instead of query writes?

I just look at the UI and have three options:

- Write if empty
- Append to table
- Overwrite table

https://cloud.google.com/bigquery/docs/writing-results#console

and I thought the settings in this connector were equivalent. Now, I happened to be using the spark/DataProc job to rewrite a whole table so if I have the wrong semantics, that's on me and it's WAI. Some clearer documentation for the connector/dataproc settings would be useful though to help the reader realize that you're limited to streaming semantics.

**Comment by suryasoma** [comment]
Noted and thanks for the suggestion. Will update the documentation.
