### ISSUE TITLE
help: Writing data from databricks to google bigquery

### ISSUE THREAD

**Issue by jeeva-98** [GoogleCloudDataproc/spark-bigquery-connector#931]
I was trying to write dataframe which is created in databricks to bigquery. But i dont know how to configure it properly. Can u pls connect with me personally and teachme on this. From morning im stucking with this problem  Pls teach me from basic which help me to write data from databricks to big query. I can able to read using service account but not write (pls note access provided in service account for writing). Forsure i will write a whitepaper and post it here which help others. My email:jeeva.b.chn@gmailcom

**Comment by davidrabinowitz** [comment]
Please review the documentation at [How do I authenticate outside GCE / Dataproc?](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#how-do-i-authenticate-outside-gce--dataproc) and [Writing data to BigQuery](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#writing-data-to-bigquery).

For Databricks specific questions, please contact the Databricks support.

**Comment by jeeva-98** [comment]
Hi i m getting the following error after authenticating properly. Pls support 

AnalysisException: 
Multiple sources found for bigquery (com.google.cloud.spark.bigquery.BigQueryRelationProvider, com.google.cloud.spark.bigquery.v2.Spark33BigQueryTableProvider),
 please specify the fully qualified class name.
       
---------------------------------------------------------------------------
AnalysisException                         Traceback (most recent call last)
<command-2928375257944040> in <cell line: 2>()
      1 df1=spark.createDataFrame(data)
----> 2 df1.write.format("bigquery").option("credentialsfile","/tmp/big1.json").option("writeMethod", "direct").option("temporaryGcsBucket","brickser").mode("overwrite").save("phonic-aquifer-381208.iris.prediction")

/databricks/spark/python/pyspark/instrumentation_utils.py in wrapper(*args, **kwargs)
     46             start = time.perf_counter()
     47             try:
---> 48                 res = func(*args, **kwargs)
     49                 logger.log_success(
     50                     module_name, class_name, function_name, time.perf_counter() - start, signature

/databricks/spark/python/pyspark/sql/readwriter.py in save(self, path, format, mode, partitionBy, **options)
    966             self._jwrite.save()
    967         else:
--> 968             self._jwrite.save(path)
    969 
    970     @since(1.4)

**Comment by davidrabinowitz** [comment]
It seems that you have multiple connector jars in your classpath - one is spark-bigquery-with-dependencies_${scala.version}.jar, and the second is spark-3.3-bigquery.jar. Please remove one of them.

**Comment by jeeva-98** [comment]
No i m getting this error pls support
java.io.IOException: Error accessing gs://databricksbq123/.spark-bigquery-local-1679374135602-b77241b8-8e19-451e-87b3-81d8691c2f68
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-3174144640000276> in <cell line: 1>()
----> 1 df1.write.format("bigquery").option("credentialsfile",serviceac).option("writeMethod", "direct").option("temporarygcsBucket","databricksbq123").save("iris.table")

/databricks/spark/python/pyspark/instrumentation_utils.py in wrapper(*args, **kwargs)
     46             start = time.perf_counter()
     47             try:
---> 48                 res = func(*args, **kwargs)
     49                 logger.log_success(
     50                     module_name, class_name, function_name, time.perf_counter() - start, signature

/databricks/spark/python/pyspark/sql/readwriter.py in save(self, path, format, mode, partitionBy, **options)
    966             self._jwrite.save()
    967         else:
--> 968             self._jwrite.save(path)
    969 
    970     @since(1.4)

/databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py in __call__(self, *args)

**Comment by davidrabinowitz** [comment]
Please check that you have properly configured the GCS connector and have the right permissions. Documentation is here: [installation](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/INSTALL.md), [configuration](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/CONFIGURATION.md).
