### ISSUE TITLE
Any plan to support Spark 3.3 with Scala 2.12?

### ISSUE THREAD

**Issue by aajisaka** [GoogleCloudDataproc/spark-bigquery-connector#937]
Hello, I'm Akira from AWS Glue team.

AWS Glue ETL is a serverless data integration service on top of Apache Spark and Spark 3.3 and Scala 2.12 are used in the latest runtime version. I saw the supported version matrix in Google Cloud DataProc and found Spark 3.3 only supports Scala 2.13, that's not compatible with our latest runtime version. 

Is there any plan to support the combination of the versions? If not, how can I contribute?

Reference: https://docs.aws.amazon.com/glue/latest/dg/release-notes.html

**Comment by davidrabinowitz** [comment]
Hi Akira, thanks for pointing that out. The `spark-bigquery-with-dependencies_2.12` works well in Spark 3.3, and we are testing it in our nightly build as well as before releases. This is just an omission in the README, soon to be rectified.

**Comment by aajisaka** [comment]
Thank you @davidrabinowitz !
