### ISSUE TITLE
Using RangePartitioning possible?

### ISSUE THREAD

**Issue by dirk-gasser-db** [GoogleCloudDataproc/spark-bigquery-connector#939]
Is it possible to use BQ RangePartitioning :
bq query \
    --use_legacy_sql=false \
    --destination_table PROJECT_ID:DATASET.TABLE \
    --range_partitioning COLUMN,START,END,INTERVAL \
    'QUERY_STATEMENT'

for writing a table?

**Comment by davidrabinowitz** [comment]
Not yet, but it's on our roadmap

**Comment by davidrabinowitz** [comment]
Duplicate of issue #867
