### ISSUE TITLE
Spark is always producing 1000 partitions when reading from GBQ

### ISSUE THREAD

**Issue by mkvenkatesh** [GoogleCloudDataproc/spark-bigquery-connector#943]
I have a Spark 3.2.1 & Scala 2.12 project where I'm trying to use Spark BQ connector to read data from GBQ and write to S3. This Spark code is running in an AWS EMR cluster.

My spark configuration looks like this;
```
    /bin/runSpark.sh \
    --master yarn \
    --deploy-mode client \
    --driver-memory=2g \
    --executor-cores=4 \
    --executor-memory=10g \
    --conf spark.executor.memoryOverhead=2g \
    --conf spark.executor.extraClassPath=main.jar \
    --conf spark.datasource.bigquery.arrowCompressionCodec=ZSTD \
    --conf spark.datasource.bigquery.viewsEnabled=true \
    --conf spark.datasource.bigquery.materializationProject=my-gcp-project \
    --conf spark.datasource.bigquery.materializationDataset=temp_storage \
    --conf spark.datasource.bigquery.maxParallelism=10 \
    --conf spark.datasource.bigquery.preferredMinParallelism=10 \
    --driver-class-path dist/lib/main.jar \
    --jars dist/lib/main.jar \
    --class com.myclass \
    dist/lib/main.jar
```

Using this gradle dependency
```
compile "com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.29.0"
```

The read/write call roughly translates to this
```
val df = spark.read.format("bigquery").option("filter", "DATE(create_time) = PARSE_DATE('%Y%m%d', '20230205')").load("myproj.schema.table")

df.write.format("orc").mode(SaveMode.Overwrite).option("compression", "zstd").save("s3://somelocation")
```

I know the partition filter is applied successfully because this table requires partition filtering and without passing a valid filter Spark throws an error. The above statement works fine and is able to read from source and write to my destination for only that partition data.

Initially I didn't set any conf for `maxParallelism` or `preferredMinParallelism` thinking the connector is smart enough to set the right parallelism, but it always got 1000 partitions and Spark UI shows 1000 tasks for the stage.

I then added the `maxParallelism` and `preferredMinParallelism` setting and there was no change in how many spark tasks were produced. It was always a 1000.

The size of the input table didn't matter. Small (MBs) or large table (TBs), Spark always produced 1000 tasks.

Some log output if it helps;

```
2023-04-04 20:36:18,357 INFO  START:1680658525 [common.ReadSessionCreator] [ForkJoinPool-1-worker-1] Read session:{"readSessionName":"projects/<redacted>/locations/us/sessions/CAISDEo4eWpocldnR3VfTxoCamkaAmlj","readSessionCreationStartTime":"2023-04-05T01:36:10.157Z","readSessionCreationEndTime":"2023-04-05T01:36:18.325Z","readSessionPrepDuration":598,"readSessionCreationDuration":7570,"readSessionDuration":8168}

2023-04-04 20:36:18,358 INFO  START:1680658525 [common.ReadSessionCreator] [ForkJoinPool-1-worker-1] Requested 20000 max partitions, but only received 1000 from the BigQuery Storage API for session projects/<redacted>/locations/us/sessions/CAISDEo4eWpocldnR3VfTxoCamkaAmlj. Notice that the number of streams in actual may be lower than the requested number, depending on the amount parallelism that is reasonable for the table and the maximum amount of parallelism allowed by the system.

2023-04-04 20:36:18,363 INFO  START:1680658525 [direct.BigQueryRDDFactory] [ForkJoinPool-1-worker-1] Created read session for table '<redacted>': projects/<redacted>/locations/us/sessions/CAISDEo4eWpocldnR3VfTxoCamkaAmlj
```

I tried various versions of the connector and I still get the same result. I hope I'm doing something silly here and there's an obvious thing that I'm missing.

**Comment by davidrabinowitz** [comment]
What is the size of your cluster? What's the default parallelism? 

Can you please share the code sample where you set a small maxParallelism, and the log line which says "Asked for N streams, got only M streams"?

**Comment by mkvenkatesh** [comment]
EMR cluster has 1 master and 2 core nodes to begin with and set to auto scale on task nodes based on how many Spark tasks needs to be processed. I don't set any default parallelism conf, I leave that for Spark to automatically calculated.

`maxParallelism` is set at the spark submit command level as shown below;
```
    --conf spark.datasource.bigquery.maxParallelism=10 \
    --conf spark.datasource.bigquery.preferredMinParallelism=10 \
```

With this configuration set, I still see `Requested 20000 max partitions, but only received 1000 from the BigQuery Storage API` message. There's no change to how many streams are being requested with any of these configurations. I don't see anything in the log about `Asked for N streams, got only M streams` message.

Just to be completely sure, I set this inside the application as well, and there's no change. 

```
  spark.conf.set("maxParallelism", "10")
  spark.conf.set("preferredMinParallelism", "10")
```

**Comment by mkvenkatesh** [comment]
Ha, using the `.option()` for parallelism is taking effect. For some reason passing it via spark-submit or `spark.conf.set` is not sticking.

Is there a better way to control this parallelism factor without hard coding it? The input tables/views that I want to read from GBQ is of varied size and it would be nice if this was set dynamically reasonably based on how much data is being read instead of either default to 1000 or something arbitrary that I can hard code with `.option()`

**Comment by mkvenkatesh** [comment]
After looking at how the read session is created [here](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/6685be74eb865d8a5d1bd33628a7276f8f882199/bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreator.java#L82), I'm able to achieve what I want with a syntax like this

```
val df = spark.read.format("bigquery")
                .option("filter", "DATE(create_time) = '2023-02-05'")
                .load("myproj.schema.table")
                .filter("DATE(create_time) = '2023-02-05')
```

With this syntax, I don't have to set any parallelism settings and Spark seems to produce tasks sensibly based on the data read.

The reason I still kept the `.option("filter")` is that I see from logs that having this on makes a difference in how much data is being read, even with the filter statement.

With `.load().filter()`, I see 9547 rows read

```
Tracer Logs:{"Stream Name":"projects/<redacted>/locations/us/sessions/CAISDHg2US1rZHhleUtHVhoCamkaAmlj/streams/GgJqaRoCaWMoAg","Started":"2023-04-05T15:17:38.515Z","Ended":"2023-04-05T15:17:39.200Z","Parse Timings":"Average: PT0.001713752S Samples: 10","Time in Spark":"Average: PT0.019983635S","Time waiting for service":"Average: PT0.031220483S Samples: 10","Bytes/s":641256,"Rows/s":561588,"Bytes":200072,"Rows":9547,"I/O time":312}
```

With `option("filter").load().filter()`, I see 4774 rows read which matches the partition row count in GBQ
```
Tracer Logs:{"Stream Name":"projects/<redacted>/locations/us/sessions/CAISDE5VTDZNYW9YWGlEYxoCamkaAmlj/streams/GgJqaRoCaWMoAg","Started":"2023-04-05T15:18:27.628Z","Ended":"2023-04-05T15:18:28.122Z","Parse Timings":"Average: PT0.001725517S Samples: 5","Time in Spark":"Average: PT0.017808014S","Time waiting for service":"Average: PT0.074050346S Samples: 5","Bytes/s":270378,"Rows/s":596750,"Bytes":100040,"Rows":4774,"I/O time":370}
```

If you have any insights into making this better please let me know. 

I don't know if there's a bug with how spark configuration is passed into the connector and want me to leave this issue open or if you would like me to close this one out.

Thanks!

**Comment by davidrabinowitz** [comment]
When using `.filter()` (NOT `.option("filter",...)`) please try the following"
```
.filter("DATE(create_time) = DATE('2023-02-05')")
```

When the spark does type does not match exactly to the BigQuery type, it does not push the predicate down to the connector, which results in a larger read. `'2023-02-05'` is a String from spark's perspective, it does not assume that the connector will make the implicit conversion like any other SQL engine does.

**Comment by khaledh** [comment]
We have the same issue. No matter what we set the parallelism to, it's always 1000. We tried setting `spark.datasource.bigquery.preferredMinParallelism = 10000` and `spark.default.parallelism = 10000` but it has no effect. In our case this is a problem because the input table is ~2TB, and using 1000 partitions creates ~2GB per partition, which causes a lot of executor OOMs (exit code 137).

I searched the code base for this number, and found the default [here](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/288bc2c30a4b59a3c64a7e943fe33df5a77cc055/bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfigBuilder.java#L35). What is the correct way to override this default?

**Comment by kmjung** [comment]
> What is the correct way to override this default?

In the short term, this (server-side) limit can be raised on a per-project basis by filing a support request. We're working on some changes that will hopefully improve the default experience here early next year.

**Comment by khaledh** [comment]
@kmjung Thanks for letting me know. It would be good to highlight this in the docs until it gets properly supported.

**Comment by cpantar** [comment]
@khaledh were you able to get the limit increased in your project and did it solve your issue?

**Comment by khaledh** [comment]
@cpantar We ended up repartitioning the dataframe (that represents the input table) to a larger number of partitions before applying further transformations, and this seems to have resolved the issue for us.

**Comment by isha97** [comment]
@mkvenkatesh Please reopen the issue if the fix suggested by @kmjung doesn't work.

**Comment by gtupak** [comment]
@kmjung Do you have any updates? I set both `preferredMinParallelism` and `maxParallelism` to a value over `1000` but they're being ignored as I'm still getting only 1000 partitions from BigQuery.
