### ISSUE TITLE
No data in dataframe when queried from bigquery streaming buffer

### ISSUE THREAD

**Issue by ruixuel** [GoogleCloudDataproc/spark-bigquery-connector#95]
Hi,

I stream some data into bigquery and the data are still in bigquery streaming buffer. Then I use this spark-bigquery-connector to query the streaming data from bigquery, however, I always got 0 data in the dataframe. And the data are only available to be queried after they are inserted into bigquery from the streaming buffer. Is this issue designed by default? Or this is a problem you can help to solve?

Thank you!

**Comment by kmjung** [comment]
This is a known limitation of the [BigQuery Storage API](https://cloud.google.com/bigquery/docs/reference/storage/), which underlies the read side of the Spark connector. Adding the ability to read data from the streaming subsystem is on our road map, but it's a significant amount of work, and I don't have an ETA for you. I will make sure this limitation is added to the documentation.

**Comment by ruixuel** [comment]
Thank you! Do you know there's any other way to query streaming buffer from bigquery to spark dataframe?

**Comment by kmjung** [comment]
As a workaround, you can execute a SELECT * query against the table to force the results to be materialized and then use the Spark connector to read from the destination table; you can see the sample code for reading the results of a query [here](https://github.com/GoogleCloudPlatform/spark-bigquery-connector/blob/master/examples/python/query_results.py). Beware that the storage API also can't yet read very small query results; this will be addressed sooner rather than later, however.

More generally, what's your use case here?

**Comment by ruixuel** [comment]
Thank you for your help! Seems a good solution for me.
Our case is to stream the data into bigquery periodically and use spark to do some data manipulation (ex: sampling, iterative query etc.) then convert the query result to apache arrow.

**Comment by ruixuel** [comment]
I cannot get the destination table_id  through Java API, although it could be retrieved by python API.   Do you have any idea how to get it from Java API just like the example you sent above?

**Comment by ruixuel** [comment]
Never mind, I found it in queryJob.getConfiguration() (Cast to QueryJobConfiguration).getDestinationTable. The documentation is not that nice in Java...
Thank you! I will close this.

**Comment by ruixuel** [comment]
Sorry for bothering again. I am wondering what is the threshold for very small query result. I tested several dataset, seems around 1000?

**Comment by emkornfield** [comment]
We've fixed the issue so that query results of any size can now be read through the API.
