### ISSUE TITLE
BigQuery direct insert fails when spark schema is a subset of BigQuery schema

### ISSUE THREAD

**Issue by nikolay-voskresenskiy-db** [GoogleCloudDataproc/spark-bigquery-connector#954]
Seems like the com.google.cloud.bigquery.connector.common.BigQueryUtil#schemaWritable call in BigQueryDirectDataSourceWriterContext has its arguments in the wrong order, resulting in behavior when the dataframe schema has fewer fields than the bigquery table , it produces a 'Destination table's schema is not compatible with dataframe's schema' error.

1. Create table:
`
CREATE TABLE my_table
(id STRING,
foo STRING,
bar STRING )
`

```
val schema = StructType(
      List(
        StructField("id", StringType, true),
        StructField("foo", StringType, true)
      )
    )
val rowData = Seq(Row("1", "hello world"))
var df= spark.createDataFrame(rowData,schema)


df.write
    .format("bigquery")
    .option("writeMethod", "direct")
    .mode(SaveMode.Append)
    .save("my_table") 
```

java.lang.IllegalArgumentException: com.google.cloud.bigquery.connector.common.BigQueryConnectorException$InvalidSchemaException: Destination table's schema is not compatible with dataframe's schema
	

Additionally, any such schema incompatibility exception does not provide any trace information about which field/record causes a failure, making it extremely inconvenient to diagnose

**Comment by suryasoma** [comment]
please find the fix in the latest release `0.31.0` 
Thanks
