### ISSUE TITLE
While reading data from BQ table getting the below message related to number of paritions

### ISSUE THREAD

**Issue by ajaykamal3** [GoogleCloudDataproc/spark-bigquery-connector#956]
While trying to read data from BQ getting the below info message

INFO ReadSessionCreator: Requested 20000 max partitions, but only received 1 from the BigQuery Storage API for session projects/<project_id>/locations/us/sessions/<sessionid>. Notice that the number of streams in actual may be lower than the requested number, depending on the amount parallelism that is reasonable for the table and the maximum amount of parallelism allowed by the system.

How to fix this so that the data can be read much faster from BQ?

**Comment by 007vasy** [comment]
I have the same problem @davidrabinowitz 

Scenarios:

1. BQ to Dataproc with query: 1-4
with the below code:
```
get_spark().read.format(bq_format).option('query', query).option('materializationProject', materializationProject).option('materializationDataset', materializationDataset).load()
```
2. BQ to databricks with query: 200
```
get_spark().read.format(bq_format).option('query', query).option('materializationProject', materializationProject).option('materializationDataset', materializationDataset).load()
```
'+ parentproject
3. BQ to Dataproc with pure pyspark: 200
```
spark.read.format('bigquery') \
            .option('project', self.project_id) \
            .option('dataset', dataset) \
            .load(table)
```
4. BQ to Dataproc with pure pyspark with increased max partitions limit:  5000ish
```
spark.read.format('bigquery') \
            .option('project', self.project_id) \
            .option('dataset', dataset) \
            .load(table)
```
'+ and we asked google support to increase some internal limit from 200 to 5000, which increased the reading speed

all test and queries had been run on a dataset like this:
https://cloud.google.com/blog/products/data-analytics/ethereum-bigquery-public-dataset-smart-contract-analytics

**Comment by 007vasy** [comment]
will test the 
```
spark.read.format("bigquery").load(sql)
```
with pyspark as well

**Comment by 007vasy** [comment]
neither of those helped,

jar used:
gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.13-0.28.0.jar

**Comment by 007vasy** [comment]
after further testing:
loading via filter + load then select and where: the result is 200 partitons
loading via query -> result is 1 partitions via rdd. getNumPartitions

**Comment by michalbarer** [comment]
The same issue occurred to me as well. This message appears even after closing BQ client, and I believe it affects the performance of the job.

**Comment by NickGrigoriev** [comment]
Same to me, I got this limit on table with 1.2 Physical storage and 17Tb of Logical storage. 27 Partitions.

**Comment by 007vasy** [comment]
You can ask Google to increase the limit

**Comment by isha97** [comment]
This is expected behavior.
