### ISSUE TITLE
Issue with BigNumeric support - Serverless

### ISSUE THREAD

**Issue by karthikt16** [GoogleCloudDataproc/spark-bigquery-connector#959]
Hello,

I’m running serverless spark batch

Jar file used: "gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.30.0.jar"

"runtime_config":{
            "version": "1.1.11",

I got the below error:
 
![image](https://user-images.githubusercontent.com/76015136/235155569-0e7aec75-c2bc-4fd4-b34a-28c31a830d30.png)

The same code when I run on Dataproc with the same Jar file the job succeeds and as specified in the https://github.com/GoogleCloudDataproc/spark-bigquery-connector#bignumeric-support the column gets stored as STRING.

Why is this not working with serverless image? Any pointers please?

**Comment by karthikt16** [comment]
And this error when running serverless 
![image](https://user-images.githubusercontent.com/76015136/235162117-44816ecb-9e74-44d3-a909-90907be995fc.png)

**Comment by davidrabinowitz** [comment]
What's the precision and scale of the decimal field?

**Comment by davidrabinowitz** [comment]
Can you please provide a sample code with a schema (doesn't need to be the one you actually use) with all the types that cause those errors? Thanks!

**Comment by karthikt16** [comment]
> What's the precision and scale of the decimal field?

@davidrabinowitz :

the function to generate the table looks like this

![image](https://user-images.githubusercontent.com/76015136/235621480-adca1636-f0b0-4c6c-86f0-bf9c5459f05d.png)

running it as Pyspark job - the column gets stored as STRING type
![image](https://user-images.githubusercontent.com/76015136/235621928-9e4f0922-b882-43f4-9e02-24e2baf5d5ac.png)

and the data looks like this

![image](https://user-images.githubusercontent.com/76015136/235622403-9d54d9d7-f1cc-4781-a763-72dfabfe6cba.png)

**Comment by karthikt16** [comment]
> Can you please provide a sample code with a schema (doesn't need to be the one you actually use) with all the types that cause those errors? Thanks!

@davidrabinowitz : 

The sample code for data type Vector issue looks like this:

![image](https://user-images.githubusercontent.com/76015136/235624962-2c76fb10-2834-4bfe-af6f-03bcb87c3c5e.png)

and the table stored as this
![image](https://user-images.githubusercontent.com/76015136/235626266-04b327a1-fdd1-4c0d-aa7c-0d2e7c62243a.png)

But this does not work with serverless

**Comment by karthikt16** [comment]
@davidrabinowitz code to replicate issue [bigNumeric.txt](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/files/11572241/bigNumeric.txt). 
It fails with all serverless runtime versions mentioned [here](https://cloud.google.com/dataproc-serverless/docs/concepts/versions/spark-runtime-versions)

**Comment by davidrabinowitz** [comment]
should be fixed in version 0.31.1
