### ISSUE TITLE
SchemaConverters is breaking after 0.30.0,  default config should be provided for the converter

### ISSUE THREAD

**Issue by kaiseu** [GoogleCloudDataproc/spark-bigquery-connector#969]
SchemaConverters.toSpark and SchemaConverters.toBigQuerySchema is static before 0.30.0, while  [PR923](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/923) made it not static, which breaks the application from upgrading to the latest connector, can we have a default config for the converter so that it's compatible for the existing application?

**Comment by kaiseu** [comment]
@davidrabinowitz any suggestions?

**Comment by davidrabinowitz** [comment]
Can you please share a full stack trace?

**Comment by kaiseu** [comment]
@davidrabinowitz  we regard SchemaConverters as a util to convert schema from spark to bq in our app.

**Comment by vishalkarve15** [comment]
Looks like `configuration` is never used within the class. You could pass `null` as a workaround.
I think we could change everything to static since there's no configuration? @davidrabinowitz wdyt?

**Comment by davidrabinowitz** [comment]
It is there for an upcoming feature. There may be another way to implement it, so we can restore SchemaConverters.

**Comment by isha97** [comment]
@kaiseu we can't make the above mentioned functions static as we are using the configuration.
You can use `SchemaConverters.from(SchemaConvertersConfiguration.createDefault())` to make a call to those functions.
Please check the `allowMapTypeConversion` property if you would want to set it in the `SchemaConvertersConfiguration`.
