### ISSUE TITLE
Incremental load within glue etl job utilizing this connector 

### ISSUE THREAD

**Issue by Ahaberling** [GoogleCloudDataproc/spark-bigquery-connector#972]
Hey, 
I'm using this connector within an aws glue etl job (see https://aws.amazon.com/blogs/big-data/migrating-data-from-google-bigquery-to-amazon-s3-using-aws-glue-custom-connectors/). I'm trying to modify the job to load data incrementally. For this, I'm setting an additional connection option with the "datePartition" property. This raises the following error:

'An error occurred while calling o94.getDynamicFrame. com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: request failed: table decorators are not supported in standard SQL'

Any idea how to circumvent this, or how to implement an incremental load differently? It would help me out tremendously.

```
import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job

args = getResolvedOptions(sys.argv, ["JOB_NAME"])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args["JOB_NAME"], args)

# Script generated for node Google BigQuery Connector 0.24.2 for AWS Glue 3.0
GoogleBigQueryConnector0242forAWSGlue30_node1 = (
glueContext.create_dynamic_frame.from_options(
connection_type="marketplace.spark",
connection_options={
"datePartition": "20230501",
"parentProject": "project_name",
"dataset": "dataset_name",
"table": "table_name",
"connectionName": "connection_name",
},
transformation_ctx="GoogleBigQueryConnector0242forAWSGlue30_node1",
)
...
```

**Comment by emkornfield** [comment]
I'm not familiar with the connector on this.  Bu this error means under the cover you are trying to run a query like "select * from table_name@20230501" or at least it is trying to create a read session with the `table_name@20230501`.  This is isn't supported.  To get the same affect you need to have it generate `select * from table_name where datePartition = "2023-05-01"` or pass the similar filter clause when create the read session (datePartition = "2023-05-01).   How this is actually accomplished through Glue, I could not say.
