### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: com/google/cloud/spark/bigquery/BigQueryRelation

### ISSUE THREAD

**Issue by poojac42** [GoogleCloudDataproc/spark-bigquery-connector#975]
Hi David,
I am getting this error after submitting job in dataproc cluster
Caused by: java.lang.NoClassDefFoundError: com/google/cloud/spark/bigquery/BigQueryRelation
can you please help me with this

**Comment by davidrabinowitz** [comment]
Can you please share the Dataproc image version and the job configuration?
