### ISSUE TITLE
Support for BQ DATETIME / Spark 3.4.0 TimestampNTZType

### ISSUE THREAD

**Issue by sixdimensionalarray** [GoogleCloudDataproc/spark-bigquery-connector#977]
Spark has added support for timestamp without time zone (TimestampNTZType) in Spark 3.4.0.  Wanted to bring this to the attention of the maintainers, just to make sure the team is aware!  I work with many customers who struggle with BQ DATETIME type and Spark, so this might be a solution to support BQ DATETIME natively in this connector.

"TimestampNTZType: Timestamp without time zone(TIMESTAMP_NTZ). It represents values comprising values of fields year, month, day, hour, minute, and second. All operations are performed without taking any time zone into account.
Note: TIMESTAMP in Spark is a user-specified alias associated with one of the TIMESTAMP_LTZ and TIMESTAMP_NTZ variations. Users can set the default timestamp type as TIMESTAMP_LTZ(default value) or TIMESTAMP_NTZ via the configuration spark.sql.timestampType."

- https://spark.apache.org/docs/3.4.0/sql-ref-datatypes.html#supported-data-types
- https://issues.apache.org/jira/browse/SPARK-35662

**Comment by davidrabinowitz** [comment]
Hi @sixdimensionalarray thanks for this, we are aware of TimestampNTZType and plan to support it.

**Comment by psonilloyds** [comment]
Hi @davidrabinowitz  - Do we have any timelines(tentative) for this support to be rolled out ? where is this being tracked ? Any JIRA story for the same ?

Thanks in advance.
