### ISSUE TITLE
spark-3.1-bigquery-0.30.0.jar - writes in Parquet not AVRO

### ISSUE THREAD

**Issue by annacielas** [GoogleCloudDataproc/spark-bigquery-connector#984]
According to the documentation:

> The `spark-X.Y-bigquery` connectors use only AVRO as an intermediate format.

However using this connector the intermediateDataFormat is Parquet:

- I checked in the Dataproc 2.0 job details and the Source format was PARQUET
- _df.write_ without _.option('enableListInference', True)_ was not working

**Comment by isha97** [comment]
Hi @annacielas ,

Thank you for bringing this up. The documentation had an error which is fixed now. Pull #1103 
Please use the `intermediateFormat` property to set the  intermediate format.

For the question regarding `enableListInference` not working, can you please elaborate and provide with sample code snippet.
