### ISSUE TITLE
Log verbosity in LoggingBigQueryStorageReadRowsTracer

### ISSUE THREAD

**Issue by idc101** [GoogleCloudDataproc/spark-bigquery-connector#988]
This line in `LoggingBigQueryStorageReadRowsTracer`
```
log.info("Tracer Logs:{}", new Gson().toJson(jsonObject));
```

caused a significant cost increase in our Google Cloud Logging bill (5x increase). Please consider logging this at debug or trace level instead of info.

**Comment by davidrabinowitz** [comment]
Fixed in [version 0.31.1](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/releases/tag/0.31.1)
