### ISSUE TITLE
Spark ML vector does not work on Serverless

### ISSUE THREAD

**Issue by karthikt16** [GoogleCloudDataproc/spark-bigquery-connector#993]
Hello,

Running serverless spark batch

"runtime_config":{
"version": "1.1.11",

I got the below error while saving data to bigquery:

![serverless log 1](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/76015136/a50d9de9-255b-4806-b931-a37a8284e6a0)

![serverless error log](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/76015136/66c4c414-7d05-424a-8828-e8f77b3b04a6)

The same code works on dataproc. I was able to store the table. 
Connector used: gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.24.2.jar

![Saved table using 24_2 jar file](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/assets/76015136/a5530c40-c027-4c7b-8127-4e0718be42b4)

I also tested the same code with the most recent connector "gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.31.1.jar" and here again it fails.

Could you please check?

Code to replicate the issue 
[testvector.txt](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/files/11706062/testvector.txt)

regards

**Comment by davidrabinowitz** [comment]
Fixed in release 0.32.1
