### ISSUE TITLE
Custom Connector - AWS Glue for latest version of spark-bigquery connector

### ISSUE THREAD

**Issue by kaa125** [GoogleCloudDataproc/spark-bigquery-connector#996]
We need to develop a custom connector for AWS Glue that utilizes the latest version of the spark-bigquery connector. The purpose of this connector is to facilitate seamless data integration and transfer between AWS Glue and BigQuery.

The custom connector should leverage the capabilities of AWS Glue, a fully managed extract, transform, and load (ETL) service, to efficiently process and transform data before transferring it to BigQuery. The latest version of the spark-bigquery connector should be used to establish a reliable and high-performance connection between AWS Glue and BigQuery.

If any person has any experience or provide guidance on how to leverage the latest version in a custom way. please do provide your guidance.

**Comment by davidrabinowitz** [comment]
Can you please provide more details about what you're trying to achieve? Also, have you tried to use the connector in AWS Glue for Spark?

Lastly - can [BigQuery Omni](https://cloud.google.com/bigquery/docs/omni-introduction) serve your needs?

**Comment by kaa125** [comment]
The goal is to create an ETL pipeline from AWS RDS database to BigQuery using AWS Glue via glue job which includes data migration, incremental updates and triggering new schema events on an hourly basis. We have to migrate data from RDS to BigQuery for our warehouse but there have been issues regarding spark connector for BigQuery as the marketplace has an older version. A custom connector can leverage the updated version of the spark connector. Guidance will be highly appreciated regarding this.

**Comment by kabdulahad** [comment]
@davidrabinowitz Did you check on this

**Comment by isha97** [comment]
@kaa125 Which marketplace are you referring to here? Can you please highlight why do you need a custom connector to be able to use the latest version of the spark bigquery connector? All the connector versions are available to use.

**Comment by isha97** [comment]
Closing this issue, @kaa125 please reopen if you still need help on this.
