### ISSUE TITLE
Destination BQ table's schema is not compatible with Spark dataframe's schema

### ISSUE THREAD

**Issue by shree-ca** [GoogleCloudDataproc/spark-bigquery-connector#999]
Data is read from BQ table then perform some transformations in scala (Spark).  When dataframe is in writing stage using below

`df_insight_om1.distinct().repartition(6).write.format("bigquery").mode("append").option("table", s"${bq_gcp_project}.xxx.XXX_INSIGHT_OM").option("temporaryGcsBucket", s"${tempLocation}").partitionBy("DT_SKEY").save() `then it is errored out as 
```
23/06/14 22:32:29 ERROR com.google.cloud.bigquery.connector.common.BigQueryClient: Unable to create the job to load to prj-cxbi-dev-nane1-eng-edw.xxx.XXX_INSIGHT_OM

Exception in thread "main" com.google.cloud.bigquery.connector.common.BigQueryConnectorException: Failed to write to BigQuery

Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: Error while reading data, error message: Parquet column 'APPOINTMENTDATE' has type BYTE_ARRAY which does not match the target cpp_type INT32. File: gs://bkt-echat-dev-nane1-cxbi-data/.spark-bigquery-application_1686780304908_0001-df1ae331-2317-46e7-91b7-65e68c8e6901/part-00001-08bae64b-2928-43ee-b718-4a00a5545dcf-c000.snappy.parquet
```
BQ table has APPOINTMENTDATE' has data type "DATE".

Further tried to write in Direct mode ,I added following configs in the write statement (direct mode) 

`df_insight_om1.distinct().repartition(6).write.format("bigquery").option("enableModeCheckForSchemaFields", "false").option("writeMethod", "direct").mode("append").option("table", s"${bq_gcp_project}.xxx.XXX_INSIGHT_OM").partitionBy("DT_SKEY").save()` then another error is thrown
```
Caused by: java.lang.IllegalArgumentException: com.google.cloud.bigquery.connector.common.BigQueryConnectorException$InvalidSchemaException: Destination table's schema is not compatible with dataframe's schema
```
But BQ table's schema and dataframe schema are idential. 

Tried 2 versions - 0.29.0 to 0.31.0 as below 
```
<!-- https://mvnrepository.com/artifact/com.google.cloud.spark/spark-bigquery -->
<dependency>
    <groupId>com.google.cloud.spark</groupId>
    <artifactId>spark-bigquery_2.13</artifactId>
    <version>0.31.0</version>
</dependency>
```
Google team suggested to raise this issue in this place.
Note: Using Scala 2.12

Thanks

**Comment by suryasoma** [comment]
can you print the schema for the dataframe and table?
to do it that you can do `df_insight_om1.printSchema()` and `spark.read.format("bigquery").option("table",s"${bq_gcp_project}.xxx.XXX_INSIGHT_OM").load().printSchema()`

**Comment by davidrabinowitz** [comment]
Couple of additional comments: 
* If yo use Scala 2.12, then use the `spark-bigquery-with-dependencies_2.12` connector. 
* The connector does not support the `partitionBy()` method yet, please use `.option("datePartition", "DT_SKEY")` instead.

**Comment by shree-ca** [comment]
Hi suryasoma and davidrabinowitz,

Thanks for responding on my issue. I changed the datatype to String which are Timestamp and then executed spark job. It worked for me.  In my current code, I am using partitionBy("DT_SKEY").

**Comment by shree-ca** [comment]
Thanks a lot for all your support. Feeling good.
